### ISSUE TITLE
Add support for YandexMaps

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#109]
Suggested at [Maps talk page](https://www.mediawiki.org/wiki/Topic:Syaykhvnj57rkasf).

**Comment by kghbln** [comment]
There is the [WikivoteMapsYandex extension](https://www.mediawiki.org/wiki/Extension:WikivoteMapsYandex) which is currently unmaintained and implemented this with Maps as an dependency.

**Comment by JeroenDeDauw** [comment]
If someone has interest in doing so, great, create a pull request or open a new issue to discuss it.
