### ISSUE TITLE
Add support for MWs new extension registration

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#126]
This needs to be done in such a way the extension still works with older versions of MW (down to MW 1.23) and continues to work via Composer in the way existing users expect it to.

Some of the features of the extension registration should also not be used:
- Hooks
- autoloading
- SpecialPages, Actions, JobClasses, APIModules

This one is up for the taking. Help with it is much appreciated.

**Comment by JeroenDeDauw** [comment]
Ping @paladox

**Comment by paladox** [comment]
@JeroenDeDauw sorry I didn't write sooner but yep I can do it.

**Comment by paladox** [comment]
@JeroenDeDauw which mw versions would you like it to be compatible with.

**Comment by JeroenDeDauw** [comment]
As already mentioned, MW 1.23 and up :)

**Comment by paladox** [comment]
Ok.

**Comment by JeroenDeDauw** [comment]
2018 and no clear benefit for the user of having this, so closing this task for now
