### ISSUE TITLE
Inline Label crash the map

### ISSUE THREAD

**Issue by devilmanozzy** [JeroenDeDauw/Maps#13]
A week ago or so I noticed the maps on the wiki started not working right. Seemed to be either related to the markers or text labels (Inline Labels). Anyways, I hope this will be corrected. The labels were part of what made the map work so well.

 http://ghostbusters.wikia.com/wiki/User:Devilmanozzy/Map_testbed

**Comment by JeroenDeDauw** [comment]
If this is still an issue with the latest version, please open a new issue with a clear description of how to replicate the problem, or a link to an example on https://sandbox.semantic-mediawiki.org/
