### ISSUE TITLE
Add missing messages

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#137]
* maps-googlemaps3-par-resizable
* maps-googlemaps3-par-searchmarkers

Seen on http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Ask when using format Google Maps v3

**Comment by kghbln** [comment]
Related to https://github.com/JeroenDeDauw/Maps/issues/67 In the meantime I have forgotten what I wanted to tell myself with it.
