### ISSUE TITLE
Icons clustering makers not shown

### ISSUE THREAD

**Issue by waandershz** [JeroenDeDauw/Maps#138]
For some days now the icons for clustering markers aren't shown anymore.
See: https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_marker_clustering

We use them here: https://www.deltaexpertise.nl/wiki/index.php/Dijkvakken_Zeeland_VN

Has something to do with references Google-sites. Console browser gives error messages like 
> Failed to load resource: the server responded with a status of 404: https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png

Also see:
- http://stackoverflow.com/questions/37087583/google-maps-not-working-in-https
- https://github.com/googlemaps/js-marker-clusterer/issues/55
- https://wp-types.com/forums/topic/404-error-in-toolset-maps-due-to-outdated-googlecode-refs/

**Comment by PeterTheOne** [comment]
https://github.com/JeroenDeDauw/Maps/blob/637e120d81681ed71646ddeb2e85cb9be2ef06d4/includes/services/GoogleMaps3/gm3-util-library/markerclusterer.js#L1578 should point to a local copy of the images..

**Comment by waandershz** [comment]
@PeterTheOne So? We just use the extension and this code:

```
{{#ask: [[Category:Dijkvak]]
| ?Coordinate
| limit=500
| markercluster=yes
| format=map
}}
```

**Comment by kghbln** [comment]
@waandershz There is nothing you can do on wiki.

**Comment by waandershz** [comment]
@kghbln What do you mean? We just have to wait till next extension version?

**Comment by kghbln** [comment]
Affirmative.
