### ISSUE TITLE
Do 3.6.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#147]
@PeterTheOne any objections?

**Comment by PeterTheOne** [comment]
Maybe merge #146? Other than that, go ahead. :)

**Comment by PeterTheOne** [comment]
And maybe #148 #149 #150 #151 #152 #153? ^^

**Comment by JeroenDeDauw** [comment]
Thanks for those. Let's see if https://github.com/JeroenDeDauw/Maps/issues/50 is easy to resolve before releasing.

**Comment by PeterTheOne** [comment]
Only #50 left.
