### ISSUE TITLE
Remove obsolete and thus unused system messages

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#169]
* [x] maps-displaypoint-description

@JeroenDeDauw About the following two:
* [x] maps_osm
* [x] maps-osm-par-thumbs
* [x] maps-osm-par-photos

Do you happen to know what happend to them? Introduced with [Maps 0.7](https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#new-features-5). Only found these in the .json-files.

**Comment by JeroenDeDauw** [comment]
I do not recall

**Comment by kghbln** [comment]
Just had a second look [OSM was disabled with v2.0.0](https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#compatibility-changes-1) and probably killed at a later stage without a note. Anyhow, will kill these after the next translation update.

**Comment by JeroenDeDauw** [comment]
Yeah, we don't have a dedicated OSM service any more
