### ISSUE TITLE
add dataItems (in javascript) for coordinates

### ISSUE THREAD

**Issue by PeterTheOne** [JeroenDeDauw/Maps#171]
Like these https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/res/smw/data.

**Comment by JeroenDeDauw** [comment]
Ugh. Such a developer! <o>

I think it is important to describe the goal in issues, optionally followed by possible technical approaches.

**Comment by JeroenDeDauw** [comment]
Closing to keep the discussion in one place: https://github.com/SemanticMediaWiki/SemanticMaps/pull/72
