### ISSUE TITLE
Do 3.7.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#172]
Ping @kghbln @PeterTheOne any reason to not do this in the next few days?

The one thing I'd like to do before is to at least disable the layer functionality by default. See https://github.com/JeroenDeDauw/Maps/issues/168

**Comment by kghbln** [comment]
Not from my side. Let the coolness rule! :) Will try to do https://github.com/JeroenDeDauw/Maps/issues/169 today but it does not really matter if this is in or out.

**Comment by PeterTheOne** [comment]
Go for it.

**Comment by kghbln** [comment]
https://github.com/JeroenDeDauw/Maps/issues/169 is done. Just needs to be merged.

**Comment by PeterTheOne** [comment]
Maybe have a look at #155?

**Comment by PeterTheOne** [comment]
Ok, let's keep #155 out of this release..
