### ISSUE TITLE
Add system messages directly

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#178]
Currently the following system messages as [seen here](https://www.semantic-mediawiki.org/wiki/Help:Ergebnisformat_googlemaps) are created in a patchwork manner via [L374](https://github.com/JeroenDeDauw/ParamProcessor/blob/master/src/ParamDefinition.php#L374) of the ParamProcessor extension and pop up as missing for the Validator extension:

* [ ] validator-type-mapscircle-list
* [ ] validator-type-mapsimageoverlay-list
* [ ] validator-type-mapsline-list
* [ ] validator-type-mapslocation-list
* [ ] validator-type-mapslocation
* [ ] validator-type-mapsrectangle-list
* [ ] validator-type-wmsoverlay

These should be added here directly by reusing one of the following [L20-L31](https://github.com/JeroenDeDauw/Validator/blob/master/i18n/en.json#L20-L31) system messages provided by the Validator extension.

See https://github.com/JeroenDeDauw/Validator/issues/15#issuecomment-229033012

**Comment by JeroenDeDauw** [comment]
I'm not sure where you've seen `validator-type-mapscircle-list` and some of the others. `#mapsdoc` only shows parameters specific to mapping services. It does not show the base ones supported by `#display_map`.

**Comment by kghbln** [comment]
> I'm not sure where you've seen validator-type-mapscircle-list and some of the others.

I linked to [the page on "googlemaps"](https://www.semantic-mediawiki.org/wiki/Help:Ergebnisformat_googlemaps) in my initial report where all these message can still be seen.

**Comment by kghbln** [comment]
Well I could have done the change too. I figured you will probably have a got at:

> Currently the following system messages as seen here are created in a patchwork manner via L374 of the ParamProcessor extension
