### ISSUE TITLE
Option to add version number

### ISSUE THREAD

**Issue by Henryfunk** [JeroenDeDauw/Maps#181]
It wiould be a good idea to add the option for users to supply a version number. Google at any given time has three versions of Google Maps API for JS: a frozen version, a standard version and an experimental one. According to https://developers.google.com/maps/documentation/javascript/versions#version-rollover-and-version-types : "If you do not explicitly specify a version, you will receive the experimental version by default if you are on the standard plan (this includes customers who do not provide a key). If you're on the premium plan and don't specify a version, you will receive the release version by default."

**Comment by PeterTheOne** [comment]
It is easy to implement. Can you explain why you need it? Why isn't the default good?

**Comment by Henryfunk** [comment]
Well, originally I asked if this was a good idea, and Jeroen thought it was, but I don't really need it myself. It's just that people might prefer a non-experimental version of Google Maps to an experimental one or vice versa. The reason the dault might not be good is that it isn't one version, it is two versions: for those who pay Google it's the standard (version), for those who don't it's an exsperimental version. If those who don't pay for Google Maps wish to use a version that has been around longer and so is more likely to be stable in terms of functionality, they would then have the option to select that version.
