### ISSUE TITLE
tiles missing when expanding map window

### ISSUE THREAD

**Issue by Flexmaen** [JeroenDeDauw/Maps#182]
If you grab the bottom border of the map and expand it, tiles will be missing, even if you move the map.
It seems that this bug gets fixed if you resize your browser window. (Tried on different browsers).

You need to set
|resizable=yes

Example, see here:
![sm_bug](https://cloud.githubusercontent.com/assets/6330276/16598113/a6deaaee-42fc-11e6-9ab3-b07a59541039.jpg)

Tested with:
Semantic Maps 2.0.1.2, Maps (Version 2.0.1)
Semantic Maps 3.4.0-alpha (354da01), Maps 3.7.0

Both with the same result.
Also happened with both format=googlemaps and format=leaflet.

**Comment by PeterTheOne** [comment]
Does this only happen with googlemaps3 or also leafletjs and openlayers?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting the issue. I thought this was already in the issue tracker but it looks like it's not. This bug has been there for a long time indeed.

**Comment by PeterTheOne** [comment]
Not really sure what is going on but for me jquery.ui.resizable doesn't load:

Repsonse:

    mw.loader.implement("ext.maps.resizable",function($,jQuery){});

**Comment by JeroenDeDauw** [comment]
This appears to no longer be an issue in the latest version (5.5.5), both for Leaflet and Google Maps. Demo: https://sandbox.semantic-mediawiki.org/wiki/Resizable_map
