### ISSUE TITLE
Change `egMapsDefaultService` default away from Google Maps

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#184]
Since Google now requires a key for new instances (see https://github.com/JeroenDeDauw/Maps/issues/179) that must be added to the configuration I suggest to change the default of [``egMapsDefaultService``](https://github.com/JeroenDeDauw/Maps/blob/master/Maps_Settings.php#L30) to "openlayers" allowing the Maps extension to work out of the box without configuration. If someone wants to use Google he or she will have to touch the configuration anyway. Such a default also feels more free to me. The disadvantage obviously is that existing instances are forced to touch their setup. We could also wait until Google makes the key mandatory which I feel will probably happen at one point in the future sooner or later.

@JeroenDeDauw @PeterTheOne Thoughs?

**Comment by PeterTheOne** [comment]
Good point, I'm for changing away from google as default. Why do you prefer openlayers over leaflet?

**Comment by kghbln** [comment]
> Why do you prefer openlayers over leaflet?

Last time I looked at things a bit closer there were some things one was able to do with "openlayers" which were not possible with "leaflet". So the reason is that there are more features to work with though I cannot remember which features exactly.

**Comment by JeroenDeDauw** [comment]
Sounds reasonable. Though the behaviour change for existing users is significant. This would require a new major release.

**Comment by kghbln** [comment]
> This would require a new major release.

Yeah. I just created an Maps 4.0 milestone to track this.

**Comment by PeterTheOne** [comment]
Leaflet is up to date and getting some new features/plugins, I recommend using it as default. Tell me if something important is missing compared to openlayers (`searchmarkers` maybe?). Openlayers is also still on version 2 and `jquery.openlayers.js` is a mess.

**Comment by kghbln** [comment]
> Leaflet is up to date and getting some new features/plugins, I recommend using it as default.

Fine with me. I suggested "openlayers" since it offers/offered more features out of the box. This left aside if they are actually needed. Perhaps asking via the mailing list for frequently used features is a way to find out.

**Comment by JeroenDeDauw** [comment]
I'm fine with changing this to Leaflet
