### ISSUE TITLE
 Leaflet tile layer URL

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#186]
Hello,

It would be useful to be able to set the tile layer URL for Leaflet.
Currently we can't choose anything else than OSM.

(Originally reported here: https://github.com/SemanticMediaWiki/SemanticMaps/issues/87)

**Comment by kghbln** [comment]
@Rudloff Isn't this a possible dupe to https://github.com/JeroenDeDauw/Maps/issues/92?

**Comment by Rudloff** [comment]
Yes it is a dupe, sorry.

**Comment by kghbln** [comment]
You do not have to be sorry. Happens to me all the time too. I just wanted to make sure that we are indeed talking about the same thing.
