### ISSUE TITLE
Leaflet fullscreen

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#187]
Hello,

It would be nice to be able to use `enablefullscreen` with Leaflet.
There is a nice plugin that does that: https://github.com/brunob/leaflet.fullscreen

(Originally reported here: https://github.com/SemanticMediaWiki/SemanticMaps/issues/86)

**Comment by PeterTheOne** [comment]
I'm wondering if it works with Leaflet version 1.0.0, so I asked in the linked repository. Also I would wait for https://github.com/JeroenDeDauw/Maps/pull/174 to be merged.

**Comment by PeterTheOne** [comment]
Seems to work with Leaflet version 1.0.0 and 1.0.0-rc2 is merged, I will have a look at this.
