### ISSUE TITLE
Rephrasing "Maps-googlemaps3-par-clustermaxzoom"?

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#188]
From [Phabricator](https://phabricator.wikimedia.org/T139935): I cannot understand what the message "The maximum zoom level that a marker can be part of a cluster." means in English.

**Comment by kghbln** [comment]
As I understand it the marker can be - if applicable - part of a cluster until the zoom level provided is reached so "The maximum zoom level a marker can be part of a cluster" (without "that") or "The maximum zoom level a marker may be used to form a cluster". Probably a native speaker may help out here.

@PeterTheOne Is my interpretation correct and what do you think of the suggestions for rephrasing?
@amire80 FYI

**Comment by PeterTheOne** [comment]
Feel free to rephrase.. it was the original text from the clusterer documentation.

Maybe: "The greatest/highest/maximum zoom level where markers are clustered."?

**Comment by kghbln** [comment]
@PeterTheOne Thanks for your info and suggestion. I came up with a slightly different wording which should be clear.

**Comment by kghbln** [comment]
@PeterTheOne Thanks for merging. @amire80 Change should roll in soon.
