### ISSUE TITLE
Exception encountered, of type "Error" 

### ISSUE THREAD

**Issue by a01020304uk** [JeroenDeDauw/Maps#216]
Hello, I have added Maps and SemanticMaps to my extension folder and then checked version page and both are showing as active!
I then goto my page and add a test code {{#display_map:address=Brandenburg Gate, Berlin, Germany}}
and save the page
I then load the page to view it and then get blank page with this error
Exception encountered, of type "Error" 

I go back to the page and delete the code and check it again and page loads fine but add the code and it fails again.
![sw1](https://cloud.githubusercontent.com/assets/14941361/17835572/d4b0d270-676a-11e6-9494-43d0f6b261b2.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/14941361/17835574/f6862e22-676a-11e6-9822-f8c23c6e0526.jpg)

**Comment by JeroenDeDauw** [comment]
Can you try the latest version of Maps?

**Comment by a01020304uk** [comment]
I am getting same error.
I am using mediawiki 1.27 and also the Maps and SemanticMaps versions 1.27
When I use the wfLoadExtension command in localsettings it dies not like it so used require_once  and then get the error as listed in initial post.

If I remove Maps from extension folder I get the error saying semanticMaps is required, if I remove semanticMaps then wiki loads fine, but as soon as I add Maps it fails and gives error and nothing loads.

**Comment by JeroenDeDauw** [comment]
If you installed Maps with Composer, as per the install instructions, you should not need to do any require or wfLoadExtension stuff in LocalSettings.

> SemanticMaps versions 1.27

There is no such version

**Comment by a01020304uk** [comment]
I do not know how to install through composer, that concept is way beyong my understanding.
i downloaded  from here
https://www.mediawiki.org/wiki/Special:ExtensionDistributor/Maps
https://www.mediawiki.org/wiki/Special:ExtensionDistributor/SemanticMaps

once downloaded i installed the folders manually through ftp to extensions folder then added the code to local settings

**Comment by mwjames** [comment]
> i downloaded from here
https://www.mediawiki.org/wiki/Special:ExtensionDistributor/Maps
https://www.mediawiki.org/wiki/Special:ExtensionDistributor/SemanticMaps
>once downloaded i installed the folders manually through ftp to extensions folder then added the code to local settings

This is __not going to work__! @kghbln Maybe we should note somewhere (for all repos related to https://github.com/SemanticMediaWiki/) that using `Special:ExtensionDistributor` will result in incorrect tar packages hence it cannot be used.

Composer is more than just as a "download tool", it builds packages with the correct dependencies and if required infuses additional software that can or is not available via `Special:ExtensionDistributor` or via the normal git download therefore you cannot expect a simple download to work.

> I do not know how to install through composer, that concept is way beyong my understanding.

You are only required to install Composer as outlined in [0] and with the next command hereafter `composer require mediawiki/semantic-maps:~3.3` to retrieve the package, yet you went through all the trouble to download Maps and Semantic Maps manually (probably in versions that don't match and work with each other) to do a "folders manually through ftp to extensions folder then added the code to local settings" which most likely is/was more effort and error prone then just to let Composer do the work.

PS: Software provided by us are made and developed in volunteer capacity hence we choose tools that help us to make the most of our time without going to a lot of maintenance burden. Building tar packages, keeping manually track of dependencies are just one of several tasks that is taken over by Composer where it reduces the amount of effort we need to spend to provide a professional working software.

[0] https://getcomposer.org/download/

**Comment by mwjames** [comment]
> Exception encountered, of type "Error" 

In future when you encounter a similar error, it would be most helpful to the party who is expected to reply to provide a full stack trace as described in [0].

[0] https://www.semantic-mediawiki.org/wiki/Stack_trace

**Comment by JeroenDeDauw** [comment]
`Special:ExtensionDistributor` does not give you stable releases of the extensions, does not include their dependencies, and in this case does not even get the code from the correct git repository. I strongly recommend against using it, as I have done for years. During which, coincidentally, none of these issues where addressed.
