### ISSUE TITLE
Special:MapEditor Failing to Load

### ISSUE THREAD

**Issue by JasonJones23** [JeroenDeDauw/Maps#217]
MapEditor is giving an error are you aware of this?
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

I am using Maps 3.7.0

**Comment by JeroenDeDauw** [comment]
Loading fine at http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:MapEditor

Do the regular embedded maps on your wiki work?

**Comment by JasonJones23** [comment]
I use OSM for maps and they show fine on my pages but when I visit Special:MapEditor I get this as shown on attached screenshot
![oops](https://cloud.githubusercontent.com/assets/21164381/17866663/4a505d2c-689f-11e6-9fc0-14fe533b65b3.png)

**Comment by JeroenDeDauw** [comment]
I guess Google Maps is not set up correctly on your wiki then. Which might not be possible to do with 3.7 due to https://github.com/JeroenDeDauw/Maps/issues/179

You could use the latest development version of Maps, or wait for 3.8, which we really ought to release anyway https://github.com/JeroenDeDauw/Maps/issues/210

**Comment by JasonJones23** [comment]
How do I install the developer version as php composer.phar require mediawiki/maps "*" only gives 3.7 version

**Comment by JeroenDeDauw** [comment]
Use `@dev`instead of `*`

**Comment by JasonJones23** [comment]
i did that, now all i get is a blank white page when try and load mapeditor

**Comment by JeroenDeDauw** [comment]
Completely blank? That's not a good sign,,,

Maps 3.8 has been released now, so you can switch back to using a stable version.

Also see https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#configuration

**Comment by JasonJones23** [comment]
updated and still the same
http://www.all-about-ayrshire.tk/index.php?title=Special:MapEditor

**Comment by PeterTheOne** [comment]
You are getting a [`MissingKeyMapError`](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error), you need to set the [api key](https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#configuration).

**Comment by JeroenDeDauw** [comment]
Would be good to give the user some hint that they need to set the key when this happens. New issue: https://github.com/JeroenDeDauw/Maps/issues/222

**Comment by JasonJones23** [comment]
Peter, just a pity no one mentioned a key was needed in the previous messages

**Comment by JeroenDeDauw** [comment]
What do you mean? I said so and included the same link...
