### ISSUE TITLE
Fluff up 3.8 release notes

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#221]
Some docu/example links would be great, so users can actually understand how to use the new features. I think something like the link I added to the rotate control point in the 3.7 section works well.

**Comment by JeroenDeDauw** [comment]
@PeterTheOne any interest in doing this for the stuff you added?

Would be cool to have this before announcing the release.

**Comment by PeterTheOne** [comment]
- [Leaflet marker clustering](http://sandbox.semantic-mediawiki.org/wiki/Leaflet_marker_clustering)
- [Google Maps marker clustering](http://sandbox.semantic-mediawiki.org/wiki/Google_Maps_marker_clustering) (older, but still not moved to semantic-mediawiki.org)
- [Leaflet fullscreen](http://sandbox.semantic-mediawiki.org/wiki/Leaflet_fullscreen)

Please copy those to semantic-mediawiki.org. Access to semantic-mediawiki.org would be nice.

**Comment by JeroenDeDauw** [comment]
> Access to semantic-mediawiki.org would be nice.

/me MAWs @kghbln

**Comment by JeroenDeDauw** [comment]
@PeterTheOne do you have an account yet?

**Comment by JeroenDeDauw** [comment]
I moved the examples to the SMW wiki and linked them from the release notes

**Comment by kghbln** [comment]
Sorry for not reacting. I was not in Berlin and did not realise that this is a release blocker. Yeah the reason for adding this to sandbox.smw.o first is that smw.o only gets updated after the tag was done. So these example will not work at first. When it comes to transferring the examples it is just a matter of having an account at smw.o
