### ISSUE TITLE
#display_map fails on certain chars?

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#223]
**Setup**
- MediaWiki     1.27.1 (a52d35d) 06:46, 23 August 2016
- PHP   5.6.24-0+deb8u1 (apache2handler)
- MariaDB   10.0.27-MariaDB-1~jessie
- Maps  3.8.0 (a8e86d1) 16:20, 24 August 2016

**Issue**
- `{{#display_map:Schloßstraße 29, Frankfurt am Main, Germany|service=leaflet|width=280|height=280}}` does only give the centre of Frankfurt since "Schloßstraße" is not recognized.
- `{{#display_map:Schlossstraße 29, Frankfurt am Main, Germany|service=leaflet|width=280|height=280}}` gives the correct location in Frankfurt since "Schlossstraße" is recognized.

However, "Schlossstraße" is incorrect since it is a name that does not change. See also the tiles which are correctly showing "Schloßstraße". It does not matter that according to new writing rules a "Schloß" is nowadays written as "Schloss".

**Example**
- [See sandbox](http://sandbox.semantic-mediawiki.org/wiki/Issue/223_%28M%29)

This rolled in with the 3.8 release I believe. All services are affected, "googlemaps", "openlayers" and "leaflet".

**Comment by JeroenDeDauw** [comment]
@PeterTheOne any idea which change could have caused this?

**Comment by PeterTheOne** [comment]
@kghbln which geocoder are you using?

**Comment by kghbln** [comment]
>  which geocoder are you using?

All of them fail, i.e. "googlemaps", "openlayers" and "leaflet".

**Comment by JeroenDeDauw** [comment]
Looking at the linked sandbox page, this appears to have been fixed. @kghbln can you confirm?

**Comment by kghbln** [comment]
> Looking at the linked sandbox page, this appears to have been fixed. @kghbln can you confirm?

Affirmative. Lucky us since was a really painful issue.
