### ISSUE TITLE
Maps + Composer - Bug

### ISSUE THREAD

**Issue by Azot94** [JeroenDeDauw/Maps#224]
I have installed Maps and Composer (the latest version) on MW 1.27.1. On special pages I can't export any pages (Special:Eksport) because I have an error:

`Fatal error: OOUI\InputWidget cannot use OOUI\FlaggedElement - it is not a trait in /home/czarnob1/domains/czarnobyl.pl/public_html/wiki/vendor/oojs/oojs-ui/php/widgets/InputWidget.php on line 11`

The same error I have on another Special Pages (fe. ChangeContentModel)

My installed extensions:

Nuk, PdfHandler, Renameuser, SpamBlacklist, TitleBlacklist, Validator, WikiEditor, ApprovedRevs, Cite, Confirm Edit, Gadgets, GoogleAnalytics, InputBox, Interwiki, Localisation, MobileFrontend, MultimediaViewer, Poem, Scribunto, Scribunto, SocialProfile, VisualEditor, SyntaxHighlight_GeSHi, 'ParserFunctions, Echo, Flow, TemplateData, Popups, TextExtracts, PageImages,EventLogging, RevisionSlider

Also Flow extension doesn't work:

`Fatal error: OOUI\ButtonWidget cannot use OOUI\ButtonElement - it is not a trait in /home/czarnob1/domains/czarnobyl.pl/public_html/wiki/vendor/oojs/oojs-ui/php/widgets/ButtonWidget.php on line 9`

**Comment by JeroenDeDauw** [comment]
Does not look like a Maps issue to me. I suggest you report this on the MediaWiki mailing list.
