### ISSUE TITLE
RFC: Merge Maps and Semantic Maps

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#227]
I'm thinking of merging Semantic Maps into the Maps extension. There seems to be little benefit of having them separately, be it for the users or the developers.

The Semantic Maps functionality would automatically enable itself if Semantic MediaWiki is also installed, and could be disabled via a setting.

**Comment by PeterTheOne** [comment]
Would be fine with me, I don't have a strong opinion/preference on this.

**Comment by JeroenDeDauw** [comment]
Do you have concerns about doing this "now", ie before the next release of either Maps or SM?

**Comment by PeterTheOne** [comment]
I would like to see one release of SM before that.

**Comment by JeroenDeDauw** [comment]
This merge will happen. I got a bunch of +1 in private mails and no real concerns. Now tracked at https://github.com/JeroenDeDauw/Maps/issues/233

**Comment by kghbln** [comment]
There was an [interesting suggestion](http://wikimedia.7.x6.nabble.com/Merging-Semantic-Maps-into-the-Maps-extension-tp5067419p5067440.html) on the mailing list though I think that moving the map results format to SRF introduces a dependency which this RFC wants to avoid.

**Comment by JeroenDeDauw** [comment]
Then SRF would partially depend on Maps, and again, you'd need two extensions on top of SMW to get the semantic maps stuff. From a dev point of view it also does not make a lot of sense, as you'd lose the strong cohesion that the maps and sm code has. Separation of concerns is good, though is better done on another level (ie separating out cohesive libraries that do not depend on MW, such as DataValues Geo)

**Comment by JeroenDeDauw** [comment]
Now tracked at https://github.com/JeroenDeDauw/Maps/issues/233
