### ISSUE TITLE
Merge in Semantic Maps

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#233]
* [x] First step: get Maps tests to pass with SM code include
* [x] Second step: get SM tests to pass
* [x] Third step: have CI run both with and without SM
* [x] Fourth step: update README and INSTALL
* [x] Fifth step: cleanup
* [x] Declare replacement of SM in composer.json
* [x] Declare SMW compatibility in composer.json
* [ ] Sixth step: larger refactoring: organize code by feature, with some depending on SMW for being enabled. Definitely for a different PR. Might even want to do a release before, since this is internal anyway

Additional TODOs:

* [x] Lock SM repo and point here
* [x] Migrate SM issues and PRs
* [ ] Merge docs on MediaWiki.org
* [ ] Merge docs on semantic-mediawiki.org

**Comment by kghbln** [comment]
@JeroenDeDauw Will it be necessary to switch from master to a stable version while the merge of these two extensions is being done to avoid preliminary issues caused by the transition. I have sites like e.g. sandbox in mind which run daily updated master versions.

**Comment by kghbln** [comment]
Thanks for the info. Sounds like a plan.

**Comment by kghbln** [comment]
Ah, something that comes to my mind.  Composer needs know not to install SM if Maps 4.0+ is present and vice versa. Dunno if this is a final fluff thing for SM including updating the docu over there.

**Comment by JeroenDeDauw** [comment]
Ah right. I've updated the TODO list. This also made me realize that the compatibility with SMW is not defined yet.

**Comment by JeroenDeDauw** [comment]
Actually things should not blow up if SM would get installed, since it prevents double loading itself by checking if SM_VERSION is set, which is now set by Maps. On top of that, no version of SM specifies it's compatible with Maps 4.x, so you can't install them together based on that alone. Anyway, with https://github.com/JeroenDeDauw/Maps/issues/251, things are now even more fluff.
