### ISSUE TITLE
Forminput doesn't work with HeaderTabs

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#240]
Reported by @jqnatividad on 22 Sep 2014 at https://github.com/SemanticMediaWiki/SemanticMaps/issues/26
## 

As a workaround to #25, tried using HeaderTabs in a Form to prompt for 5 locations using a map input type, but it also doesn't work.

![define_knowledge_product__test_666_-_knowledge_commons](https://cloud.githubusercontent.com/assets/1980690/4361886/5bef38a8-4288-11e4-9ea4-b3d4bc42825e.jpg)

As soon as I resize the browser window though, it seems to work.  Maybe, triggering a map resize will help? (http://stackoverflow.com/questions/3014156/google-maps-and-jquery-tabs)

**Comment by JeroenDeDauw** [comment]
Feature moved to Page Forms extension

**Comment by kghbln** [comment]
I am pretty sure that this still does not work. Thus pinging @yaronkoren to make him aware of this.
