### ISSUE TITLE
Map form input does not work with multi-instance templates

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#241]
Reported by @jqnatividad on 19 Sep 2014 at https://github.com/SemanticMediaWiki/SemanticMaps/issues/25
## 

With MW 1.23.1, SMW 1.9.2, SF 2.8, SM 3.0.4 and Maps 3.1, input type=map doesn't work, but works fine outside a multi-instance template.
![define_knowledge_product__test_entry_55-5_-_knowledge_commons](https://cloud.githubusercontent.com/assets/1980690/4329822/03ac9710-3fa1-11e4-894a-9849165e16cc.jpg)

**Comment by JeroenDeDauw** [comment]
Feature moved to Page Forms extension

**Comment by kghbln** [comment]
I cannot tell if this works in the meantime. Thus pinging @yaronkoren to make him aware of this.
