### ISSUE TITLE
Add support for fusiontables styles

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#243]
Reported by @grobot at https://github.com/SemanticMediaWiki/SemanticMaps/issues/32
## 

I have made the following FusionTable. https://www.google.com/fusiontables/data?docid=12gBHmge2WpO72D4Eo1gsVNNmuImhOFS1e2ebBuOY#map:id=3. It has polygons, and custom fill parameters all made through the google UI.

To save you from clicking on a link it looks like:
![screen shot 2014-11-26 at 11 58 00 am](https://cloud.githubusercontent.com/assets/361387/5207881/87473ba0-7563-11e4-9765-61ac449053e2.png)

I then used the Maps extension to embed it on a page

```
{{#display_map:|zoom=4|center=Iowa|fusiontables=12gBHmge2WpO72D4Eo1gsVNNmuImhOFS1e2ebBuOY}}
```

and it looks like
![screen shot 2014-11-26 at 11 56 02 am](https://cloud.githubusercontent.com/assets/361387/5207861/51d3210a-7563-11e4-85db-bc93472b6283.png)

So it seems to me that the styles from the fusion table aren't being picked up by the extension. Though, honestly, this is just a guess. Any help would be appreciated.

**Comment by akuckartz** [comment]
> Google Fusion Tables and the Fusion Tables API have been discontinued.... You’ll be able to download your table data via Google Takeout until March 3, 2020. After that, all Fusion Tables data will be permanently and irrevocably deleted.

https://support.google.com/fusiontables
