### ISSUE TITLE
Configuration parameters are not documened

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#247]
Basically [only a few](https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#configuration) of the [configuration parameters](https://github.com/JeroenDeDauw/Maps/blob/master/Maps_Settings.php) are not documented (Maps and former Semantic Maps as well). The docu should go into [README](https://github.com/JeroenDeDauw/Maps/blob/master/README.md) or into [INSTALL](https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#configuration) and/or to the wiki.

Example for an [undocumented parameter](https://github.com/SemanticMediaWiki/SemanticMaps/issues/45)

**Comment by kghbln** [comment]
Assigned self however other are most welcome to contribute, too.

**Comment by JeroenDeDauw** [comment]
> into README or into INSTALL

No in the README, and the INSTALL is already getting rather cluttered. How about having a dedicated file/"page" for it?

**Comment by kghbln** [comment]
> How about having a dedicated file/"page" for it?

No objections at all. Let's do it like this!

**Comment by JeroenDeDauw** [comment]
The docs now mention relevant settings in a bunch of places (example: https://www.semantic-mediawiki.org/wiki/Maps/Geocode). There is still no overview of all settings, though the INSTALL docs mention you can look in the settings file for that. So the settings are now at least no longer documented worse than most other stuff :)
