### ISSUE TITLE
Using template parameter in queries breaks the maps

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#248]
Reported by @kghbln in https://github.com/SemanticMediaWiki/SemanticMaps/issues/56
## 

I just see yellow snow when trying to display a google maps v3 map. Some API-change at Google which requires this extension to be adapted?

Instead of a Map one gets the message "Your browser is not compatible with Google Maps v3".

[Directly added maps](https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_basic_map) are cool. As soon as [SM is used](https://www.semantic-mediawiki.org/wiki/Semantic_Maps_examples/Using_templates_%28queries%29) I just see this error message (all browsers).

**Comment by JeroenDeDauw** [comment]
Issue is still present with SM 3.4.1

**Comment by Karlpietsch** [comment]
ext.maps.googlemaps3.js

`(function ($, mw) {

    window.initializeGM3 = function() {

        console.log('maps-API has been loaded, ready to use');
        $('.maps-googlemaps3').each(function () {
            var $this = $(this);
            $this.googlemaps($.parseJSON($this.find('div').attr('data-mapdata')));
        });
    }

    function loadScript(src, callback) {

        var script = document.createElement("script");
        script.type = "text/javascript";
        if (callback) script.onload = callback;
        document.getElementsByTagName("head")[0].appendChild(script);
        script.src = src;
    }
    

	$( document ).ready( function() {

	    if (typeof google === 'undefined') {
	        //$( '.maps-googlemaps3' ).text( mw.msg( 'maps-googlemaps3-incompatbrowser' ) );
	        loadScript('https://maps.googleapis.com/maps/api/js?v=3&sensor=false&callback=initializeGM3',
                    function () { console.log('google-loader has been loaded, but not the maps-API '); });

			
		}
		else {
		    $('.maps-googlemaps3').each(function () {
		        var $this = $(this);
		        $this.googlemaps($.parseJSON($this.find('div').attr('data-mapdata')));
		    });
		}

	} );

})( window.jQuery, mediaWiki );`

**Comment by kghbln** [comment]
Still present with MediaWiki 	1.27.1 (8c593e7) 22:49, 26 October 2016, PHP 7.0.8-0ubuntu0.16.04.3 (apache2handler), MySQL 	5.7.16-0ubuntu0.16.04.1 and Maps	4.0.3 (e4f4b9a) 14:18, 6 December 2016

**Comment by waandershz** [comment]
When viewing (Windows 7 + Chrome 55.0 / Firefox 50.1.0) this page: https://www.semantic-mediawiki.org/wiki/Semantic_Maps_examples/Using_templates_(queries) I get the same error.

Also with our own wiki (MW 1.27.1, Semantic Maps 3.3 and Maps 3.8.0). Okay when omitting the template-param.

**Comment by JeroenDeDauw** [comment]
It is not fixed yet. I agree it's a high priority thing, since the template parameter is indeed a very useful feature.

**Comment by JeroenDeDauw** [comment]
This appears to be a Google Maps issue. Works fine with OpenLayers: https://www.semantic-mediawiki.org/wiki/Semantic_Maps_examples/Using_templates_(queries)

**Comment by JeroenDeDauw** [comment]
It's not fully broken. If there is just one map with the template parameter it works, even with Google Maps:

![notfullybroke](https://cloud.githubusercontent.com/assets/146040/26184096/19703896-3b83-11e7-887c-7e67610fdba7.png)

**Comment by JeroenDeDauw** [comment]
Having one map with template and several other without on a page works fine. And as soon as a second one with template param is added, they all stop working.

**Comment by JeroenDeDauw** [comment]
With https://github.com/JeroenDeDauw/Maps/pull/332 things are ... somewhat less broken

**Comment by JeroenDeDauw** [comment]
If you where seeing this somewhere else than on the SMW wiki itself, could you try out the latest dev version and see if it fixes the issue?

**Comment by kghbln** [comment]
I have recreated the examples on sandbox.semantic-mediawiki.org:

- [googlemaps](https://sandbox.semantic-mediawiki.org/wiki/Maps_using_templates_-_googlemaps)
- [openlayers](https://sandbox.semantic-mediawiki.org/wiki/Maps_using_templates_-_openlayers)
- [leaflet](https://sandbox.semantic-mediawiki.org/wiki/Maps_using_templates_-_leaflet)

> And as soon as a second one with template param is added, they all stop working.

Affirmative. The second one is still breaking.

**Comment by JeroenDeDauw** [comment]
Thanks so much for verifying. Tracking the other issue at https://github.com/JeroenDeDauw/Maps/issues/334 now

**Comment by kghbln** [comment]
> Thanks so much for verifying. 

Well, I have to thank you for tackling. Maps 4.2.1?

**Comment by stefahn** [comment]
This seems to be an issue still, at least in certain cases.
When using two openlayers maps on the same page (and templates), the second query doesn't show as a map but as a table. 

See this revision of the example page: https://www.semantic-mediawiki.org/w/index.php?title=Semantic_Maps_examples/Using_templates_(queries)&oldid=60896

**Comment by JeroenDeDauw** [comment]
Please create a new issue and create a working example on https://sandbox.semantic-mediawiki.org/

Also note that openlayers (format=openlayers) is no longer supported by Maps. On the linked page the maps are using Leaflet.

**Comment by stefahn** [comment]
Hi Jeroen,

with Leaflet and GoogleMaps it works just fine. See https://sandbox.semantic-mediawiki.org/wiki/Maps_using_templates_-_leaflet for Leaflet examples.

I found out that the second map is not loaded, if one uses Openlayers on both maps. Since this service is no longer provided I think there's no need to create a new issue.
