### ISSUE TITLE
Make `$egGoogleJsApiKey` an alias setting to `$egMapsGMaps3ApiKey`

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#250]
This will probably make it easier for upgraders from Maps 2.x since they will not have to change this setting. This is related to https://github.com/JeroenDeDauw/Maps/issues/179 which was released with Maps 3.8 I got this idea from this [thread](https://www.mediawiki.org/wiki/Topic:Tb9wyrsmyuxnnob4). Perhaps it is not too complicated to implement this. @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
Ah, good idea

**Comment by kghbln** [comment]
Probably, but in the meantime we also have an API version configuration parameter so to keep the naming consistent ...
