### ISSUE TITLE
Rendering for the `#smwdoc` table broken for geo related formats

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#258]
**Setup**
- MediaWiki     1.25.6 (01b4001) 21:49, 20 May 2016
- PHP   5.6.11-1ubuntu3.4 (apache2handler)
- Maps  3.8.2 (a5a1d77) 05:18, 22 September 2016
- Semantic Maps 3.4.1 (0763cfa) 01:47, 21 September 2016

**Examples**
- [map format](https://www.semantic-mediawiki.org/wiki/Help:Map_format)
- [openlayers format](https://www.semantic-mediawiki.org/wiki/Help:OpenLayers_format)
- [googlemaps format](https://www.semantic-mediawiki.org/wiki/Help:Google_Maps_format)

Interestingly enough [klm](https://www.semantic-mediawiki.org/wiki/Help:KML_format) is working though I think this is more of an export format. So this one is unaffected as all the other formats provided by SMW and SRF.

**Comment by JeroenDeDauw** [comment]
Ah right, this was mentioned to me at SMWCon and then I forgot about it :)

Issue also present with Maps 4.0 alpha: http://sandbox.semantic-mediawiki.org/wiki/Smwdoc_-_googlemaps

**Comment by JeroenDeDauw** [comment]
I have a hunch this has something to do with the map format parameters having aliases and the others not having them. Or are there SMW formats with parameter aliases that do not experience this issue?

**Comment by JeroenDeDauw** [comment]
Relevant code:

* https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ParameterListDocBuilder.php
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/ParserFunctions/DocumentationParserFunction.php

**Comment by kghbln** [comment]
Still an issue for Maps 4.x I guess it will be nice to get this fluffed somehow. This is the main entry point for the docu.

**Comment by kghbln** [comment]
Cool, this is [great again](https://sandbox.semantic-mediawiki.org/wiki/Smwdoc_-_googlemaps)!
