### ISSUE TITLE
#display_map kml support broken for Google Maps

### ISSUE THREAD

**Issue by Flexmaen** [JeroenDeDauw/Maps#259]
With the update of the map plugin i suddenly get the error: `<maps-kml-parsing-failed>` when trying to display a KML file on the map which worked before.

Here is an example KML:
http://www.grazwiki.at/images/b/b0/Rundgang_Herz-Jesu.kml

**Comment by kghbln** [comment]
What are the versions of PHP, MW and Maps?

Apart from that: Using kml is an [undocumented feature](https://www.semantic-mediawiki.org/w/index.php?title=Maps_examples/Google_Maps_KML&action=edit&redlink=1). Just recently added the docu for [Semantic Maps](https://www.semantic-mediawiki.org/wiki/Semantic_Maps_examples/Adding_data_from_a_KML_file). Have not used this so I cannot even tell which syntax should work somehow. :(

**Comment by JeroenDeDauw** [comment]
http://www.grazwiki.at/Spezial:Version

> Maps	3.8.2
> Semantic Maps	3.4.0-alpha (392d931) 11:36, 18 July 2016

Is that the version for which it fails? With what version did it work before? What is the wikitext that causes this?

**Comment by Flexmaen** [comment]
I think it was 3.4 or 3.5 where it still worked.

The command is:
{{#display_map:{{{place|}}}|kml={{{kml file|}}}|kmlrezoom=yes}}
So, there were some options like kml= and kmlrezoom=

**Comment by kghbln** [comment]
> Is that the version for which it fails?

Ah, I was so distracted by the fact that there is no docu ... I guess it is me how will have to add it.

**Comment by samwilson** [comment]
The `kml=` option works in Maps 4.0.5, but it requires a full URL (rather than a wiki filename).

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/JeroenDeDauw/Maps/commit/f3ff4f7e3ed5f1174bdef6132a9d21f86dc366e4
