### ISSUE TITLE
Semantic Forms input broken again

### ISSUE THREAD

**Issue by Flexmaen** [JeroenDeDauw/Maps#262]
We are using Semantic Forms like:

```
{{{field
|Coordinates
|input type=googlemaps
|width=100%
|height=400
|zoom=17
|type=satellite
|autozoom=on
|default={{PAGENAME}}
|property=Koordinaten
|mandatory
}}}
```

Maps should load the coordingates of the pagename (which usually is an address in this case).

Both, the input in genereal and also loading of the pagename seem to be broken again with the latest version of maps.

**Comment by JeroenDeDauw** [comment]
Which version of Maps? Can you link to an example of how this is broken on a public wiki? If not, can you describe in more detail what is broken?

**Comment by JeroenDeDauw** [comment]
Well the input is no longer in this extension...
