### ISSUE TITLE
Maps 4.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#268]
Remaining tasks: https://github.com/JeroenDeDauw/Maps/milestone/1

**Comment by JeroenDeDauw** [comment]
@kghbln any reason sandbox wiki is still running Maps stable?

@PeterTheOne any plans for working on Maps? For instance finishing up https://github.com/SemanticMediaWiki/SemanticMaps/pull/107? I'd like to release 4.0 soon. And if you create some new stuff, that will reassure me more that things are working, as you'd probably notice if they where not :)

**Comment by kghbln** [comment]
@JeroenDeDauw I pinged you about this: https://github.com/SemanticMediaWiki/SemanticNotifications/issues/17#issuecomment-252553179 ;) The issue is that Maps master causes Semantic MediaWiki to be reverted back from master to 2.4.1 stable. So I pulled Maps and now it gets installed as a dependency of Whats Nearby as 3.8.2 stable. Basically the dependencies for Maps need to be rearranged it a way that allows both extensions to be run with master.

**Comment by JeroenDeDauw** [comment]
Ok... I found what the issue is and removed it. Not sure why it's an issue though. Might be a Composer bug. Or me being confoosed about how this particular thing is supposed to work. https://github.com/JeroenDeDauw/Maps/pull/272

**Comment by Flexmaen** [comment]
Would be fine if the Semantic Forms input and also the KML works here.
We had the problem that after every update something that already worked was broken, mostly the Forms input.

**Comment by JeroenDeDauw** [comment]
The form input got removed in this release of Maps in favour of the one that comes bundled with Semantic Forms itself. See https://github.com/JeroenDeDauw/Maps/pull/266

**Comment by PeterTheOne** [comment]
> @PeterTheOne any plans for working on Maps?

@JeroenDeDauw I was somewhat inactive in the last weeks, I don't expect to be super active in the near future but I want to get some stuff done on the coming weekends.

**Comment by JeroenDeDauw** [comment]
I've just updated the [release notes](https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md) and am fine with releasing the extension without further work being done on it. Going to do a RC release first though, and not today.

In other news: I now once again have a MediaWiki development install (using Vagrant), so can actually see if the extension is totally broken or not :)

**Comment by kghbln** [comment]
> Going to do a RC release first though, and not today.

Means that I have to do urgent docu fluff on the wiki.

> In other news: I now once again have a MediaWiki development install (using Vagrant), so can actually see if the extension is totally broken or not :)

Cool! I am fluffy now. :D

**Comment by JeroenDeDauw** [comment]
> Cool! I am fluffy now. :D

You are always fluff, even when grump :)

**Comment by JeroenDeDauw** [comment]
`4.0.0-RC1` tag created, and you can haz blog post: https://www.entropywins.wtf/blog/2016/11/09/maps-4-0-0-rc1-released/

**Comment by kghbln** [comment]
Wiki page updates:
- [smw.o: Maps](https://www.semantic-mediawiki.org/w/index.php?title=Extension%3AMaps&type=revision&diff=47503&oldid=47178)
- [smw.o: Semantic Maps](https://www.semantic-mediawiki.org/w/index.php?title=Extension%3ASemantic_Maps&type=revision&diff=47504&oldid=46771)
as well as on mw.o
