### ISSUE TITLE
Unexpected behaviour of #display_map:

### ISSUE THREAD

**Issue by heinrich-k** [JeroenDeDauw/Maps#275]
Hello.
I currently run Semantic Map 3.1.3 and Maps 3.2 - MediaWiki 1.24.0 - PHP 5.3.10-1ubuntu3.25 (cgi-fcgi)

My code is
`{{#display_map: |lines={{semantic template query}} |centre=46.5,-34.5 |maxzoom=11 |minzoom=2 |zoom=3 |geoservice=geonames |width=auto |height=750px |type=earth |types=hybrid,earth,physical,satellite }}`

The semantic query seem to generate output that is suitable for the lines= parameter. However, it appears as if there was some additional output that I can't see, but `#display_map:` tries to interpret, resulting in additional lines on the map.

How would I fix that ?

Best regards,
Heinrich

ps.:
I attached a screenshot. The red line shouldn't be there at all. The dark blue lines marked with red arrows should actually be only one short line from NYC to DC, but only the NYC point is correctly drawn.
![snip_20161024194114](https://cloud.githubusercontent.com/assets/11177446/19656858/fc94faa2-9a21-11e6-994f-7104108e6137.png)

**Comment by JeroenDeDauw** [comment]
It is difficult to say much about this without knowing the output of `{{semantic template query}}`.

**Comment by heinrich-k** [comment]
Well, it is supposed to generate the lines, basically it is an #ask: which fuels a template

`<noinclude>Diese Vorlage soll die [[Mondbrücken]] aus der Defnition abrufen und als Vorlage formatiert in der Kartenanzeige widergeben.{{br}}</noinclude>{{#ask:[[Endpunkt 1::+]]
|?Endpunkt 1=Endpunkt1
|?Endpunkt 2=Endpunkt2
|?Bekanntheit
|?Hinweise
|?Caern 1
|?Caern 2
|sort=Endpunkt 1,Endpunkt 2
|format=template
|link=none
|headers=hide
|mainlabel=-
|sep=;
|template=Mondbrücken-Kartenausgabe
|limit=
|offset=0
}}
`

And the template "Mondbrücken-Kartenausgabe" goes like this
`<includeonly>
{{#show: {{{1|}}} |?Koordinaten#}}:{{#show: {{{2|}}} |?Koordinaten#}}~ ~{{{3|}}}{{br}}{{#if:{{{4|}}}|{{{4|}}}{{br}}}}{{ifexist|{{{1|}}}|{{#show: {{{1|}}} |?Septenname}}{{#if:{{{5|}}}| ->„{{{5|}}}”}}}}{{br}}{{ifexist|{{{2|}}}|{{#show:{{{2|}}} |?Septenname}}{{#if:{{{6|}}}| ->„{{{6|}}}” }}}}~{{#if: {{{4|}}} | #FFFFFF | {{#switch: {{{3|}}}
|bekannt=#0000FF
|wenig bekannt=#7777FF
|quasi unbekannt=#BBBBFF
|#default=#FF0000
}} }};</includeonly><noinclude>[[category:Einbettung]]Diese Vorlage soll semantische Suchergebnisse für [[Mondbrücke]]n erhalten und sie für den Kartendienst lesbar ausgeben.</noinclude>`

with template ifexist basically being #ifexist: and template br basically bein <br />

**Comment by JeroenDeDauw** [comment]
I'd like to know the *output* of the query.

**Comment by heinrich-k** [comment]
Oh, okay....

`38° 51' 24", -77° 1' 36":40° 46' 58", -73° 58' 2"~ ~bekannt
Sept of the Awakening
Septe im Grünen~

    0000FF;

38° 51' 24", -77° 1' 36":41° 47' 13", -87° 35' 45"~ ~bekannt
Sept of the Awakening
Wind Catchers Sept~

    0000FF;

42° 8' 32", 41° 47' 5":33° 35' 21", -7° 37' 0"~ ~wenig bekannt
nur einmal wöchentlich
Sept of the Blood Sea
Rad von Ptah~

    FFFFFF;

46° 15' 13", -117° 43' 24":35° 52' 46", -110° 32' 18"~ ~quasi unbekannt
Caldron Rock Sept
Sept of the Painted Sands~

    BBBBFF;

46° 15' 13", -117° 43' 24":43° 17' 12", -104° 6' 55"~ ~wenig bekannt
Caldron Rock Sept
Pure Heart Sept~

    7777FF;

46° 15' 13", -117° 43' 24":37° 53' 43", -122° 36' 47"~ ~quasi unbekannt
Caldron Rock Sept
Septe des westlichen Auges~

    BBBBFF;

41° 54' 37", 12° 23' 45":33° 35' 21", -7° 37' 0"~ ~wenig bekannt
nur einmal wöchentlich
Caput Mundi->„Porta di Mare”
Rad von Ptah~

    FFFFFF;

46° 18' 40", 6° 2' 39":51° 29' 46", -0° 20' 48"~ ~wenig bekannt
Le Salon Vert / Der grüne Salon
Septe der ewigen Stadt~

    7777FF;

47° 23' 43", 13° 56' 12":51° 28' 56", 23° 51' 23"~ ~wenig bekannt
Septe des endlosen Sturms
Septe des Lodernden Flusses~

    7777FF;

51° 29' 46", -0° 20' 48":50° 7' 16", 8° 33' 58"~ ~wenig bekannt
Septe der ewigen Stadt
Septe der steinernen Bäume~

    7777FF;

51° 29' 46", -0° 20' 48":42° 18' 48", -71° 7' 37"~ ~bekannt
Septe der ewigen Stadt
(Sept of) Thirteen Stars~

    0000FF;

49° 48' 55", 5° 51' 11":38° 19' 38", 26° 0' 23"~ ~bekannt
Septe Felsenhof
Septe der neun Federn~

    0000FF;

59° 46' 29", 56° 55' 36":33° 35' 21", -7° 37' 0"~ ~wenig bekannt
wöchentlich, mittwochs
Sept of the Firebird
Rad von Ptah~

    FFFFFF;

59° 46' 29", 56° 55' 36":28° 0' 56", 85° 55' 32"~ ~quasi unbekannt
Sept of the Firebird
Sept of the Snow Leopard~

    BBBBFF;

50° 23' 51", -122° 40' 0":61° 45' 16", -145° 44' 30"~ ~bekannt
Sept of the First Rage
Sept of the Weeping Daughter~

    0000FF;

50° 23' 51", -122° 40' 0":66° 1' 55", 142° 3' 32"~ ~wenig bekannt
Sept of the First Rage
Septe des Winterwalds~

    7777FF;

42° 37' 43", -77° 3' 30":40° 46' 58", -73° 58' 2"~ ~wenig bekannt
Sept of the Hand of Gaia
Septe im Grünen~

    7777FF;

47° 38' 59", 11° 55' 56":51° 47' 56", 10° 36' 26"~ ~bekannt
Septe der hohen Quellen
Septe des stürmischen Felsens~

    0000FF;

-0° 53' 37", -64° 20' 33":40° 46' 58", -73° 58' 2"~ ~bekannt
North Ward
Septe im Grünen~

    0000FF;

-0° 53' 37", -64° 20' 33":33° 35' 21", -7° 37' 0"~ ~wenig bekannt
wöchentlich, donnerstags
North Ward
Rad von Ptah~

    FFFFFF;

-0° 53' 37", -64° 20' 33":37° 53' 43", -122° 36' 47"~ ~bekannt
North Ward
Septe des westlichen Auges~

    0000FF;

-0° 53' 37", -64° 20' 33":41° 47' 13", -87° 35' 45"~ ~bekannt
North Ward
Wind Catchers Sept~

    0000FF;

34° 5' 58", 135° 0' 55":22° 18' 39", 114° 6' 34"~ ~wenig bekannt
Sept of the Ichijo Modoribashi
Konzil des universellen Handels~

    7777FF;

34° 5' 58", 135° 0' 55":28° 0' 56", 85° 55' 32"~ ~wenig bekannt
Sept of the Ichijo Modoribashi
Sept of the Snow Leopard~

    7777FF;

34° 5' 58", 135° 0' 55":37° 53' 43", -122° 36' 47"~ ~quasi unbekannt
Sept of the Ichijo Modoribashi
Septe des westlichen Auges~

    BBBBFF;

40° 46' 58", -73° 58' 2":35° 52' 46", -110° 32' 18"~ ~quasi unbekannt
Septe im Grünen
Sept of the Painted Sands~

    BBBBFF;

40° 46' 58", -73° 58' 2":33° 35' 21", -7° 37' 0"~ ~bekannt
wöchentlich, dienstags
Septe im Grünen
Rad von Ptah~

    FFFFFF;

40° 46' 58", -73° 58' 2":41° 47' 13", -87° 35' 45"~ ~wenig bekannt
Septe im Grünen
Wind Catchers Sept~

    7777FF;

40° 46' 58", -73° 58' 2":55° 59' 22", -105° 26' 8"~ ~wenig bekannt
Septe im Grünen
Sept of the Winter Wolf~

    7777FF;

22° 18' 39", 114° 6' 34":33° 35' 21", -7° 37' 0"~ ~wenig bekannt
wöchentlich
Konzil des universellen Handels
Rad von Ptah~

    FFFFFF;

22° 18' 39", 114° 6' 34":28° 0' 56", 85° 55' 32"~ ~wenig bekannt
Konzil des universellen Handels
Sept of the Snow Leopard~

    7777FF;

29° 33' 33", -92° 0' 36":43° 4' 47", -79° 4' 11"~ ~wenig bekannt
Táłłàapi homma Niłahasi
Sept of the White Water~

    7777FF;

67° 39' 45", 15° 2' 42":65° 38' 58", -22° 42' 50"~ ~wenig bekannt
Septe des nebligen Moores
Norðvestur Fólk~

    7777FF;

65° 38' 58", -22° 42' 50":52° 38' 21", -56° 10' 58"~ ~wenig bekannt
Norðvestur Fólk
Septe des Südlands~

    7777FF;

35° 52' 46", -110° 32' 18":61° 45' 16", -145° 44' 30"~ ~quasi unbekannt
Sept of the Painted Sands
Sept of the Weeping Daughter~

    BBBBFF;

35° 52' 46", -110° 32' 18":37° 53' 43", -122° 36' 47"~ ~wenig bekannt
Sept of the Painted Sands
Septe des westlichen Auges~

    7777FF;

35° 52' 46", -110° 32' 18":41° 47' 13", -87° 35' 45"~ ~quasi unbekannt
Sept of the Painted Sands
Wind Catchers Sept~

    BBBBFF;

35° 52' 46", -110° 32' 18":55° 59' 22", -105° 26' 8"~ ~wenig bekannt
Sept of the Painted Sands
Sept of the Winter Wolf~

    7777FF;

33° 35' 21", -7° 37' 0":28° 0' 56", 85° 55' 32"~ ~wenig bekannt
wöchentlich
Rad von Ptah
Sept of the Snow Leopard~

    FFFFFF;

33° 35' 21", -7° 37' 0":44° 52' 11", -94° 9' 26"~ ~wenig bekannt
wöchentlich, sonntags
Rad von Ptah
Seat of House Unbreakable Hearth~

    FFFFFF;

33° 35' 21", -7° 37' 0":53° 13' 43", -6° 9' 10"~ ~wenig bekannt
wöchentlich, montags
Rad von Ptah
Taming The Tiger~

    FFFFFF;

49° 35' 25", 9° 0' 18":38° 31' 29", 25° 25' 46"~ ~wenig bekannt
Septe der tosenden Wasser
Septe der Vergangenen Visionen~

    7777FF;

61° 45' 16", -145° 44' 30":55° 59' 22", -105° 26' 8"~ ~wenig bekannt
Sept of the Weeping Daughter
Sept of the Winter Wolf~

    7777FF;

37° 53' 43", -122° 36' 47":41° 47' 13", -87° 35' 45"~ ~bekannt
Septe des westlichen Auges
Wind Catchers Sept~

    0000FF;`

This of cource is the output when rendered completely. The # turned into List-Items (lost in copy and paste) and so on.
Is there a way to stop the parsing and show only the result of the query, before it is converted into HTML ?

**Comment by Nikerabbit** [comment]
You could try placing the query on Special:ExpandTemplates and copy from there. You can also wrap the output inside ```s to avoid GitHub trying to parse it.

**Comment by heinrich-k** [comment]
`[[SMW::off]]
38° 51' 24", -77° 1' 36":40° 46' 58", -73° 58' 2"~ ~bekannt<br />[[Awakening|Sept of the Awakening]]<br />[[Im Grünen|Septe im Grünen]]~
#0000FF;
38° 51' 24", -77° 1' 36":41° 47' 13", -87° 35' 45"~ ~bekannt<br />[[Awakening|Sept of the Awakening]]<br />[[Wind Catchers|Wind Catchers Sept]]~
#0000FF;
42° 8' 32", 41° 47' 5":33° 35' 21", -7° 37' 0"~ ~wenig bekannt<br />nur einmal wöchentlich<br />[[Blutsee|Sept of the Blood Sea]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
46° 15' 13", -117° 43' 24":35° 52' 46", -110° 32' 18"~ ~quasi unbekannt<br />[[Caldron Rock|Caldron Rock Sept]]<br />[[Painted Sands|Sept of the Painted Sands]]~
#BBBBFF;
46° 15' 13", -117° 43' 24":43° 17' 12", -104° 6' 55"~ ~wenig bekannt<br />[[Caldron Rock|Caldron Rock Sept]]<br />[[Pure Heart|Pure Heart Sept]]~
#7777FF;
46° 15' 13", -117° 43' 24":37° 53' 43", -122° 36' 47"~ ~quasi unbekannt<br />[[Caldron Rock|Caldron Rock Sept]]<br />[[Westliches Auge|Septe des westlichen Auges]]~
#BBBBFF;
41° 54' 37", 12° 23' 45":33° 35' 21", -7° 37' 0"~ ~wenig bekannt<br />nur einmal wöchentlich<br />[[Caput Mundi|Caput Mundi->„Porta di Mare”]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
46° 18' 40", 6° 2' 39":51° 29' 46", -0° 20' 48"~ ~wenig bekannt<br />[[Der grüne Salon|Le Salon Vert / Der grüne Salon]]<br />[[Ewige Stadt|Septe der ewigen Stadt]]~
#7777FF;
47° 23' 43", 13° 56' 12":51° 28' 56", 23° 51' 23"~ ~wenig bekannt<br />[[Endloser Sturm|Septe des endlosen Sturms]]<br />[[Lodernder Fluss|Septe des Lodernden Flusses]]~
#7777FF;
51° 29' 46", -0° 20' 48":50° 7' 16", 8° 33' 58"~ ~wenig bekannt<br />[[Ewige Stadt|Septe der ewigen Stadt]]<br />[[Steinerne Bäume|Septe der steinernen Bäume]]~
#7777FF;
51° 29' 46", -0° 20' 48":42° 18' 48", -71° 7' 37"~ ~bekannt<br />[[Ewige Stadt|Septe der ewigen Stadt]]<br />[[Thirteen Stars|(Sept of) Thirteen Stars]]~
#0000FF;
49° 48' 55", 5° 51' 11":38° 19' 38", 26° 0' 23"~ ~bekannt<br />[[Felsenhof|Septe Felsenhof]]<br />[[Neun Federn|Septe der neun Federn]]~
#0000FF;
59° 46' 29", 56° 55' 36":33° 35' 21", -7° 37' 0"~ ~wenig bekannt<br />wöchentlich, mittwochs<br />[[Feuervogel|Sept of the Firebird]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
59° 46' 29", 56° 55' 36":28° 0' 56", 85° 55' 32"~ ~quasi unbekannt<br />[[Feuervogel|Sept of the Firebird]]<br />[[Schneeleopard|Sept of the Snow Leopard]]~
#BBBBFF;
50° 23' 51", -122° 40' 0":61° 45' 16", -145° 44' 30"~ ~bekannt<br />[[First Rage|Sept of the First Rage]]<br />[[Weeping Daughter|Sept of the Weeping Daughter]]~
#0000FF;
50° 23' 51", -122° 40' 0":66° 1' 55", 142° 3' 32"~ ~wenig bekannt<br />[[First Rage|Sept of the First Rage]]<br />[[Winterwald|Septe des Winterwalds]]~
#7777FF;
42° 37' 43", -77° 3' 30":40° 46' 58", -73° 58' 2"~ ~wenig bekannt<br />[[Hand of Gaia|Sept of the Hand of Gaia]]<br />[[Im Grünen|Septe im Grünen]]~
#7777FF;
47° 38' 59", 11° 55' 56":51° 47' 56", 10° 36' 26"~ ~bekannt<br />[[Hohe Quellen|Septe der hohen Quellen]]<br />[[Stürmischer Felsen|Septe des stürmischen Felsens]]~
#0000FF;
-0° 53' 37", -64° 20' 33":40° 46' 58", -73° 58' 2"~ ~bekannt<br />[[Hollow Earth Caern|North Ward]]<br />[[Im Grünen|Septe im Grünen]]~
#0000FF;
-0° 53' 37", -64° 20' 33":33° 35' 21", -7° 37' 0"~ ~wenig bekannt<br />wöchentlich, donnerstags<br />[[Hollow Earth Caern|North Ward]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
-0° 53' 37", -64° 20' 33":37° 53' 43", -122° 36' 47"~ ~bekannt<br />[[Hollow Earth Caern|North Ward]]<br />[[Westliches Auge|Septe des westlichen Auges]]~
#0000FF;
-0° 53' 37", -64° 20' 33":41° 47' 13", -87° 35' 45"~ ~bekannt<br />[[Hollow Earth Caern|North Ward]]<br />[[Wind Catchers|Wind Catchers Sept]]~
#0000FF;
34° 5' 58", 135° 0' 55":22° 18' 39", 114° 6' 34"~ ~wenig bekannt<br />[[Ichijo Modoribashi|Sept of the Ichijo Modoribashi]]<br />[[Konzil des universellen Handels|Konzil des universellen Handels]]~
#7777FF;
34° 5' 58", 135° 0' 55":28° 0' 56", 85° 55' 32"~ ~wenig bekannt<br />[[Ichijo Modoribashi|Sept of the Ichijo Modoribashi]]<br />[[Schneeleopard|Sept of the Snow Leopard]]~
#7777FF;
34° 5' 58", 135° 0' 55":37° 53' 43", -122° 36' 47"~ ~quasi unbekannt<br />[[Ichijo Modoribashi|Sept of the Ichijo Modoribashi]]<br />[[Westliches Auge|Septe des westlichen Auges]]~
#BBBBFF;
40° 46' 58", -73° 58' 2":35° 52' 46", -110° 32' 18"~ ~quasi unbekannt<br />[[Im Grünen|Septe im Grünen]]<br />[[Painted Sands|Sept of the Painted Sands]]~
#BBBBFF;
40° 46' 58", -73° 58' 2":33° 35' 21", -7° 37' 0"~ ~bekannt<br />wöchentlich, dienstags<br />[[Im Grünen|Septe im Grünen]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
40° 46' 58", -73° 58' 2":41° 47' 13", -87° 35' 45"~ ~wenig bekannt<br />[[Im Grünen|Septe im Grünen]]<br />[[Wind Catchers|Wind Catchers Sept]]~
#7777FF;
40° 46' 58", -73° 58' 2":55° 59' 22", -105° 26' 8"~ ~wenig bekannt<br />[[Im Grünen|Septe im Grünen]]<br />[[Winter Wolf|Sept of the Winter Wolf]]~
#7777FF;
22° 18' 39", 114° 6' 34":33° 35' 21", -7° 37' 0"~ ~wenig bekannt<br />wöchentlich<br />[[Konzil des universellen Handels|Konzil des universellen Handels]]<br />[[Rad von Ptah|Rad von Ptah]]~
#FFFFFF;
22° 18' 39", 114° 6' 34":28° 0' 56", 85° 55' 32"~ ~wenig bekannt<br />[[Konzil des universellen Handels|Konzil des universellen Handels]]<br />[[Schneeleopard|Sept of the Snow Leopard]]~
#7777FF;
29° 33' 33", -92° 0' 36":43° 4' 47", -79° 4' 11"~ ~wenig bekannt<br />[[Marsh Island|Táłłàapi homma Niłahasi]]<br />[[White Water|Sept of the White Water]]~
#7777FF;
67° 39' 45", 15° 2' 42":65° 38' 58", -22° 42' 50"~ ~wenig bekannt<br />[[Nebliges Moor|Septe des nebligen Moores]]<br />[[Norðvestur|Norðvestur Fólk]]~
#7777FF;
65° 38' 58", -22° 42' 50":52° 38' 21", -56° 10' 58"~ ~wenig bekannt<br />[[Norðvestur|Norðvestur Fólk]]<br />[[Südland|Septe des Südlands]]~
#7777FF;
35° 52' 46", -110° 32' 18":61° 45' 16", -145° 44' 30"~ ~quasi unbekannt<br />[[Painted Sands|Sept of the Painted Sands]]<br />[[Weeping Daughter|Sept of the Weeping Daughter]]~
#BBBBFF;
35° 52' 46", -110° 32' 18":37° 53' 43", -122° 36' 47"~ ~wenig bekannt<br />[[Painted Sands|Sept of the Painted Sands]]<br />[[Westliches Auge|Septe des westlichen Auges]]~
#7777FF;
35° 52' 46", -110° 32' 18":41° 47' 13", -87° 35' 45"~ ~quasi unbekannt<br />[[Painted Sands|Sept of the Painted Sands]]<br />[[Wind Catchers|Wind Catchers Sept]]~
#BBBBFF;
35° 52' 46", -110° 32' 18":55° 59' 22", -105° 26' 8"~ ~wenig bekannt<br />[[Painted Sands|Sept of the Painted Sands]]<br />[[Winter Wolf|Sept of the Winter Wolf]]~
#7777FF;
33° 35' 21", -7° 37' 0":28° 0' 56", 85° 55' 32"~ ~wenig bekannt<br />wöchentlich<br />[[Rad von Ptah|Rad von Ptah]]<br />[[Schneeleopard|Sept of the Snow Leopard]]~
#FFFFFF;
33° 35' 21", -7° 37' 0":44° 52' 11", -94° 9' 26"~ ~wenig bekannt<br />wöchentlich, sonntags<br />[[Rad von Ptah|Rad von Ptah]]<br />[[Seat of House Unbreakable Hearth|Seat of House Unbreakable Hearth]]~
#FFFFFF;
33° 35' 21", -7° 37' 0":53° 13' 43", -6° 9' 10"~ ~wenig bekannt<br />wöchentlich, montags<br />[[Rad von Ptah|Rad von Ptah]]<br />[[Taming Tiger|Taming The Tiger]]~
#FFFFFF;
49° 35' 25", 9° 0' 18":38° 31' 29", 25° 25' 46"~ ~wenig bekannt<br />[[Tosende Wasser|Septe der tosenden Wasser]]<br />[[Vergangenen Visionen|Septe der Vergangenen Visionen]]~
#7777FF;
61° 45' 16", -145° 44' 30":55° 59' 22", -105° 26' 8"~ ~wenig bekannt<br />[[Weeping Daughter|Sept of the Weeping Daughter]]<br />[[Winter Wolf|Sept of the Winter Wolf]]~
#7777FF;
37° 53' 43", -122° 36' 47":41° 47' 13", -87° 35' 45"~ ~bekannt<br />[[Westliches Auge|Septe des westlichen Auges]]<br />[[Wind Catchers|Wind Catchers Sept]]~
#0000FF;[[SMW::on]]`

**Comment by heinrich-k** [comment]
![welt](https://cloud.githubusercontent.com/assets/11177446/19768024/ea1d71ac-9c55-11e6-8888-bcff22a5c8c9.png)
So, the map looks like it is supposed to do, when I insert the same text I inserted in the post above - without `[[SMW::off]]` and `[[SMW::on]]`.
The short line between NYC and DC isn't remplaced by two lines anymore and the red line is also gone.

Is there a way to remove these SMW-Tags? Or disable them?

`#replace:` states the argument is to long to find one of them and remove it.

**Comment by kghbln** [comment]
There were other formats provided by SRF [suffering from on and off too](http://wikimedia.7.x6.nabble.com/SMW-off-and-SMW-on-in-result-output-td5068322.html). So this seems related to https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/179

**Comment by heinrich-k** [comment]
I can't really make out any instructions to fix the problem in the links above.

**Comment by kghbln** [comment]
> I can't really make out any instructions to fix the problem in the links above.

This was a FYI. Indeed a programmer is needed to see sense it it. By the way what version of SMW are you running?

**Comment by heinrich-k** [comment]
It's 2.0

**Comment by JeroenDeDauw** [comment]
I don't know why those tags are added or what their exact function is. Ping @mwjames

**Comment by mwjames** [comment]
> It's 2.0

Well, if that relates to the SMW version then I may note that this version is no longer maintained. I may further note that using [0] is a more efficient way to demonstrate an issue.

> I don't know why those tags are added or what their exact function is

Those tags are annotation marker to signal to the `InTextAnnotationParser` that a text has been invoked by a different SMW process \[1] (such as a template from a printer) and is expected to avoid adding annotations [2] as it can theoretically (and practically) call itself (#ask call a template with a #ask that retrieves with an annotation that ... ) and would mostly likely cause a out-of-memory in case of a circular parse loop or annotations that are undesired.

[0] http://sandbox.semantic-mediawiki.org
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/queryprinters/ResultPrinter.php#L309-L321
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L356-L366

**Comment by heinrich-k** [comment]
Is there a flag or option for #ask: to disable that functionality for that specific call?
If not, can I globally disable that and just be careful - it's not like someone else is building queries on my wiki ?

**Comment by mwjames** [comment]
> Is there a flag or option for #ask: to disable that functionality for that specific call?

Without having seen the example (and I mean as live example) and without guarantee but for SMW 2.4+ the parameter `|import-annotation=true` should avoid the markers (as one explicitly requests that "foreign" annotation are to be imported).

**Comment by heinrich-k** [comment]
Unfortunately I can't that easy update to 2.4.

I tried to write a Parserfunction to remove `[[SMW::on]]` and `[[SMW::off]]` myself, but if I get 
`[9384af0a] 2016-11-01 22:43:54: Fatal exception of type MWException`

And that's just from adding the code for a new parserfunction, without using it anywhere...

**Comment by JeroenDeDauw** [comment]
If you go down the route of writing your own code, then perhaps it's easier to modify the maps code to strip out the tags. Such modifications are not ideal, though this one is presumably very small anyway.

**Comment by heinrich-k** [comment]
I'll search the code of Maps for a appropriate place to filter this out. Hope I find a way.

Any idea why writing a basically limitless #replace does lead to an exception ?

**Comment by JeroenDeDauw** [comment]
I'm not up to speed with MW dev but can suggest you look at https://www.mediawiki.org/wiki/Manual:How_to_debug

**Comment by JeroenDeDauw** [comment]
Can this be closed?

**Comment by heinrich-k** [comment]
No idea if the problem remains in newer versions, I couldn't manage to update so far.
I'm still intrested in workaround for my current setup...

**Comment by PeterTheOne** [comment]
@heinrich-k can you create an example in the https://sandbox.semantic-mediawiki.org so that we can see if this works in newer versions? :)

**Comment by JeroenDeDauw** [comment]
Closing as it is not clear this issue exists in supported versions of the software
