### ISSUE TITLE
INSTALL.md needs to be fluffed

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#296]
## Issue

The file recommends to install with `"mediawiki/maps": "*"` added to "composer.local.json" which [leads to issues](https://www.mediawiki.org/wiki/Topic:Tgl1c0uc3csj0ugx) and additionally defeats the versioning this extension does for a purpose. Moreover an occasional revision does not hurt at all, too.

**Comment by JeroenDeDauw** [comment]
huh wtf... requiring "*" should not fail... perhaps this is some behavior specific to the Composer merge plugin? Ping @bd808

**Comment by bd808** [comment]
I don't see anywhere on https://getcomposer.org/doc/articles/versions.md where a bare `*` is listed as a valid version constraint, but composer-merge-plugin doesn't do anything special one way or another for this. It merely updates the data and lets Composer do it's thing.

**Comment by kghbln** [comment]
[All in fluff now, I believe.](https://www.semantic-mediawiki.org/wiki/Maps/Installation)
