### ISSUE TITLE
JavaScript MissingKeyMapError error with GoogleMaps

### ISSUE THREAD

**Issue by nydepot** [JeroenDeDauw/Maps#299]
### Setup

- MW version: 1.27.1
- DB (MySQL etc.): MariaDB 5.5.53-0070
- PHP version: 5.6.28-0049
- Maps version: 4.0.3
- SMW version (if applicable):

### Issue

I updated a couple of days ago and now none of my maps work (using GoogleMaps). The error is a JavaScript error in each maps window and the error console points to this error.

<https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error>

MissingKeyMapError

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

Occurs in all Safari/Chrome/Firefox.

I use the following code in the wiki page to produce a map:

{{#display_map:
42.314928,-77.651518
}}

Generic Maps install setup with GoogleMaps. No custom code.

I've changed it to OpenMaps to at least see a map.

**Comment by JeroenDeDauw** [comment]
Did you set the API key? https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#configuration

Google changes their API so it is now needed.

**Comment by nydepot** [comment]
I just asked the person who did the update. RTFM, or installation notes in this case. He did the key late last night and the maps work now. Sorry for this. And thank you.
