### ISSUE TITLE
Two "Markers" checkboxes in OpenLayer maps

### ISSUE THREAD

**Issue by chrisch-hh** [JeroenDeDauw/Maps#3]
Since the release of 3.0 two "Markers" checkboxes are displayed in the overlays section on the OpenLayer maps like on this example [1]. Seems to be a bug...

[1] http://semantic-mediawiki.org/wiki/Semantic_Maps_examples/Mapping_service_%28queries%29

**Comment by kghbln** [comment]
Indeed a bit irritating. +1 for a fix
