### ISSUE TITLE
Map page breaks on Edit. BlueSpice Compatibility Issue

### ISSUE THREAD

**Issue by johncourtland** [JeroenDeDauw/Maps#302]
### Setup

- MW version: 1.27.1
- DB (MySQL etc.): MySQL 5.5.54
- PHP version: 5.6.29 (cgi-fcgi)
- Maps version: 4.0.4
- SMW version (if applicable): 2.4.5
- BlueSpice version: 2.27
- Server: CentOS 7 VPS with LAMP 

### Issue
This is a compatibility issue with BlueSpice, the incompatibility is on BlueSpice, if I disable BlueSpice the Edit function for Wiki_Map works fine. If I enable BlueSpice, Edit function for Wiki_Map breaks to a blank page.

Per suggestions from the Semantic Mediawiki mailing list, I have disabled Extension:Lockdown, doing this produced no change to Wiki_Map issue, but at least the Lockdown is not invoked, and will not cause issues in other areas, thank you Karsten for that tip.

I understand I am working with two complex software projects that may not play well with each other, but if this is a fixable item, it would be wonderful to benefit from the fix.

I also understand that I'll probably be deferred to BlueSpice to file a bug report, that is good, but if there was a known issue here, I am taking a chance there may be solution.

Also, there is an interesting discussion at https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2015/BlueSpice_goes_Semantic
attached to that discussion is a fine video. So I know the two developers are working together to a certain extent. 

**Detailed description** of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

When BlueSpice is enabled, I am unable to edit the map page at http://tpwtestuser.com/mw/index.php?title=Wiki_Map.
The main issue is the ability to edit Wiki_Map page at the link of our test instance provided above, with BlueSpice enabled.
My trouble shooting efforts are limited to my experience, so they consisted of the basic "go-to" fixes as:
?action=purge, cleared cache, cleared browser cache, cleared win cache on desktop pc, deleted page, rebuilt page, deleted page, reproduced page with different name, tried different browsers, Edge, Mozilla, Chrome, Vivaldi.

It is noteworthy however that when the Wiki_Map is accessed via mobile device, specifically Android, I can edit the Wiki_Map page.

```
Deprecated: Use of BsExtensionManager::registerNamespace was deprecated in MediaWiki 2.27.0. [Called from Blog::onRegistration in /home/wood/public_html/tpwtestuser.com/mw/extensions/BlueSpiceExtensions/Blog/Blog.class.php at line 98] in /home/wood/public_html/tpwtestuser.com/mw/includes/debug/MWDebug.php on line 300

Deprecated: Use of BsExtensionManager::setContext was deprecated in MediaWiki 2.27.0. [Called from SaferEdit::onBeforeInitialize in /home/wood/public_html/tpwtestuser.com/mw/extensions/BlueSpiceExtensions/SaferEdit/SaferEdit.class.php at line 325] in /home/wood/public_html/tpwtestuser.com/mw/includes/debug/MWDebug.php on line 300

Deprecated: Use of BsExtensionManager::addContext was deprecated in MediaWiki 2.27.0. [Called from BsExtensionManager::setContext in /home/wood/public_html/tpwtestuser.com/mw/extensions/BlueSpiceFoundation/includes/ExtensionManager.class.php at line 43] in /home/wood/public_html/tpwtestuser.com/mw/includes/debug/MWDebug.php on line 300

Notice: Did not find alias for special page 'WikiExplorer'. Perhaps no aliases are defined for it? [Called from SpecialPageFactory::getLocalNameFor in /home/wood/public_html/tpwtestuser.com/mw/includes/specialpage/SpecialPageFactory.php at line 688] in /home/wood/public_html/tpwtestuser.com/mw/includes/debug/MWDebug.php on line 300

Deprecated: Use of BsExtensionManager::isContextActive was deprecated in MediaWiki 2.27.0. [Called from SaferEdit::onBeforePageDisplay in /home/wood/public_html/tpwtestuser.com/mw/extensions/BlueSpiceExtensions/SaferEdit/SaferEdit.class.php at line 71] in /home/wood/public_html/tpwtestuser.com/mw/includes/debug/MWDebug.php on line 300
```
ERROR LOG from our server
```
[Tue Jan 24 14:02:49 2017] [error] [client 70.32.24.228] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[Tue Jan 24 14:02:46 2017] [error] [client 47.156.32.145] PHP Catchable fatal error:  Argument 2 passed to SMMapPrinter::getMapHTML() must be an instance of Parser, instance of StubObject given, called in /home/wood/public_html/tpwtestuser.com/mw/extensions/Maps/SemanticMaps/src/queryprinters/SM_MapPrinter.php on line 201 and defined in /home/wood/public_html/tpwtestuser.com/mw/extensions/Maps/SemanticMaps/src/queryprinters/SM_MapPrinter.php on line 269, referer: http://tpwtestuser.com/mw/index.php?title=Wiki_Map
[Tue Jan 24 14:02:21 2017] [error] [client 70.32.24.228] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```
Per the STACK TRACE above, Extension:SaferEdit may have caused the issue, I commented out SaferEdit with no results.

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
Not applicable, BlueSpice would have to be enabled.

Thank you for looking at this!
John

**Comment by JeroenDeDauw** [comment]
I suspect this is some kind of JavaScript issue and recommend you have a look at your browsers JS console. Presumably the issue is the BlueSpice side, maps is not loading much crazy things.

**Comment by mwjames** [comment]
> Presumably the issue is the BlueSpice side, maps is not loading much crazy things.

@osnard FYI

**Comment by JeroenDeDauw** [comment]
The error in `SM_MapPrinter.php on line 269` has been fixed, not much more that can be done on the Maps side now.

**Comment by johncourtland** [comment]
UPDATE: BlueSpice V 2.27.1 seems to have addressed the issue, we can now edit Semantic Maps.

**Comment by JeroenDeDauw** [comment]
Awesome, and thanks for the status update!

**Comment by johncourtland** [comment]
Thank you for addressing this on your end Jeroen, I don't know if BS targeted the issue in their latest release, or by default it was fixed as a result of their latest release, however it happened, it happened, and that's what counts, life is good, thanks again.
