### ISSUE TITLE
Custom Leaflet markers are misaligned

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#304]
### Setup

- MW version: 1.28.0
- DB (MySQL etc.): MySQL 5.6.30
- PHP version: 5.6.29-0+deb8u1
- Maps version: 4.0.4
- SMW version (if applicable): 2.4.5

### Issue

When using Leaflet with a custom marker icon with (with `icon` or `activeicon`), the top left corner is always used has the center so the result is quite ugly:
![capture d ecran 2017-01-31 a 19 58 07](https://cloud.githubusercontent.com/assets/840125/22479885/b920db62-e7ef-11e6-929a-bd4b6a620bfa.png)

Leaflet has several icon properties that can be used to tweak this: http://leafletjs.com/examples/custom-icons/#creating-an-icon
But they currently can't be set from MediaWiki.

**Comment by JeroenDeDauw** [comment]
Thanks for filing this feature request!

FYI @PeterTheOne

**Comment by JeroenDeDauw** [comment]
@PeterTheOne do you still intend to tackle this? If not, probably good to not self-assign just yet

**Comment by PeterTheOne** [comment]
@JeroenDeDauw Sorry, but I still intend to do some work on this.

**Comment by JeroenDeDauw** [comment]
Not something to be sorry about :)

**Comment by Rudloff** [comment]
Are you sure this is fixed?
When I update to 4.4.0, my small custom icons are stretched:
![image](https://user-images.githubusercontent.com/840125/30774817-f78da874-a088-11e7-8854-b09e2efba580.png)

And I can't find a way to set the size manually.

**Comment by JeroenDeDauw** [comment]
Thanks for filing the new issue!
