### ISSUE TITLE
google map API KEY

### ISSUE THREAD

**Issue by doclav57** [JeroenDeDauw/Maps#305]
### Setup

- MW version:1.26.2
- DB (MySQL etc.):5.6.33
- PHP version:5.6.22
- Maps version:3.5.0
- SMW version (if applicable):

### Issue

Hello , i try to instal maps on my wiki, i follow the instalation instruction
wget http://getcomposer.org/composer.phar
php composer.phar require mediawiki/maps "*"

i go in my special pages maps extension was correctly instaled.

i replace my content file to this #180 

i have 2 error in my console 

"Google Maps API error: ApiNotActivatedMapError https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error"

"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"

and the map dont load

Can you tell me what I need to change

Sorry for my english and thanks

**Comment by doclav57** [comment]
sorry i take a wrong API Key , i replace geocodding API to javascript API and they have only one error 

"Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required"

**Comment by JeroenDeDauw** [comment]
I'm not seeing this code on the current codebase. Please use a recent version of Maps. (3.5 is no longer supported)
