### ISSUE TITLE
Ver 4.x.x causes parsing error in Wikipedia Template:Coord {{coord}}

### ISSUE THREAD

**Issue by jonesipedia** [JeroenDeDauw/Maps#315]
### Setup

- MW version: 1.29.0-wmf.20 (9d406de)
- DB (MySQL etc.): 10.1.20-MariaDB-1~xenial
- PHP version: 7.0.15-0ubuntu0.16.04.4 (apache2handler)
- Maps version: 4.0.x
- SMW version (if applicable): 2.5.0

### Issue

Installation of Maps 4.0.x causes the Wikipedia Template:Coord to report a parsing error in any page utilizing {{coord}}.  The error message in full is: "Fatal error: The format of the coordinate could not be determined. Parsing failed." The actual {{coords}} are displayed properly but include the parsing error message. 

The Wikipedia Template:Coord, ( https://en.wikipedia.org/wiki/Template:Coord ) is exported from wikipedia and imported to my instance of mediawiki. 

The actual language of the parsing error is delivered through "data-values/geo" and found on line 83 in "/_path_/_to_/extensions/Geo/src/Parsers/GeoCoordinateParser.php". 

There is no debug message that I have found that would seem to be help resolve the error message.

Maps Versions 3.x.x  do not exhibit the parsing error with {{coord}}. I have reverted to 3.8.2 to avoid the error message.

Am I missing another template/module/extension that might resolve the error?

Thanks,
Chap

**Comment by JeroenDeDauw** [comment]
I don't know about this template... Wikipedia does not use the Maps extension, so I'm not sure how they are related, if at all.

Do you know how Maps is getting invoked and what the input is?

**Comment by jonesipedia** [comment]
Jeroen,

At the moment I do not know how or why. All I know is 4.x.x returns an error and 3.x.x does not and data-values/geo is what reports the error. How it is triggered, I haven't a clue. I would imagine that 4.x.x and 3.x.x parse coordinates in a different fashion from each other. I'll keep trying to figure it out. 

Thanks,
Chap

**Comment by JeroenDeDauw** [comment]
Coordinate parsing should not have changed... at least not on the Maps side of things.

Did you have Semantic Maps installed before? If not, perhaps the template is clashing with one of it's features, which are enabled by default in 4.x if you have SMW installed. If you don't use them, you can disable them with this in your LocalSettings.php and see if that fixes the issue:

```php
$GLOBALS['egMapsDisableSmwIntegration'] = true;
```

If it does not, have a look at what versions of `data-values/geo` you use with Maps 3.x and 4.x. Perhaps 4.x is pulling in a newer version that no longer accepts something an older one did.

**Comment by mwjames** [comment]
> At the moment I do not know how or why. All I know is 4.x.x returns an error and 3.x.x does not and data-values/geo is what reports the error.

It may help to create an example on [0] that shows the error otherwise it will be very difficult for a developer to guess the cause let alone to fix it.

[0] https://sandbox.semantic-mediawiki.org

**Comment by kghbln** [comment]
No response in six months thus assuming this is no longer an issue. Please reopen in case it actually still is.

**Comment by Luensche** [comment]
I have the sime issue with Maps 5.1.0 and the template. For example on page [Adam-und-Eva-Haus](https://paderwiki.de/wiki/Adam-und-Eva-Haus).

**Comment by JeroenDeDauw** [comment]
Hey @Luensche, could you file a new ticket with a minimal list of steps to reproduce the issue? (With minimal I mean not needing a whole pile of templates full of irrelevant details first)
