### ISSUE TITLE
can't disable mouse scrolling: Scrollwheel zooms map in and out when scrolling through the page

### ISSUE THREAD

**Issue by stitch** [JeroenDeDauw/Maps#316]
### Setup
https://wiki.sha2017.org/w/Special:Version

### Issue

Scrolling through a page using the mouse zooms the map when hovering over it. Would like to disable mouse scrolling and just use the control.

Example:
https://www.semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_basic_map

Go here and and use your mouse wheel to scroll through the page.

Additionally: the static option doesn't work to fix this: when there are markers with large text-balloons, the position of the map is changed to show the text balloon after clicking: resulting you cannot use the mouse or anything else to show the original map except reloading the page. This makes the static option unusable.

**Comment by JeroenDeDauw** [comment]
At one point it was certainly possible to disable this scrolling... Not seeing any parameters in the current docs that do this for either Google Maps or OpenLayers. Perhaps this feature was somehow lost a few years ago? I don't recall. @kghbln any idea?

Anyway, I agree this would be good to have. And for all mapping services.

**Comment by kghbln** [comment]
I'd say that the current behaviour of `|static=yes` is all we ever had. At lease whithout or small text-ballons it works.

**Comment by Rudloff** [comment]
Leaflet has an option to disable this feature: http://leafletjs.com/reference-1.2.0.html#map-scrollwheelzoom

**Comment by PeterTheOne** [comment]
As I've seen today google maps changed its default, zooming works with `CTRL + Scroll` now.

**Comment by hidrarga** [comment]
We could add the `scrollwheelzoom` option for leaflet (and probably also for other map services). We discussed about this in a past PR (#354).
