### ISSUE TITLE
Ambiguous scrolling behavior with mouse wheel zooming

### ISSUE THREAD

**Issue by stitch** [JeroenDeDauw/Maps#317]
### Setup

https://www.semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_with_changed_zoom

### Issue

When min or maxzoom is reached (which can be done with the mouse wheel), the scrolling behavior of the mouse wheel changes to pane in a certain direction. This makes navigating to depth at a certain marker an absolute pain as the map hops to an entirely different area that has nothing to do with the thing you wanted to look at.

See the example page: just use the mouse wheel to zoom in to a specific point: you'll most likely be unable to do so as the map just panes all over the place.

**Comment by JeroenDeDauw** [comment]
I concur that this is not what should happen. Though I suspect that the issue here does not lie with the Maps extension but instead with OpenLayers. Then again we are using a 6 years old version, so perhaps we should upgrade as per https://github.com/JeroenDeDauw/Maps/issues/88

**Comment by stitch** [comment]
Sounds better than trying to fix the old stuff 👍
