### ISSUE TITLE
Documentation regarding the "layers" option is missing

### ISSUE THREAD

**Issue by stitch** [JeroenDeDauw/Maps#318]
### Setup

https://www.semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_with_layer_maps

### Issue

There is no documentation is "what a layer is", "how to make one", "how to find out what layers exist" and etcetera. Please point a map newbie to the right sources, it's currently dark magic.

**Comment by stitch** [comment]
Found some documentation here:
https://www.semantic-mediawiki.org/wiki/Extension:Maps/mapping_service

But it's incomplete. 

For SHA2017 we added this config, which might serve as an example:

$egMapsOLAvailableLayers['layername'] = array("OpenLayers.Layer.XYZ(
                'base',
                'https://map.yourserver.org/tiles/base/\${z}/\${x}/\${y}.png',
                {
                    singleTile:false,
                    sphericalMercator: true,
                    isBaseLayer: false,
                    visibility: true,
                    displayInLayerSwitcher: true
                }
            )");

**Comment by JeroenDeDauw** [comment]
Help with these docs is much appreciated

**Comment by kghbln** [comment]
> Help with these docs is much appreciated

Very much so. I hardly use Maps but seem to be the only clown to document it nowadays. The result is to be seen. So go for it!

**Comment by mwjames** [comment]
>  Maps but seem to be the only clown to document it nowadays

I like the expression but of course I don't like idea of you being held captive as  "docu" slave.

**Comment by JeroenDeDauw** [comment]
No one should feel obliged to do anything if they don't want to (beyond repairing damage they did and similar). We're all volunteers here :)

And there is no cage that can hold kgh!

![escape](https://cloud.githubusercontent.com/assets/146040/26021968/de983036-3798-11e7-984d-96c89f6e54d2.png)

**Comment by kghbln** [comment]
As a good clown one should be a sad person but not a grumpy one. So we are cool. Talking about [breaking free and bunnies](https://www.youtube.com/watch?v=eM8Ss28zjcE). Note the shoes. :D

**Comment by m-art-in** [comment]
@stitch can you explain your tiles / tilesserver a  bit more? 
I have an old map as png, would should I do to display the .png with leaflet as layer?
