### ISSUE TITLE
Zoom control slider goes out of bounds

### ISSUE THREAD

**Issue by stitch** [JeroenDeDauw/Maps#320]
### Setup

https://www.semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_with_changed_zoom

### Issue

Clicking on the zoom control demonstrates it's possible to have the slider go beyond the "+" marker and into the directional buttons. At least on the latest version of chrome. 

Just hit the + button and see the slider moving out of the bar.

**Comment by JeroenDeDauw** [comment]
Also seeing this on FireFox.

When clicking minus afterwards the value stays stuck at max. Which makes me think we might be providing incorrect values to the OpenLayers API.

**Comment by PeterTheOne** [comment]
My guess is that it is an OL issue.. so maybe lets do #88 first.
