### ISSUE TITLE
Leaflet misses documentation on adding layers

### ISSUE THREAD

**Issue by stitch** [JeroenDeDauw/Maps#327]
Missing the documentation on adding layers to leaflet. Wanting to try out another service to see what it does.

Documentation link:
https://www.semantic-mediawiki.org/wiki/Extension:Maps/mapping_service

Result:
![image](https://cloud.githubusercontent.com/assets/333846/25995328/1fdf2aa4-3712-11e7-92ba-b76f50646b47.png)

**Comment by PeterTheOne** [comment]
I'm surprised that I still have no wiki account.. can someone approve my account request, so that I can add some documentation? ^^ @kghbln

**Comment by kghbln** [comment]
@PeterTheOne Actually you already have an [account](https://www.semantic-mediawiki.org/wiki/User_talk:PeterTheOne) which was freigeschaltet 13 months ago.

**Comment by PeterTheOne** [comment]
@kghbln Hmm, then I'm not getting my password reset emails.. :/

**Comment by kghbln** [comment]
@PeterTheOne I have now [renamed](https://www.semantic-mediawiki.org/w/index.php?title=Special%3ALog&type=renameuser&user=&page=User%3APeterTheOne) your old account to make room for a new one.

**Comment by kghbln** [comment]
@PeterTheOne So this worked?

**Comment by PeterTheOne** [comment]
@kghbln After fishing two mails out of a spam folder and one pw reset, it worked! :+1:

**Comment by PeterTheOne** [comment]
@kghbln Sry, for being super annoying.. I still can't edit because I need to verify my E-Mail, the link I got expired before it said so. It seems I'm not getting a new link..

**Comment by kghbln** [comment]
@PeterTheOne So it is not possible to request another confirmation e-mail via Special:Preferences? I cannot switch to self-service since nocaptcha was cracked too at least I got four spam accounts an hour after switching to it. :(

**Comment by PeterTheOne** [comment]
@kghbln I did request it twice, but no e-mail response.. after over 20min.

**Comment by kghbln** [comment]
No wonder. gmail bounces the e-mails which does not surprise me. Heaps of problems with gmail on other places, too. Do you happen do have an e-mail account with a reliable provider?

**Comment by PeterTheOne** [comment]
I finally got my e-mail activated! :)

Updated: https://www.semantic-mediawiki.org/wiki/Extension:Maps/mapping_service#Leaflet
Added: https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_with_layer_maps

If you have feedback, feel free to say or change things..

Note that there is only a fixed list of [available layers](https://github.com/JeroenDeDauw/Maps/blob/264a63b9110ced876dd24069c2204e2d3cbceb55/Maps_Settings.php#L347-L428) for leaflet now. I already made an attempt at implementing adding new tileurls, it was quite naive security wise, see.. https://github.com/JeroenDeDauw/Maps/pull/196

**Comment by kghbln** [comment]
> I finally got my e-mail activated! :)

Great, this was not gmail, wasn't it?

**Comment by PeterTheOne** [comment]
It was gmail.

**Comment by kghbln** [comment]
> It was gmail.

Lucky you that the e-mail got through.

**Comment by Nikerabbit** [comment]
Is there task for actually being able to configure new layers? Local code modifications are no-no for me.

**Comment by PeterTheOne** [comment]
> Local code modifications are no-no for me.

I'm with you on that! There is no Taks for that yet, there is only #196 for now.
