### ISSUE TITLE
Special:MapEditor not showing

### ISSUE THREAD

**Issue by a01020304uk** [JeroenDeDauw/Maps#330]
hello, I use miraheze.org to host my wiki and have had them install the Maps script and for the most part it works, however MapEditor is not showing on the special page.
I have tried to explain to them what that page is but am not doing well. I presume they missed out a setting or something so what do they need to do to make the Special:MapEditor show and be used?
My wiki is: https://ayrshire.miraheze.org

if they need to do something can you post the result on their techy page
https://phabricator.miraheze.org/maniphest/task/edit/form/1/

**Comment by JeroenDeDauw** [comment]
Please specify which versions of the relevant software you are using. I can't even access https://ayrshire.miraheze.org/wiki/special:version ...

**Comment by a01020304uk** [comment]
Mediawiki Version: 1.28
Maps Version: 4.1.0
PHP 	5.6.30-0+deb8u1 (fpm-fcgi)
MariaDB 	10.0.28-MariaDB-0+deb8u1
ICU 	52.1
Lua 	5.1.5

**Comment by a01020304uk** [comment]
i can send you a private message with logon details if you give me some way of sending it to you

**Comment by JeroenDeDauw** [comment]
Those details suffice.

Is it showing on `Special:SpecialPages`? It should be listed there under "Maps" as "Map editor".

**Comment by a01020304uk** [comment]
No, its not showing thats the problem, I have tried explaining to them that it should show but they dont understand what I mean. Maps shows fine as installed but when you look at Special page no Map Editor is showing
![clipboard03](https://cloud.githubusercontent.com/assets/14941361/26129412/0417142a-3a88-11e7-8be4-22b814ddf8d8.jpg)
![clipboard01](https://cloud.githubusercontent.com/assets/14941361/26129414/041a2908-3a88-11e7-99d8-fa503a8cc55a.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/14941361/26129413/0418f1f0-3a88-11e7-9a56-a805dd0915dc.jpg)

**Comment by a01020304uk** [comment]
thats why I suggest you leave a message on the phrabricator link i gave above as you can communicate directly with sysop

**Comment by JeroenDeDauw** [comment]
Can you access Special:MapEditor itself?

And to which degree is Maps working? Is it just listed on Special:Version, or does #display_map also work?

**Comment by a01020304uk** [comment]
Map displays on page as shown and also the code and is fine, but as for special:mapeditor that does not exist

![clipboard03](https://cloud.githubusercontent.com/assets/14941361/26132686/d78bf030-3a99-11e7-8ec5-9dc3ec08ec67.jpg)
![clipboard01](https://cloud.githubusercontent.com/assets/14941361/26132685/d78aafe0-3a99-11e7-922b-7499b356daca.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/14941361/26132687/d78e8692-3a99-11e7-8413-d329d7872e49.jpg)

**Comment by JeroenDeDauw** [comment]
I just had a look at the code to see if there are any special requirements for this special page, and indeed, you need to have Google Maps enabled. I guess this is not the case on your wiki.

**Comment by a01020304uk** [comment]
you mean this code?
$GLOBALS['egMapsGMaps3ApiKey'] = 'your-api-key';

**Comment by JeroenDeDauw** [comment]
That needs to be set yes. Though it is not the code I was referring to, which is:

```php
	if ( in_array( 'googlemaps3', $GLOBALS['egMapsAvailableServices'] ) ) {
		$GLOBALS['wgSpecialPages']['MapEditor'] = 'SpecialMapEditor';
		$GLOBALS['wgSpecialPageGroups']['MapEditor'] = 'maps';
	}
```

So you also need to have `$GLOBALS['egMapsAvailableServices']` set correctly. By default it has Google Maps, but you might have changed that.

**Comment by a01020304uk** [comment]
can OSM and Google not work together?, mapedit shows google but sisplay map wiki shows osm?

**Comment by a01020304uk** [comment]
I will have to have admin check that code so might take a few days to get back to you.

**Comment by a01020304uk** [comment]
should that code not be automaic installed when maps installed via composer?

**Comment by JeroenDeDauw** [comment]
What I posted is code internal to Maps. You should not touch this or copy it anywhere. I was merely illustrating that Maps does a check based on the `egMapsAvailableServices` configuration, which suggests that in your case it needs modifying.

By default Google Maps should be enabled. (Though it will not work unless you put in the API key.)

I've updated the documentation to include a mention that you need Google Maps for the MapEditor special page: https://www.semantic-mediawiki.org/wiki/Extension:Maps

Closing this now as there does not appear to be an issue with Maps itself.
