### ISSUE TITLE
implement Leaflet static option

### ISSUE THREAD

**Issue by PeterTheOne** [JeroenDeDauw/Maps#351]
Leaflet static option doesn't work, for googlemaps3 it looks like this: https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_with_a_static_map

**Comment by kghbln** [comment]
Implemented with 4.4.0 and already [documented.](https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_with_a_static_map)
