### ISSUE TITLE
implement Leaflet copycoords option

### ISSUE THREAD

**Issue by PeterTheOne** [JeroenDeDauw/Maps#352]
`copycoords` option is not working with leaflet, see googlemaps3 version: https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_with_copyable_coordinates

**Comment by kghbln** [comment]
OpenLayers was actually providing this parameter, too. Now that it is gone in the latest release 7+ it will be great to have it. Moreover since Leafleat does not show the current coordinates in the bottom right of the map as OpenLayers did.

**Comment by JeroenDeDauw** [comment]
This was done in Maps 6.3

**Comment by JeroenDeDauw** [comment]
If you think it would be useful to have that work all over the map, please create a new ticket for it

**Comment by kghbln** [comment]
> If you think it would be useful to have that work all over the map, please create a new ticket for it

I think it is just fine now. I was initially struggling because of the changed behaviour.
