### ISSUE TITLE
Custom markers are resized to 25x41 px

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#360]
### Setup

- MW version: 1.29.1
- DB (MySQL etc.): 5.5.57
- PHP version: 5.6.31-1~dotdeb+7.1
- Maps version: 4.4.0
- SMW version (if applicable): 2.5.4

### Issue

I'm creating a new bug following https://github.com/JeroenDeDauw/Maps/issues/304#issuecomment-331645611 because this is not fixed.

We have custom markers that are smaller than the regular Leaflet markers:
![oval-15](https://user-images.githubusercontent.com/840125/30783007-c358eb04-a13c-11e7-8acf-018a65f28601.png)

Since Maps 4.4.0, the marker size is forced to 25x41 px (Leaflet's default size) so our markers are resized to this size:
![image](https://user-images.githubusercontent.com/840125/30782938-0105d914-a13b-11e7-9492-e81cb3d0cfdc.png)

As a workaround, I created 25x41 px marker images with blank padding, it's better but now the tooltip is too high (and the hitbox is bigger than the visible marker, which is confusing for users):
![image](https://user-images.githubusercontent.com/840125/30782994-7fa4b5d2-a13c-11e7-9c35-0f80e2657d72.png)

**Comment by hidrarga** [comment]
I'm trying to solve this, but the problem is that I would need the size of the icon in order to adjust the marker's position. 

The approach I'm currently exploring is the following : I override the [createIcon](https://sandbox.semantic-mediawiki.org/wiki/Seattle) method, then I implement the img's `onload` method, which let me retrieve the icon height and width. However, I don't know how I can update the marker's position from there...

**Comment by Rudloff** [comment]
Wouldn't it be possible to add `iconSize` and `iconAnchor parameters so we can set this ourselves?

**Comment by hidrarga** [comment]
Indeed, I was also thinking about this solution. For me, this would be the easiest way, but I'd like to hear what @JeroenDeDauw (for instance) thinks of this before starting to work on this :)

**Comment by JeroenDeDauw** [comment]
Since you can use many different images on the same map, you'd need to add another per-location parameter. And even if that was not needed, it'd still be weird to be forced to deal with this as a user. A solution that "just works" would be a lot cooler.
