### ISSUE TITLE
Content of the popup window not fully parsed

### ISSUE THREAD

**Issue by hidrarga** [JeroenDeDauw/Maps#371]
In MediaWiki 1.28 and 1.29, the content of the popup window in the map is not properly parsed. For instance, links are not showing up. You can see an example there : https://sandbox.semantic-mediawiki.org/wiki/Maps_using_templates_-_leaflet

What seems to solve the problem for me is to replace in `SM_QueryHandler.php` the line 
```php
$text .= $this->getParser()->recursiveTagParse(
```
with 
```php
$text .= $this->getParser()->recursiveTagParseFully(
```

As explained [in the doc](https://doc.wikimedia.org/mediawiki-core/master/php/classParser.html#aef9a0411fd9a56751464a0eadb14e60d) : 
>The output of [`recursiveTagParse()`] IS NOT SAFE PARSED HTML; it is "half-parsed" instead, which means that lists and links have not been fully parsed yet, and strip markers are still present. 
>Use `recursiveTagParseFully()` to fully parse wikitext to output-safe HTML.

Could you confirm that this solves the bug ?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting! I cannot look at this today, but if it fixes the issue for you, then feel free to provide a PR with the fix. That'd be much appreciated.

**Comment by JeroenDeDauw** [comment]
Thanks for the PR :) Now I can just wait and see if the sandbox gets fixed or not. The lazy part of me approves this very much!

**Comment by hidrarga** [comment]
You are welcome ! :grin:

The reason I was hesitant is that I don't know why we used `recursiveTagParser` in the first place.

**Comment by JeroenDeDauw** [comment]
It's working! 383e4668a27346c27b58bd0b9c2c0ad7b25955aa
