### ISSUE TITLE
5.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#376]
I'd like to get this out in October, preferably sooner than later, as two bugs have been fixed and two useful features added. Will create a RC soon.

Testing is very welcome.

Similarly, if you know of something that should be killed of or otherwise changes in a breaking manner, please point it out before the RC, else it's going to have to wait a while till the next major release.

**Comment by JeroenDeDauw** [comment]
Actually not going to bother with a RC. If there is a bug we can always do a new patch release as per usual procedure

**Comment by kghbln** [comment]
So we need 5.1.0 because of https://github.com/JeroenDeDauw/GitHub/issues/46

**Comment by kghbln** [comment]
@JeroenDeDauw I now pulled 5.x from smw.o since the latest release is more important for the wiki than latest maps. However, thinking about this issue a second time I do not know why still supporting PHP 5.6 would break the setup. Maps 4.4.0 also supported PHP 5.6 so why did it work there?

**Comment by JeroenDeDauw** [comment]
The answer to that is kinda technical. In short: maps now implements an interface from the FileFetcher component, and it is not possible to be compatible with the PHP 5 and PHP 7 versions of that interface at the same time.

**Comment by kghbln** [comment]
Ah, I get it. Thanks for 5.0.1. All in fluff now:
![googplanbunny](https://user-images.githubusercontent.com/1104078/31707933-f3822034-b3ed-11e7-92fe-1620aedc4c7c.jpg)
```
composer update --prefer-source
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating mediawiki/maps (4.4.0 => 5.0.1):  Checking out 62332a76ac
Writing lock file
Generating optimized autoload files
```
