### ISSUE TITLE
Fatal PHP error Class 'DataValues\Geo\Parsers\LatLongParser'

### ISSUE THREAD

**Issue by Reception123** [JeroenDeDauw/Maps#382]
### Setup

- Maps version: Latest (5.0)
- MW version: 1.29.1
- PHP version: 5.6.30
- SMW version (if applicable): N/A

### Issue

After updating to the latest version of Maps on a wiki, when it is enabled a HTTP 500 happens and the logs show the fatal PHP error below. 

[19-Oct-2017 18:46:30 UTC] PHP Fatal error:  Class 'DataValues\Geo\Parsers\LatLongParser' not found in /srv/mediawiki/w/extensions/Maps/src/Geocoders/CoordinateFriendlyGeocoder.php on line 25

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Updating to the latest version (5.0)

**Comment by JeroenDeDauw** [comment]
For some reason you do not have one of the libraries the Maps extension needs, or at least not the latest version.

If you install the extension with composer, this should not happen. Did you upgrade from an old version of MediaWiki as well? Try removing the extension completely and following the installation instructions.

**Comment by Reception123** [comment]
The wiki was running 1.29.1 and then I updated the Maps submodule to the latest version. It was initially installed with Composer.

**Comment by JeroenDeDauw** [comment]
And how did you update? Not by running `composer update` I take it? That is what you need to do. If you installed the extension as is recommended, then run this in the root directory of your MW install.

**Comment by Reception123** [comment]
Thank you very much! Updating composer did indeed fix the problem.
