### ISSUE TITLE
Map attribution not shown

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#384]
### Setup

- Maps version: 5.0.2
- MW version: 1.27.3

### Issue
Maps show "Leaflet | © OpenStreetMap contributors" as attribution no matter what is set as custom attribution.

e.g. usually, custom attributions are set
 https://github.com/JeroenDeDauw/Maps/blob/9a35aad579d0e2f733bce4a62281390172ff8680/includes/services/Leaflet/leaflet-providers/leaflet-providers.js#L534

and the default should get replaced here:
https://github.com/JeroenDeDauw/Maps/blob/9a35aad579d0e2f733bce4a62281390172ff8680/includes/services/Leaflet/leaflet-providers/leaflet-providers.js#L71-L84

but anyway, this does not seem to work:
http://standards.kdz.eu/index.php?title=MapsTest

**Comment by PeterTheOne** [comment]
Thanks for the catch! :) Fixed in PR #386..
