### ISSUE TITLE
Feature: Layer Groups and Layers Control for leaflet 

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#387]
leaflet Layer Groups and Layers Control should be supported: http://leafletjs.com/examples/layers-control/

**Comment by PeterTheOne** [comment]
Should we rename the leaflet `layer` option to `layers` like it is with the openlayers service? And then if there is more than one layer defined make this [Layers Control](http://leafletjs.com/examples/layers-control/) appear?

**Comment by JeroenDeDauw** [comment]
Sounds good to me. Seems kinda odd to specify a map with multiple layers and then only be able to look at one of them :)

If you rename the parameter, please put an alias in place so the old name keeps working. Or perhaps just add an alias and save yourself some rename work inside of the codebase. (Renaming the main name is cleaner though.)
