### ISSUE TITLE
Better clustering behaviour for makers on the same location

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#39]
http://sourceforge.net/p/semediawiki/mailman/message/32510196/
## 

Hi all,

I have this inline query:

{{#ask:[[Has Coordinates::+]]
|?Has Coordinates
|format=googlemaps
|markercluster=yes
|height=400
}}

Has Coordinates was geocoded from a string property Country in a Template
as follows:

...
! Countries
| {{#arraymap:{{{Countries|}}}|,|x|[[Country::x]] {{#set:Has
Coordinates={{#geocode:x|geonames}}
...

And its pretty nice!  My problem is if I have multiple items with the exact
same coordinates (say, I have 10 pages for Sudan), the markerclusterer
logic in Semantic Maps just zooms in and doesn't have any processing to
show the items on the exact same location.  It just shows the cluster.

Ideally, something similar to this "spidercluster" effect would be nice:

http://www.ejw.de/ejw-vor-ort/   (click on a marker to show the spider
effect).

Thanks in advance!
Joel

**Comment by PeterTheOne** [comment]
We could use:

- https://github.com/jawj/OverlappingMarkerSpiderfier for googlemaps
- https://github.com/Leaflet/Leaflet.markercluster for Leaflet (first update to Leaflet 1.0 when its out)
- https://github.com/CandoImage/OL3ClusterSpiderfier for OpenLayers 3 (we use OL 2 now)

**Comment by kghbln** [comment]
See a live example on [sandbox.smw.o](http://sandbox.semantic-mediawiki.org/wiki/Locations) for this.

**Comment by JeroenDeDauw** [comment]
I think this is effectively fixed by the markercluster support that we've now had for quite some time... I updated the example on the sandbox with a cluster map: https://sandbox.semantic-mediawiki.org/wiki/Locations

**Comment by kghbln** [comment]
> I think this is effectively fixed by the markercluster support that we've now had for quite some time... I updated the example on the sandbox with a cluster map: https://sandbox.semantic-mediawiki.org/wiki/Locations

Indeed. Great! I did not think of this.

**Comment by PeterTheOne** [comment]
fyi #200 is still open.
