### ISSUE TITLE
PHP code errors

### ISSUE THREAD

**Issue by Reception123** [JeroenDeDauw/Maps#397]
### Setup

- Maps version: latest
- MW version: 1.30 (rc)
- PHP version: 5.6
- SMW version (if applicable): 

### Issue

PHP code issue here: https://github.com/JeroenDeDauw/Maps/blob/master/includes/Maps_MappingServices.php#L67

PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /srv/mediawiki/w/extensions/Maps/includes/Maps_MappingServices.php on line 67
```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by Reception123** [comment]
@JeroenDeDauw I believe this is a feature of PHP 7? If that is the case, is it possible to also have a PHP 5 version (branch) since many servers are still on PHP 5 and do not support this new feature that you have added.

**Comment by JeroenDeDauw** [comment]
Indeed. You cannot run the latest version of Maps with PHP 5.x.

For an overview of compatibility, including the versions of Maps you can run with PHP 5.x, see https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#platform-compatibility-and-release-status

Not sure how you ended up with an incompatible version. If you install Maps with Composer into MediaWiki, Composer should prevent this from happening. I take it you installed Maps manually and ran Composer inside of the Maps directory?
