### ISSUE TITLE
resource loading broken when maps not located directory named "extensions"

### ISSUE THREAD

**Issue by oetterer** [JeroenDeDauw/Maps#401]
### Setup

- Maps version: 5.1.0
- MW version: 1.27.4
- PHP version:  5.6
- SMW version (if applicable): 2.5.5

### Issue
My extensions are not located "below" but rather "next to" the mediawiki directory. e.g.:

```
_extensions
_images
mediawiki
_skins
```
Furthermore, the directory containing the extensions is not named "extensions". 

Integration is done via symlink located in the mediawiki directory
```
mediawiki/extensions -> ../_extensions
```
and also by setting `$wgExtensionDirectory`. Works so far perfectly.

Unfortunately, with maps resource loading fails in
```
Maps.resources.php
includes/services/GoogleMaps3/GoogleMaps3.php
includes/services/Leaflet/Leaflet.php
includes/services/OpenLayers/OpenLayers.php
```
Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

move Maps to a directory other than "extensions". ;)

**Comment by kghbln** [comment]
Thanks for reporting and providing a patch. I have requested a code review.

**Comment by JeroenDeDauw** [comment]
PR at https://github.com/JeroenDeDauw/Maps/pull/402
