### ISSUE TITLE
Google Maps enable scrollwheelzoom

### ISSUE THREAD

**Issue by PeterTheOne** [JeroenDeDauw/Maps#409]
Google Maps changed their default mouse scrolling behaviour: It only scrolls with `CTRL + Scroll`.

And we have a new parameter `scrollwheelzoom` see #407.

Imho when `scrollwheelzoom` is true then Google Maps should scroll without `CTRL`. The Google Maps option for that is `gestureHandling: 'greedy'`, see: https://developers.google.com/maps/documentation/javascript/interaction .

Also related to #316.

**Comment by PeterTheOne** [comment]
@hidrarga do you want to take a shot at this?

**Comment by hidrarga** [comment]
Hmm so here by default `scrollwheelzoom` would be `false` (= scrolling with `CTRL+ Scroll`), and when set to `true` it would force mouse scrolling? Not sure to see why one would want to do that, but why not ?

[I see in the code](https://github.com/JeroenDeDauw/Maps/blob/master/includes/services/GoogleMaps3/jquery.googlemap.js#L510) that scrolling is disabled with `scrollwheel = false` in static mode. I've never used Google Map's API, so I'll need to search what's the difference between this and `gestureHandling`.

**Comment by hidrarga** [comment]
Ok, it seems that `scrollWheel` is only there to enable or not mouse scrolling at all. As we want to force it, we must use `gestureHandling` indeed.
