### ISSUE TITLE
TypeError from line 84 "Maps_MappingService.php"

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#413]
### Setup

- Maps version: 5.3.0 alpha (9dffb6a) 10:05, 8 February 2018
- MW version: 1.30.0 (4998ed3) 23:28, 7 February 2018
- PHP version: 7.0.27-0+deb9u1 (apache2handler)
- DB version: 10.1.26-MariaDB-0+deb9u1
- SMW version: 3.0.0-alpha (27302c3) 22:36, 10 February 2018
- Whats Nearby version: 1.0.0-alpha (44c8faa) 10:30, 12 January 2018

### Issue
Finally I upgraded the OS. As a result of now using PHP 7.0 I was able to upgrade to recent master of Maps. Now, when rebuilding the semantic data with "rebuilldData.php" the following failure appears:

```
[no req]   TypeError from line 84 of /../w/extensions/Maps/includes/Maps_MappingService.php: Argument 1 passed to MapsMappingService::addDependencies() must be an instance of ParserOutput, instance of Parser given, called in /../w/extensions/WhatsNearby/src/NearbyParserFunction.php on line 124
```

### Backtrace
When trying to rebuild the semantic data with "rebuildData.php" I get the following backtrace:

```
#0 /../w/extensions/WhatsNearby/src/NearbyParserFunction.php(124): MapsMappingService->addDependencies(Parser)
#1 /../w/extensions/WhatsNearby/src/NearbyParserFunction.php(51): WNBY\NearbyParserFunction->addMapServicesToOutput(array)
#2 /../w/extensions/WhatsNearby/src/ParserFunctionFactory.php(26): WNBY\NearbyParserFunction->parse(array)
#3 /../w/includes/parser/Parser.php(3383): WNBY\ParserFunctionFactory->WNBY\{closure}(Parser, string, string, string, string, string, string, string, string, string, string, string)
#4 /../w/includes/parser/Parser.php(3106): Parser->callParserFunction(PPFrame_DOM, string, array)
#5 /../w/includes/parser/Preprocessor_DOM.php(1229): Parser->braceSubstitution(array, PPFrame_DOM)
#6 /../w/includes/parser/Parser.php(2921): PPFrame_DOM->expand(DOMElement, integer)
#7 /../w/includes/parser/Parser.php(1277): Parser->replaceVariables(string)
#8 /../w/includes/parser/Parser.php(451): Parser->internalParse(string)
#9 /../w/includes/content/WikitextContent.php(329): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#10 /../w/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#11 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(183): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#12 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(144): SMW\ContentParser->fetchFromContent()
#13 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(204): SMW\ContentParser->parse()
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(134): SMW\MediaWiki\Jobs\UpdateJob->doupdateTypeFreshContentParse()
#15 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(92): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#16 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityRebuildDispatcher.php(204): SMW\MediaWiki\Jobs\UpdateJob->run()
#17 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(312): SMW\SQLStore\EntityRebuildDispatcher->startRebuildWith(integer)
#18 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(267): SMW\Maintenance\DataRebuilder->doExecuteFor(SMW\SQLStore\EntityRebuildDispatcher, integer)
#19 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(168): SMW\Maintenance\DataRebuilder->doRebuildAll()
#20 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(157): SMW\Maintenance\DataRebuilder->rebuild()
#21 /../w/maintenance/doMaintenance.php(92): SMW\Maintenance\RebuildData->execute()
#22 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(206): require_once(string)
#23 {main}
```

**Comment by kghbln** [comment]
@mwjames FYI

**Comment by PeterTheOne** [comment]
https://github.com/SemanticMediaWiki/WhatsNearby/blob/717c85bd63f968781f9ce94514d37edc560bfcab/src/NearbyParserFunction.php#L124

calls addDependencies with a `Parser` but
https://github.com/JeroenDeDauw/Maps/blob/4c1d0a848b3b9d157a2dc53e452aebbad7ded44c/includes/Maps_MappingService.php#L84
wants a `ParserOutput`.

**Comment by mwjames** [comment]
> https://github.com/SemanticMediaWiki/WhatsNearby/blob/717c85bd63f968781f9ce94514d37edc560bfcab/src/NearbyParserFunction.php#L124
>
> calls addDependencies with a `Parser` but

Which is not the cause, the cause is the change in the signature [0]!!

[0] https://github.com/JeroenDeDauw/Maps/commit/6453e06e5ca9757f0b4690d04a8229ec50caf9a5

**Comment by JeroenDeDauw** [comment]
@PeterTheOne @mwjames Thanks to you both for identifying parts of the cause!

I only checked quickly but it looks like WhatsNearby can easily be updated to pass $parser->getOutput instead of $parser. I'm also fine with the PR being reverted.

**Comment by kghbln** [comment]
> I only checked quickly but it looks like WhatsNearby can easily be updated to pass $parser->getOutput instead of $parser. I'm also fine with the PR being reverted.

Looking at the PR and the related discussion it appears to me that it provides a code improvement. If it is just an easy change for WhatsNearby I'd personally opt for tackling the issue over there.

**Comment by kghbln** [comment]
Fixed with https://github.com/SemanticMediaWiki/WhatsNearby/pull/18
