### ISSUE TITLE
Set version for jeroen/simple-geocoder

### ISSUE THREAD

**Issue by Nikerabbit** [JeroenDeDauw/Maps#417]
### Issue

I am having a weird issue with composer, so that every second run uninstalls jeroen/simple-geocoder and every second run installs it:
 - Marking jeroen/simple-geocoder (1.1.x-dev a1ae573) as uninstalled, alias of jeroen/simple-geocoder (dev-master a1ae573)

And next run:
 - Installing jeroen/simple-geocoder (dev-master a1ae573): Executing command (CWD): git --version

Maybe if you set a specific version to it, this wouldn't happen?

**Comment by Nikerabbit** [comment]
I just set the version to 1.1.0 in my composer.local.json and it avoids this bug.

**Comment by JeroenDeDauw** [comment]
WTH... WTF is this still `@dev` :D

Thanks for reporting this and sorry for the hassle.

https://github.com/JeroenDeDauw/Maps/pull/418

**Comment by kghbln** [comment]
Composer is badly broken. See https://github.com/composer/composer/issues/7268 Just roll back 1.6.3 and you are fine until they fixed the issue.
