### ISSUE TITLE
New configuration parameter `egMapsAvailableGeoServices`

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#430]
### Setup

- MediaWiki | 1.31.0-rc.0 (6a329de)18:47, 16. Mai 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Maps | 5.4.0 alpha (c364940) 11:09, 18. Mai 2018

### Issue

Currently it is not possible to explicitly exclude a specific geocoding service. I will be nice to be able to do so as we can do with the `egMapsAvailableServices` configuration parameter for mapping services. Imho this becomes more important in the light of the upcoming changes for Google Maps.

**Comment by JeroenDeDauw** [comment]
I don't understand why you want this. I removed that setting in 5.0 (https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md#breaking-changes) as now you can't choose the service anymore as user of the wiki, as it can only be set in the config.

**Comment by kghbln** [comment]
> as now you can't choose the service anymore as user of the wiki, as it can only be set in the config.

Fair enough. Thanks for the pointer. I was grumpy yesterday and shooting in all directions. :(
