### ISSUE TITLE
Giving a specific address is not working

### ISSUE THREAD

**Issue by martin-edelmann** [JeroenDeDauw/Maps#433]
### Setup

- Maps version: 5.3.0
- MW version: 1.30.0
- PHP version: 7.1.17

### Issue

Giving a specific address like
```{{#display_map:23, Ilyinka Street, Moscow, 103132, Russia | service=leaflet}}```
is not correctly displaying the expected result. Instead the map shows the blue ocean somewhere to the west of Africa.
C locale is set by ```$wgShellLocale = 'C.UTF-8';```
The problem described can also be found on the [examples page](https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_map_with_one_point), in the last two examples.

**Comment by JeroenDeDauw** [comment]
Try setting the geocoding service to nomatim as seen here https://github.com/JeroenDeDauw/Maps/blob/bde92e46a1045083ffc99cfbd6a0799ca2e6b697/Maps_Settings.php#L59

Or keep it on geonames and set https://github.com/JeroenDeDauw/Maps/blob/bde92e46a1045083ffc99cfbd6a0799ca2e6b697/Maps_Settings.php#L64

I'm assuming the issue is you have it on geonames without the geonames user, in which case Maps falls back on Google and Google now requires you to pay for their shit. The next version of Maps will have nomatim by default so this does not happen.

**Comment by kghbln** [comment]
@JeroenDeDauw s-mw.o is in fact using the following setup:

```php
## Maps
// Composer
$egMapsDefaultService = 'leaflet';
$egMapsDefaultGeoService = 'nominatim';
```
Thus  the link provided proves that it is indeed not working, at least with "nominantim". Before switching to "nominantim" the maps on [this page](https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2018) were not working either - basically nothing was working at all. However they do now. I come to conclude that "nominantim" does not know the address and therefore cannot translate it into a set of co-ordinates. I guess there is nothing Maps may do to help the cause in this case.

@martin-edelmann You could try the "geonames" service and see if it is working. Other than that we are looking at a lost cause when not using Google. If you would like to use Google I wish lost of fun. Even after hours I was not able to set up a working Google Maps API for geocoding. :|

**Comment by hidrarga** [comment]
Indeed, and here you can check if Nominatim has results for a given address : https://nominatim.openstreetmap.org

To solve your specific problem : it seems to work when you remove the postal code : https://nominatim.openstreetmap.org/search.php?q=23%2C+Ilyinka+Street%2C+Moscow%2C+Russia&polygon_geojson=1&viewbox= ;)

**Comment by kghbln** [comment]
> Indeed, and here you can check if Nominatim has results for a given address : 

Good pointer!

> To solve your specific problem

Indeed after removing the postal code the point [starts to render](https://www.semantic-mediawiki.org/wiki/Maps_examples/Leaflet_map_with_one_point). However I would prefer it working with postal code too.

**Comment by martin-edelmann** [comment]
Hey guys,
sorry for the late response, been out of the country for a couple of days.
Setting the preferences @kghbln gave in his first post and configuring the adress to a place that Nominatim can interpret solved the problem for me.
So I'm closing this issue now. Thanks for the quick help, much appreciated..!
