### ISSUE TITLE
Leaflet does not show popups for shapes

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#443]
https://www.semantic-mediawiki.org/wiki/Extension:Maps/Displaying_maps#Rectangles
https://www.semantic-mediawiki.org/wiki/Extension:Maps/Displaying_maps#Polygons

Also lines:

```
{{#display_map:lines=
  Berlin:Brussels:London;
  Amsterdam:Paris~Amsterdam to Paris line~I am a text~green~0.42~10
| scrollwheelzoom=off
}}
```

**Comment by JeroenDeDauw** [comment]
@PeterTheOne FYI

**Comment by JeroenDeDauw** [comment]
This is kinda weird since the colors and so on are being used :)

**Comment by kghbln** [comment]
[sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/M/443)
