### ISSUE TITLE
Cannot install Maps

### ISSUE THREAD

**Issue by backslash451** [JeroenDeDauw/Maps#45]
Hi all, 
i followed the guide but i cannot get the Maps extension works. Here some data:

* MediaWiki version: 1.20.4
* PHP: 5.3.3

Maps installed with the ExtensionInstaller extension. ExtensionInstaller is correctly listed in the Special:Version page but Maps is not and its tags are not working.

Maps and Validator are correctly downloaded by Composer in the extension\ExtensionInstaller\extensions folder.

Any help will be appreciated. :\

**Comment by JeroenDeDauw** [comment]
Have you gotten this to work?
