### ISSUE TITLE
"imageoverlays" parameter: "text", "title" and "link" options do not work

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#450]
### Setup

- MediaWiki | 1.31.0 (959e09c)18:43, 12 July 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Maps | 5.6 alpha (c435b1a) 18:59, 14 July 2018

### Issue
When specifying values with the "text", "title" and "link"  options to this parameter, they are not working.

### Example
See [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/M/450)

**Comment by JeroenDeDauw** [comment]
```
{{#display_map: 
 |imageoverlays=50.302674198227855,10.70068359375:49.01553629578961,8.382568359375:https://sandbox.semantic-mediawiki.org/w/SMWSandBoxLogo.png~Semantic MediaWiki~World domination imminent!/~link:https://www.semantic-mediawiki.org/
 |centre=Europe
 |zoom=6
 |service=googlemaps3
}}
```

**Comment by kghbln** [comment]
Great. Thanks for the fix which is now live on sandbox! One thing to mention. If you use link you cannot use title and text since the latter would require clicking on the image which immediately links. I  guess this related to the pop-up implementation.

**Comment by JeroenDeDauw** [comment]
Meh. That is how it always worked. You can create a link with wikitext in the popup if you want.

**Comment by kghbln** [comment]
> Meh. That is how it always worked. You can create a link with wikitext in the popup if you want.

No worries. I was not complaining or so - just mentioning. I updated and expanded the [docu.](https://www.semantic-mediawiki.org/w/index.php?title=Maps_examples%2FGoogle_Maps_ground_overlays&type=revision&diff=63762&oldid=63090)
