### ISSUE TITLE
Fatal error when loading Maps

### ISSUE THREAD

**Issue by Nikerabbit** [JeroenDeDauw/Maps#458]
### Setup

- Maps version: 94626367d1682771cb1cf0c526876e4d1d901041 (master)
- MW version: b1289408dff2436f8ed1862111cf5b538ba628e0 (master)
- PHP version: 7.1
- SMW version (if applicable): 

### Issue

```
PHP Fatal error:  Uncaught UnexpectedValueException: callback 'MapsRegistration::onRegistration' is not callable in /www/dev.translatewiki.net/docroot/w/includes/registration/ExtensionRegistry.php:361
```

I think this is because you are not defining autoload entry for the class.

**Comment by JeroenDeDauw** [comment]
There is an autoload entry: https://github.com/JeroenDeDauw/Maps/blob/master/composer.json#L52

This is working for me locally, where as far as I know, I have a normal-style MW setup. So to solve this I'm going to need some more info on how you are loading things.

**Comment by Nikerabbit** [comment]
I mean extension.json. You only have it in composer.json. I don't think it is usually done this way. Anyway, it is no longer happening. I suppose composer got confused by my version requirement `"dev-master#7b113e48bd3c21baf8440953e47945967d97f3e3"` which I have now removed.

**Comment by JeroenDeDauw** [comment]
Perhaps this will help avoid such issues in the future: https://github.com/JeroenDeDauw/Maps/pull/459
