### ISSUE TITLE
Generated URLs are not protocol relative

### ISSUE THREAD

**Issue by Wegge** [JeroenDeDauw/Maps#47]
There are a multitude of hardcoded http://foo.bar.tld links in the extension code and js files. This means that whenever the extension is used on a TLS-secured wiki, any modern browser will warn about mixed security.

I've tried to do a recursive change of all 'http://' strings to just '//', which seem to work, at least for the OpenLayer type of maps. But this is probably too much, as it will also change urls in comments and documentation.

**Comment by kghbln** [comment]
Great! Thanks a ton. @JeroenDeDauw What about doing a 3.2.3?

**Comment by JeroenDeDauw** [comment]
Done. It even has a cool release codename!

**Comment by kghbln** [comment]
Cool and :D For the 4.0 release I envision the code name "another dimension of fluff for kgh"
