### ISSUE TITLE
Precision error when converting coordinates

### ISSUE THREAD

**Issue by Henryfunk** [JeroenDeDauw/Maps#474]
### Setup

- Maps version: 5.1.0
- MW version: 1.20.0
- PHP version: 7.0.30-0ubuntu0.16.04.1 (apache2handler)
- SMW version (if applicable): 2.5.6

### Issue: At my site, when I set properties of type Geographic coordinates, their value isn't stored correctly. For instance [[Geopoint::52.136945,-0.466722]] (where Geopoint is a property of type Geographic coordinates) becomes: 52.136944444444,-0.46666666666667 . 

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

Steps to reproduce the observation:

1) Define the following property: [[has type::Geographic coordinate]][[Display precision of::15]]
2) Set a property in a page (as above): [[Geopoint::52.136945,-0.466722]].

[You can see the behaviour here.](https://www.irhb.org/wiki/index.php/Coordinates_issue)

This is just a thought: I haven't checked how geographical coordinates are stored in Maps/SMW, but if they aren't stored as float, could the error result from incorrect conversion between formats (decimal/decimal minute or decimal/DMS)?

As always, your efforts are much appreciated!

Henrik Thiil NIelsen

**Comment by JeroenDeDauw** [comment]
Not an SMW issue as this happens in the [#coordinates parser function](https://www.semantic-mediawiki.org/wiki/Maps/Coordinates) as well, see https://sandbox.semantic-mediawiki.org/wiki/Maps_coordinate_issue_474

So either something is going wrong during parsing of the coordinates or during formatting them. I suspect the latter.

**Comment by Henryfunk** [comment]
Thanks, Jeroen. I intend to upgrade to Maps 6 anyway. The bug isn't a big problem at my site, but it wouldn't be nice to be onboard a self-driving car with the same bug. I just put a couple of markers in Google Earth: the difference amounts to about 3 meters :-)

Henrik

**Comment by JeroenDeDauw** [comment]
This is an issue with the formatting of coordinates in the library used by Maps. Now tracked by https://github.com/DataValues/Geo/pull/152

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/JeroenDeDauw/Maps/pull/476

**Comment by JeroenDeDauw** [comment]
Fix is in the just released 6.0.2
