### ISSUE TITLE
ReferenceError: "L is not defined"

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#480]
### Setup

- Maps version: 5.6
- MW version: 1.31.1
- PHP version: 7.0.30-0+deb9u1
- SMW version (if applicable): 3.0.0-rc.2

### Issue

I found this while creating the example for #479.

On [this example page](https://sandbox.semantic-mediawiki.org/wiki/Issue/M/480), the maps don't load correctly.
And I get this error in the console:
```
ReferenceError: "L is not defined"
<anonymous> https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=ext.maps.common%2Cleaflet&skin=vector&version=1jnszwn:9:1
runScript https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=0x384ib:162:129
checkCssHandles https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=0x384ib:162:785
execute https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=0x384ib:163:496
implement https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=0x384ib:169:897
<anonymous> https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=ext.maps.common%2Cleaflet&skin=vector&version=1jnszwn:1:333 load.php:177:183
```

I don't know what causes this (but it looks similar to https://github.com/JeroenDeDauw/Maps/issues/321).

Edit: It seems to work again if I remove the `display_map` part and purge the page.

**Comment by JeroenDeDauw** [comment]
Some changes to how the JS is loaded where made in Maps 6.0, so this might be fixed in the latest version already.

**Comment by JeroenDeDauw** [comment]
Can anyone confirm this is still present in Maps 6.x?

**Comment by kghbln** [comment]
Currently it is pretty hard to test since upgrading to Maps 6.x is not possible. :( However this issue is a real pain in the you know what.
