### ISSUE TITLE
Support services other than Google Maps on Special:MapEditor

### ISSUE THREAD

**Issue by jamesmontalvo3** [JeroenDeDauw/Maps#482]
Special:MapEditor not using default leaflet, failing due to lack of Google API key

---

### Setup

- Maps version: 6.0.3
- MW version: 1.31.1
- PHP version: 7.1.22
- SMW version (if applicable): 3.0.0

### Issue

With default settings (only change to `LocalSettings.php` is addition of `wfLoadExtension( 'Maps' );`), Special:MapEditor appears to be trying to use Google maps and fails with the following output:

![image](https://user-images.githubusercontent.com/716482/47053869-9fab1100-d174-11e8-9256-fc7261c26586.png)

Console output is:

> You have exceeded your rate-limit for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
> Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

![image](https://user-images.githubusercontent.com/716482/47053947-fd3f5d80-d174-11e8-9d20-23855dceb638.png)

Usage of `#display_map` appears to be using leaflet, which should be the default I think.

**Comment by JeroenDeDauw** [comment]
At the moment only Google Maps is supported on Special:MapEditor. Changing this is not trivial and I am not planning to do so. Furthermore, I recommend anyone who wants visual editing for other mapping services to consider going down the route of https://github.com/JeroenDeDauw/Maps/issues/447

**Comment by jamesmontalvo3** [comment]
Is there a reason no additional config on Maps 5.x allowed Special:MapEditor to work, but upgrading to 6.x causes the error above?

**Comment by JeroenDeDauw** [comment]
Not that I am aware off. Beware that Google Maps used to work without API key but now no longer does. That is a change on Google Maps side.

**Comment by JeroenDeDauw** [comment]
It is not. If you did not load SRF properly it might have caused an error that prevented Maps from doing its stuff.

**Comment by JeroenDeDauw** [comment]
I'm going to close this as wontfix as I have no intention to poke at the MapEditor and rather see it replaced by a more sustainable and more user friendly solution. Contributions to the MapEditor are still very welcome. It'd be real cool if someone created a Leaflet version.
