### ISSUE TITLE
Support polygon holes in wikitext syntax

### ISSUE THREAD

**Issue by dktue** [JeroenDeDauw/Maps#487]
I would like to draw a polygon with holes on a map. Currently, there seems no way to do so.

**Comment by JeroenDeDauw** [comment]
Maps supports GeoJSON since version 6.0, which I believe can do what you want.

https://www.semantic-mediawiki.org/wiki/Extension:Maps/GeoJSON

**Comment by JeroenDeDauw** [comment]
Does that work for you?

**Comment by dktue** [comment]
It makes the process alot more compliated for me -- it would be easier to extend the syntax to separate the inner rings from each outer ring in the polygons-parameter.

Example (draft):

    polygons=48,9:50,7:49,11|48.5,9.5:49.2:8.6:48.7:10.1

where

    48,9:50,7:49,11

is the outer ring and

    48.5,9.5:49.2:8.6:48.7:10.1

is the inner ring (only one in this case). They are being separated by a pipe.

**Comment by JeroenDeDauw** [comment]
Right ok. A delimiter different than `|` would be needed though, since that one is already used for separating top level parameters.

**Comment by JeroenDeDauw** [comment]
I'm curious what you find complicated about using GeoJSON. At present I am not planning to extend the wikitext syntax because my thinking is that it is better to use the GeoJSON standard. If someone implements this in wikitext I will be happy to review it though.

**Comment by dktue** [comment]
I would love to use GeoJSON but unfortunately it doesn't support popups at the moment.

**Comment by JeroenDeDauw** [comment]
Ah yes. I created an issue for that so it is tracked now: https://github.com/JeroenDeDauw/Maps/issues/514

**Comment by JeroenDeDauw** [comment]
Will not extend the wikitext in the foreseeable future
