### ISSUE TITLE
numerous issues

### ISSUE THREAD

**Issue by acnetj** [JeroenDeDauw/Maps#488]
My wiki (transit.wiki) hasn't upgraded the system in 4 years due to change in functionality of the Maps and other related extensions. I recently upgraded the system so that I can use a responsive skin, which is a huge benefit, despite the loss of functionalities since the refactoring from version 2.x.

May be these issues could be address in future versions, or that I may have to find alternate solutions (iframe to other mapping application).

- Lost of ability to put additional lines and points (following the method to put values as in display_map) after a map query. 

{{#ask:[[Served by::Rail Runner Express]]|?-Rail=Bus|?latlong|format=googlemaps|icon=Rail20.png|width=100%|height=100%|limit=500|gkml=|lines={{#show: {{PAGENAME}}| ?line|sep=;}}}}

I could save lines as semantic objects and query them before. That way I can show multiple lines on one map but in different colors and thickness.

- #Display_map now requires the last (;) to be removed or otherwise nothing will show. The old version didn't require that. This complicates efforts to import the lines (via the command above or some other ways including external data) because these commands will result in an extra (;) that cannot to easily eliminated but which display_map requires.

- #Display_map marker popup have a much smaller space then what the old version allowed. The old version allowed external lines. Now the field is much shorter and less useful.

{{#ask: [[-Place::{{BASEPAGENAME}}]]|?latlong|format=googlemaps|width=100%|height=100%|icon=mm_20_red.png
|locations={{#for_external_table:
{{{latitude}}},{{{longitude}}}~{{{displayname}}}~{{{to}}}<br>Stop id: {{#if:{{{511|}}}|[{{SERVER}}/511_Departure_times?id={{{id}}}&agency=511 {{{id}}} (real time departures)]|{{#ifeq:{{{agency}}}|sacrt|{{{id}}} - [http://bustime.sacrt.com/bustime/eta/eta.jsp?id={{{id}}} Desktop], [http://m.sacrt.com/bdetails.aspx?stpid={{{id}}} Mobile]|{{{id}}}}}}}~File:Bus20.png;
}}

- Custom markers now require exact file location (File:XXX.png) no longer good.
  
I held out upgrading for years due to those deficiencies. High Google Maps pricing and responsive skin pushed me to upgrade. While I've always expected some functions to break, I have to find what they are as I try to find alternate ways to address it. (such as putting a query into #display_map like this: {{#display_map:{{#ask:[[Category:Bay Area toll bridges]] [[latlong::37.818, -122.362 (100 miles)]]|?points=|mainlabel=-|format=list|sep=;}}|width=100%|height=100%|layers=traffic|service=googlemaps}} Ironically the #ask query doesn't produce an extra ; at the end, which allowed the query to be displayed this way, but no external data).

**Comment by JeroenDeDauw** [comment]
Thanks for reporting. I created dedicated issues (auto-linked above). Please create an extra one if I missed something.
