### ISSUE TITLE
Problems with tag extension

### ISSUE THREAD

**Issue by Nick2253** [JeroenDeDauw/Maps#49]
I'm getting issues with the tag extension.  Sometimes the points aren't rendered correctly, whereas the parser function works reliably.

For example: https://semantic-mediawiki.org/wiki/Maps_examples/Point_specific_data

The first and last maps don't show any of the points, which seams to be due to the "Mali|Mali||File:Blue marker.png" line.  However, even without that line, none of the pop-ups on click work.

The middle map works correctly (minus the File: issue) with the parser function.

There are various other examples in the Maps examples that display defective tag behavior (especially defective pop-up behavior), such as:  https://semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_tag_and_autoinfowindows

**Comment by JeroenDeDauw** [comment]
Is this still an issue with the most recent version of Maps?

**Comment by kghbln** [comment]
Yes as the [example](For example: https://semantic-mediawiki.org/wiki/Maps_examples/Point_specific_data) shows.

**Comment by PeterTheOne** [comment]
May this be somewhat related to #50?

> Could it be that $separator = '~'; https://github.com/JeroenDeDauw/Maps/blob/master/includes/parsers/LocationParser.php#L37 is just not the same separator than what is used in the example above:

**Comment by kghbln** [comment]
Indeed, I just [fluffed the examples](https://www.semantic-mediawiki.org/w/index.php?title=Maps_examples%2FPoint_specific_data&type=revision&diff=44158&oldid=43511) and things start to show up again.

> The middle map works correctly (minus the File: issue) with the parser function.

The file issue is still open and tracked with https://github.com/JeroenDeDauw/Maps/issues/51

**Comment by kghbln** [comment]
Apparently I added [more fluff](https://www.semantic-mediawiki.org/w/index.php?title=Maps_examples%2FGoogle_Maps_with_point_specific_data&type=revision&diff=44180&oldid=44159) to the examples.
