### ISSUE TITLE
Filter/Searching does not find points

### ISSUE THREAD

**Issue by Nick2253** [JeroenDeDauw/Maps#50]
Using the searchmarkers parameter show a "Filter markers" box in the upper right as expected, but typing anything in that box does not find any markers.

For example, see https://semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_searchmarkers 

The suggested search terms of "capital of" and "city" return nothing.  My experiments can find no search term that matches any of the filters.  I've tried direct copy-and-paste from the points' titles and descriptions, such as "Norway", "Meanwhile in Norway", "Capital of the United Kingdom", etc., and nothing is found.

The same result is found on OpenLayer searches:  https://semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_searchmarkers

The same result is found using either the tags or the parser function.

**Comment by Nick2253** [comment]
Has there been any progress on this issue?  We are currently using Maps to display the current location of all of our mobile units around the country (around 400 points), and filtering would extremely helpful to quickly identify the desired point.

**Comment by JeroenDeDauw** [comment]
I'm afraid not, and am not able to get to this myself. This should be easy enough to fix though, so perhaps you can get someone to do it?

**Comment by PeterTheOne** [comment]
I would expect the bug to be somewhere in this https://github.com/JeroenDeDauw/Maps/blob/637e120d81681ed71646ddeb2e85cb9be2ef06d4/includes/services/GoogleMaps3/jquery.googlemap.js#L644 function that does the search, but I haven't really looked into it.

**Comment by PeterTheOne** [comment]
Ok, I was wrong suspecting the bug in the javascript code. The `mapdata` json is missing `title` and `text`! It gets lost in the process of geocoding. I propose to preserve the original string in `LocationParser` or `Geocoders` or alternatively grab the Address from the geocoding API. @JeroenDeDauw What do you think?

**Comment by JeroenDeDauw** [comment]
Can you point me to the location of where the call is made that causes loss of this information?

**Comment by PeterTheOne** [comment]
https://github.com/JeroenDeDauw/Maps/blob/master/includes/parsers/LocationParser.php#L108 I think geocoder only returns coordinates here..

**Comment by JeroenDeDauw** [comment]
Code was slightly misleading, improved by https://github.com/JeroenDeDauw/Maps/pull/154

That method always returns a LatLongValue, which just has a lat and a long. It's only caller is `stringParse` in the same class, which constructs a `Location` object with it. `Location` contains title and whatnot, and `stringParse` is using its setters to set those values from the `$metaData` it got.

**Comment by PeterTheOne** [comment]
Ok. I think if there is no title https://github.com/JeroenDeDauw/Maps/blob/master/includes/parsers/LocationParser.php#L51 then it should be set to what is used for geocoding  https://github.com/JeroenDeDauw/Maps/blob/master/includes/parsers/LocationParser.php#L41 .

**Comment by PeterTheOne** [comment]
Could it be that `$separator = '~';` https://github.com/JeroenDeDauw/Maps/blob/master/includes/parsers/LocationParser.php#L37 is just not the same separator than what is used in the example above:

    <display_map searchmarkers="all">
    New York City|New York City|Home of the great Yaron Koren
    Brussels|Brussels|Capital of Belgium
    Berlin|Berlin (city)|Capital of Germany
    London|London|Capital of the United Kingdom
    Norway|Norway|Meanwhile in Norway
    </display_map>

**Comment by JeroenDeDauw** [comment]
Sounds good. You'd need to distinguish between the case in which the first part are coordinates and the first part being something that gets geocoded. Seems like that info is hidden in Geocoders::attemptToGeocode. The `Geocoders` "class" is extremely foobar though... Injecting the proper services into the LocaltionParser would be nice, though looks like an at least moderate difficult refactor.

**Comment by JeroenDeDauw** [comment]
That example looks wrong to me. `|` is the separator between top level parameters, while the `title` stuff is another part of a single parameter (of even a part of one, as we're dealing with a list of coordinates). I'm quite fuzzy on that tho. @kghbln ought to know better

**Comment by PeterTheOne** [comment]
Works here like this: http://sandbox.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_searchmarkers

**Comment by PeterTheOne** [comment]
I vote for changing the example and closing this issue.

**Comment by kghbln** [comment]
Yeah, the example seems to be wrong. As soon as one switches from "|" to "~" things are fluffy as @PeterTheOne showed. I wonder who [documented this in the first place?](https://www.semantic-mediawiki.org/w/index.php?title=Maps_examples/Google_Maps_searchmarkers&action=history) -*- ducking away -*-

**Comment by Nick2253** [comment]
I'm still seeing this issue on my internal wiki, even with the "~".  I'm using the parser function and lat/long if it makes a difference.

**Comment by kghbln** [comment]
@Nick2253 Could you set up an example at the [sandbox wiki](http://sandbox.semantic-mediawiki.org/)?

**Comment by Nick2253** [comment]
Happy to.  Just waiting on my account confirmation, and then I'll put up an example.

**Comment by Nick2253** [comment]
See here for an example: http://sandbox.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_searchmarkers_2

**Comment by JeroenDeDauw** [comment]
> I wonder who documented this in the first place? -- ducking away --

Hey! I might have copied that from the old wiki without looking at it or something like that :)

**Comment by JeroenDeDauw** [comment]
I've quickly poked a bit at what @PeterTheOne mentioned earlier. Not sure if that actually fixes this issue or is an unrelated enhancement. https://github.com/JeroenDeDauw/Maps/pull/155

**Comment by PeterTheOne** [comment]
I added a second map to http://sandbox.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_searchmarkers_2 , the search works there. (But somehow two points are missing...)

**Comment by PeterTheOne** [comment]
Ah, I found what was wrong with the first map: It had `| searchmarkers="all"` instead of `| searchmarkers=all`.

**Comment by PeterTheOne** [comment]
A flaw of searchmarkers is that it doesn't have a default/fallback https://github.com/JeroenDeDauw/Maps/blob/637e120d81681ed71646ddeb2e85cb9be2ef06d4/includes/services/GoogleMaps3/jquery.googlemap.js#L652 if you type anything else than `all` or `title`.

**Comment by Nick2253** [comment]
@PeterTheOne That fixed the problem for me on my internal wiki as well.

That's probably what did it to me:  I simply copy-pasta'd the `searchmarkers="all"` from the other syntax.  I would also agree with Peter that either adding a fallback for `"all"` would help ease confusion, or at least show an error.

**Comment by JeroenDeDauw** [comment]
I concur the current behavior is wrong. Either you should get an error, you should get a default searching behavior, or the search thing should simply not be enabled. Broken search, with no error, makes no sense. I have no real preference in which solution is used.

**Comment by kghbln** [comment]
Well the underlying issue here was also missing or outdated documentation. I just fluffed the docu [for this option](https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_with_searchmarkers) using @PeterTheOne's examples from the sandbox  to avoid issues from that side too.

Some time ago I gradually started working on the Maps related docu to extend it to provide examples for the tag as well as the parser function as well as making their appearance more consistant. Since I hardly use Maps I have so far only done the most important features from my point of view.

**Comment by JeroenDeDauw** [comment]
> Since I hardly use Maps

I searched for "heretic bunny". Got some real weird stuff

![hereticbunny](https://cloud.githubusercontent.com/assets/146040/15617284/8a327222-2448-11e6-8065-1c4aa98608e9.jpg)
