### ISSUE TITLE
Marker custom icon doesn't work

### ISSUE THREAD

**Issue by Nick2253** [JeroenDeDauw/Maps#51]
Setting a marker custom icon doesn't work.  See:

http://semantic-mediawiki.org/wiki/Maps_examples/Point_specific_data

However, setting a whole-map custom marker does work.  See:

http://semantic-mediawiki.org/wiki/Maps_examples/Map_properties

**Comment by JeroenDeDauw** [comment]
Just looked at this for half an hour. Seems like my MediaWiki is behaving broken. Not sure if it's my install or MediaWiki itself. Send a mail to wikitech...

**Comment by JeroenDeDauw** [comment]
Also reported at https://www.mediawiki.org/wiki/Thread:Extension_talk:Maps/Maps_3.2.2_-_Custom_Markers_Not_Displayed

**Comment by kghbln** [comment]
Yeah, one can either add the maker via an external URL like ```https://www.semantic-mediawiki.org/w/images/c/ce/Green_marker.png``` or one can add just ```Green_marker.png```. Maps 2.x supported ```File:Green_marker.png``` instead of ```Green_marker.png``` as Maps 3.x does. So should there something be done about it?

**Comment by PeterTheOne** [comment]
Maybe stripping "`File:`" in `MapsMapper::getFileUrl( $file )` https://github.com/JeroenDeDauw/Maps/blob/9bd76bdaf2be0234fae2d407ea007b702d52fd91/includes/Maps_Mapper.php#L136 would do the trick?

**Comment by kghbln** [comment]
The examples now reflect the current situation [without namespace prefix](https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_with_point_specific_data). Once this issue is closed the example page must be worked on. The example containing the namespace prefix is already on the page but hidden via commentary.

> Maybe stripping "File:" in `MapsMapper::getFileUrl( $file )`

@JeroenDeDauw We are now in the situation that the workaround was necessary for two years. Thus it will be best to support both - icons with and without namespace prefix to avoid breakage.

**Comment by JeroenDeDauw** [comment]
Yeah sure, let's definitely not ditch the only thing that worked during the last two years. 

> Maybe stripping "File:" in MapsMapper::getFileUrl( $file )

sure

**Comment by Nick2253** [comment]
If I may suggest an alternative:

What about making the expected behavior to have the "File:" prefix, and you add it if a namespace-style prefix isn't present.  The reason I bring this up is it is possible to change the "File" namespace prefix, or to add a different namespace, so it probably isn't always the best to assume that the icon is in the "File" namespace.  By just adding "File:" to those icons that don't have a namespace, you allow more flexibility in the configuration by explicitly specifying a namespace.

**Comment by kghbln** [comment]
> isn't always the best to assume that the icon is in the "File"

I do not think that it is possible to upload a file to a different namespace. Actually never tried it but I currently do not see any reason to do so.

**Comment by Nick2253** [comment]
@kghbln We do it right now in our corporate wiki.  Depending on the purpose of the file, we use the different namespaces to provide rudimentary CMS capability, because it's much easier to segregate a wiki by namespace than it is by article (it solves many of the "search" work-arounds).

In this case, we'd have no problems uploading the files to the "File" namespace because that would be the most public.  However, I can definitely contrive a scenario where this wouldn't be the case, and I suggested is simply because, if you have to fix it, might as well do it in such a way that works for the most generic case.

**Comment by kghbln** [comment]
Oh, interesting. Never thought of this however if I remember correctly the NSFileRepo extension allows something similar. So I could have guessed.

**Comment by PeterTheOne** [comment]
Can we bring this discussion to some conclusion? ;)

**Comment by kghbln** [comment]
> Can we bring this discussion to some conclusion? ;)

@JeroenDeDauw I am in favour for a fix as it appears most suitable to you.

**Comment by JeroenDeDauw** [comment]
If someone makes the thing less broken (without breaking what currently works) I'm all for it

**Comment by JeroenDeDauw** [comment]
Maps 5.5.1 using Leaflet:

![image](https://user-images.githubusercontent.com/146040/42297726-c29a2a6c-8001-11e8-965b-f24a57d03995.png)
