### ISSUE TITLE
Maps 7.0

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#511]
* [x] Remove OpenLayers - [close issues](https://github.com/JeroenDeDauw/Maps/issues?q=is%3Aissue+is%3Aopen+label%3AOpenLayers) - [possible blocker](https://github.com/JeroenDeDauw/Maps/issues/510)
* [x] Improve [settings loading](https://github.com/Wikia/Maps/commit/acc01d6a609303affec50781ceaa816aa65ab625)

**Comment by kghbln** [comment]
I believe this is done. :)
