### ISSUE TITLE
Two google maps won't show

### ISSUE THREAD

**Issue by acnetj** [JeroenDeDauw/Maps#519]
See here:
https://www.transit.wiki/Sandbox_3

Top: leaflet, bottom: google = top leaflet no show, bottom google shows
Top: google, bottom: leaflet = top google no show, bottom leaflet shows
Top and bottom leaflet = both leaflet maps show
Top and bottom google = both google maps no show

openlayers behave like leaflet. If both are openlayers then both will show, if they're different only bottom shows.

---

Overall this version basically restored the functions v2 had so thanks for your attention to the issues.

**Comment by JeroenDeDauw** [comment]
Reported using Maps 6.2.1

---

I cannot reproduce this, see below screenshots.

![image](https://user-images.githubusercontent.com/146040/49058831-0b69aa80-f206-11e8-8a30-7609f3a1a53f.png)
![image](https://user-images.githubusercontent.com/146040/49058834-17ee0300-f206-11e8-9af9-31d68e2f94b8.png)
![image](https://user-images.githubusercontent.com/146040/49058879-3e13a300-f206-11e8-86fb-a15fb3ace60d.png)

---

There are some image path issues in 6.2.1 that I just fixed. So perhaps 6.2.2 will fix the issue for you.

**Comment by acnetj** [comment]
What I found that the issue occurs when the parameter string '~' is used on map other than the first one. ~ is used to separate the marker info from the coordinates.

It doesn't appear to happen if it is just used on the display_map, but happened with #ask query with locations parameter. If there's a display_map on top all maps will show but if there's a display_map below then some if not all the display_map will show.

**Comment by JeroenDeDauw** [comment]
Are you missing at "not" at the end there?

**Comment by JeroenDeDauw** [comment]
Minimal wikitext to reproduce the issue would be really helpful

**Comment by acnetj** [comment]
No. In that case (ask query with ~ and display_map below). Some maps show and some not.

{{#ask: [[-Place::14-Mission]]|?latlong|format=googlemaps
|locations=37.744693, -122.426165~
}}

{{#ask: [[-Place::14-Mission]]|?latlong|format=googlemaps
|locations=37.744693, -122.426165~
}}

**Comment by JeroenDeDauw** [comment]
During the last two year several improvements where made around map loading. I doubt this issue still exists.
