### ISSUE TITLE
Add caching for GeoJSON

### ISSUE THREAD

**Issue by dktue** [JeroenDeDauw/Maps#525]
It would be helpful to have a caching-option for GeoJSON. The extension would then cache the data and not query the source again until the cache expired.

Suggestion
----

    {{#display_map: | geojson=http://example.com/geometries.php | geojsoncacheduration=86400 }}

**Comment by JeroenDeDauw** [comment]
Beware that you can save the GeoJSON in a page in the GeoJSON namespace and thus avoid any web requests from being made. This does not work for all use cases though might just be what you need.

**Comment by JeroenDeDauw** [comment]
Wat exactly is the problem you are running into? Is the rendering of the page too slow? Can you only make a limited amount of web requests?

**Comment by JeroenDeDauw** [comment]
I am hesitant to create a cache parameter. Would having a setting (that goes into LocalSettings.php) that applies to all GeoJSON file web requests work well for you?

**Comment by JeroenDeDauw** [comment]
Should be done with https://github.com/JeroenDeDauw/Maps/commit/c1ff874a3f96b2d64f02f5bf9bcd560047ae3e6e. Would be amazing if you could test this.

**Comment by JeroenDeDauw** [comment]
This functionality is part of the now released Maps 7.0.

@dktue is it working for you?
