### ISSUE TITLE
Title in Specialpages Category misformatted

### ISSUE THREAD

**Issue by anipp100** [JeroenDeDauw/Maps#526]
### Setup

- Maps version: 6.3
- MW version: 1.31.1
- PHP version: 7.2.10 (cgi-fcgi)
- SMW version (if applicable): no

### Issue

I installed Maps today via composer.
On the specialpages-Page I find the Mapeditor under the category: "⧼specialpages-group-Maps⧽", literally. There should be a translation from the constant "specialpages-group-maps" to "Maps" instead, i suppose.

**Comment by JeroenDeDauw** [comment]
Thanks for reporting the issue! I will have a look at it tomorrow

**Comment by JeroenDeDauw** [comment]
Fixed on master now. Fix will be part of 7.0.0
