### ISSUE TITLE
Add API key for Thunderforest Leaflet layers

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#529]
### Setup

- Maps version: 6.3.0 and later (earlier versions affected too but are no longer supported)

### Issue

Maps indeed allows to use the Thunderforest services in general [DefaultSettings.php](https://github.com/JeroenDeDauw/Maps/blob/cd9854ce91417cf6542751b28a69295163684db4/DefaultSettings.php#L169) however they require an API key. See [Thunderforest API Keys documentation](http://www.thunderforest.com/docs/apikeys/)

**Comment by JeroenDeDauw** [comment]
https://github.com/JeroenDeDauw/Maps/blob/cd9854ce91417cf6542751b28a69295163684db4/DefaultSettings.php#L250-L255

![image](https://user-images.githubusercontent.com/146040/50047391-2d8f7380-00b4-11e9-9313-62d0a0ef99e3.png)

**Comment by kghbln** [comment]
OMG, yeah. Senior moments again.
