### ISSUE TITLE
Map does not show when maker count gets to big

### ISSUE THREAD

**Issue by davecotter** [JeroenDeDauw/Maps#53]
Can the problem be viewed online in a public wiki? (If yes, provide its URL.)
https://karaoke.kjams.com/wiki/Map/Test

    Which versions of the relevant extension(s) was/were used?
current / latest

    Which version of MediaWiki was used?
current

    Which server setup was used (PHP, MySQL, OS)?
MySQL i think, and MacOS

    Can the problem be reproduced on another wiki (like this one)? (If yes, provide its URL.)
probably, haven't tried

**Comment by davecotter** [comment]
this problem seems to be resolved, feel free to close it

**Comment by kghbln** [comment]
Great that it now works with recent Maps! Thanks for the feedback. Yeah, discussing if is an enhancement or bug leads to nowhere. That's just sucking energy which could have gone into fixing or enhancing or whatever.

**Comment by davecotter** [comment]
i understand.  i just know from experience that getting something labeled as "bug" or "data loss" gives it a much higher priority than something labeled as "performance" or "feature request" :)
