### ISSUE TITLE
Marker and Fullscreen Icon not loaded

### ISSUE THREAD

**Issue by m-art-in** [JeroenDeDauw/Maps#538]
### Setup

MediaWiki 1.31.1
PHP 7.2.5 (apache2handler)
MariaDB 10.2.15-MariaDB
ICU 60.2
Elasticsearch 6.5.4
Maps 7.1.0

### Issue
If I enable fullscreen, the Icon is not loaded:
![image](https://user-images.githubusercontent.com/15324884/52716602-6908ca00-2f9f-11e9-85b2-93152dc77db0.png)

my wiki is inside a subdirectory and Maps looks for the fullscreen-icon here:
MYSERVER-IP/smw/extensions/resources/leaflet/leaflet.fullscreen/icon-fullscreen.png

but it's there:
MYSERVER-IP/smw/extensions/Maps/resources/leaflet/leaflet.fullscreen/icon-fullscreen.png

So somewhere "Maps/" is missing.

Similar with the markers. Maps expects it here:
MYSERVER-IP/smw/images/marker-icon.png

but it's there:
MYSERVER-IP/smw/extensions/Maps/resources/leaflet/leaflet/images/marker-icon.png

So the root-path to the Maps-Extension is not set. Maybe a config-error on my side?

**Comment by JeroenDeDauw** [comment]
Did this work with a previous version of Maps? And do you know if this problem also happens with Google Maps?

**Comment by m-art-in** [comment]
I had the bug with missing Icon in Maps 5.x., then there was a fix (Sorry I don't know the excat Version) und with 7.1.0 it's there again.
With Googlemaps and MapsExtension 7.0.1. the Markers are fine. Only leaftet service has this Issue.

**Comment by m-art-in** [comment]
Short Addition:
In the Sandbox-SMW which runs Maps 5.6  the Icon is there:
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Zym#map

**Comment by JeroenDeDauw** [comment]
Can you try if this change fixes the issue for you? https://github.com/JeroenDeDauw/Maps/commit/59da6cc497b137ce18b368ef198b7eebcb6b1617

**Comment by m-art-in** [comment]
Thanks for the fix, unfortunatly no change: The full screen icon is still missing with 404 Error

**Comment by JeroenDeDauw** [comment]
I've just released my recent changes as version 7.2.0. If that still does not work, then idk what the issue could be. Maps is doing what other extensions are also doing. So maybe it is your config that is wrong or maybe some MW magic I don't know about. Either way, asking on the wikitech mailing list might help. Please let me know if you find out something is wrong in the extension (I am not on that list).

**Comment by JeroenDeDauw** [comment]
The sandbox is now running 7.2 and the icon is showing:

![image](https://user-images.githubusercontent.com/146040/57010703-6745be80-6bfe-11e9-9026-0cf9f6c80e5a.png)

**Comment by JeroenDeDauw** [comment]
Do you have Maps or your extensions installed in some non-standard location?

**Comment by m-art-in** [comment]
Ok, when it's fine in the sandbox maybe somethin with my server and installation went wrong. I installed it on a wiki farm in subfolders. I have to investigate. So I close this issue.
Thank you

**Comment by kghbln** [comment]
I believe this is some borked CSS which is being inherited from Leaflet. See [this page](https://www.semantic-mediawiki.org/wiki/SMWCon_Fall_2019) The controls only show on hover.
