### ISSUE TITLE
Map covering Timeless skin

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#546]
Maps 7.3

Martin Brunner wrote:

> Using the latest MW LTS with latest SMW and Maps 7.3 we have the problem that
the map is covering elements from the drop down menu.
Also it is covering the menu and search bar, see https://imgur.com/a/VfXvuzr

> Is this a known issue? Is it a problem of the skin or of maps?

**Comment by kghbln** [comment]
This does not look like the Modern skin but like the Timeless skin.

**Comment by Flexmaen** [comment]
Ah yes, it's the Timeless skin, not Modern skin.

**Comment by s7eph4n** [comment]
The map is likely using a high z-index without having a proper stacking context to contain it. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

Solution: Create a stacking context on the root element of the map widget.

**Comment by s7eph4n** [comment]
Looks like the map has a high z-index without a proper stacking context to contain it. See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by JeroenDeDauw** [comment]
Is there a live example of this somewhere?

**Comment by JeroenDeDauw** [comment]
Not happening for all skins... 
![image](https://user-images.githubusercontent.com/146040/61177557-e715df00-a5d8-11e9-8d17-10f7f2164d94.png)

Maybe the mentioned skin is just doing it wrong? Really need a working example of the issue to fix.

**Comment by kghbln** [comment]
[Sandbox provides Timeless running REL1_33](https://sandbox.semantic-mediawiki.org/w/index.php?title=Leaflet_static&useskin=timeless) and it works for me.

**Comment by Flexmaen** [comment]
> Is there a live example of this somewhere?

Yes, at http://www.housetrails.org

So its a fault of the skin?

**Comment by JeroenDeDauw** [comment]
I'm not seeing the issue there. This is what I get:

![image](https://user-images.githubusercontent.com/146040/61714172-7a2de200-ad5a-11e9-8bad-05107144db88.png)

**Comment by Flexmaen** [comment]
On a phone it seems to work, but please try on a real computer.

There I get results like these:
![housetrails_screenshot](https://user-images.githubusercontent.com/6330276/61753437-97d96680-adaf-11e9-9e49-3aa2cfbd197c.png)
![housetrails_screenshot2](https://user-images.githubusercontent.com/6330276/61753444-9d36b100-adaf-11e9-9b1b-23e2e96c6bf8.png)

I also tried browsers without plugins and on a computer with no special setup.

**Comment by kghbln** [comment]
I am pretty sure that it is the skin causing the issue. On sandbox using a real computer [there is no issue](https://sandbox.semantic-mediawiki.org/w/index.php?title=Timeless_mess&useskin=timeless) when using REL1_33. So this was fixed in Timeless.

**Comment by JeroenDeDauw** [comment]
My screenshot was on my desktop PC which is now feeling insulted :)

**Comment by Flexmaen** [comment]
> My screenshot was on my desktop PC which is now feeling insulted :)

Ooops, sorry. ;)
Strange that there are different results on other computers, but this seems to be a skin issue.
