### ISSUE TITLE
Missing GeoPolygonValue DataValues, upgrade from SemanticMaps to Maps

### ISSUE THREAD

**Issue by rijvirajib** [JeroenDeDauw/Maps#548]
### Setup
- Maps version: ~7.1
- MW version: 1.31 LTS
- PHP version: PHP 7.2.14
- SMW version (if applicable): ~3.0

### Issue
Possibly related to #239 .

Upgrading from MediaWiki LTS 1.27 to LTS 1.31.
`SemanticMaps` has been merged into `Maps` (as per the docs).

I have an extension that uses `Geometry` and `PolygonValues`. It used to be that Maps had `Maps\Semantic\DataValues\GeoPolygonValue` but this has been removed. Is there any documentation on how to migrate from SemanticMaps to Maps ~7.0.0 and use GeoPolygonValue?

I extend CoordinateValue and PolygonValue for some datatypes:
```
       public static function spgfInitGeoDataTypes() {
		SMW\DataTypeRegistry::getInstance()->registerDatatype(
			'_geo',
			PostGISPointValue::class,
			SMWDataItem::TYPE_GEO
		);
		SMW\DataTypeRegistry::getInstance()->registerDatatype(
			'_gpo',
			PostGISPolygonValue::class,
			SMWDataItem::TYPE_BLOB
		);
		SMW\DataTypeRegistry::getInstance()->registerDatatype(
			'_gmy',
			PostGISPolygonValue::class,
			SMWDataItem::TYPE_BLOB
		);
		return true;
	}
```

**Comment by JeroenDeDauw** [comment]
This code was removed because the features that used it where broken for over 2 years without anyone complaining. Both the code and features are not present in the latest version of Maps so there is no migration path.

You can just copy the code you are using from the old version of Maps / Semantic Maps.

**Comment by rijvirajib** [comment]
Can confirm that copying the old files seem to work. Thank you!
