### ISSUE TITLE
Maps no longer showing infowindow

### ISSUE THREAD

**Issue by OBondarenko** [JeroenDeDauw/Maps#55]
I'm returning to the already known issue "Maps no longer showing infowindow" (e.g. see http://goo.gl/nQ3HaF).

I found this issue neither resolved nor patched. Moreover, I've found the issue inconsistent, namely:
1) infowindow is not working
`<display_points type="terrain">`
`Amsterdam`
`Berlin|This is Berlin`
`London|London|The capital of [[England]].`
`Ghent|Ghent|Most awesome city in Europe|Green marker.png`
`</display_points>`

1) but infowindow is working
`{{#display_map:`
`Moscow, Russia~Moscow~A city in Russia;`
`New York~New York city;`
`London~[[London]]~Capital of England~File:Green marker.png;`
`Brussels;`
`Mali~Mali~~File:Blue marker.png`
`}}`

These results were obtained for the following options:
Product			Version
* MediaWiki		1.23.6
* PHP				5.3.29 (cgi-fcgi)
* MySQL			5.1.72-cll-lve
* Semantic Bundle	1.9.2
* Maps			3.0.1
* Validator			1.0.0.1

I'd be grateful for an answer about resolving this issue.

**Comment by JeroenDeDauw** [comment]
Is this still an issue with the most recent version of Maps?
