### ISSUE TITLE
Class 'Maps\MediaWiki\Api\Geocode' not found

### ISSUE THREAD

**Issue by paladox** [JeroenDeDauw/Maps#552]
### Setup

- Maps version: 7.3.1
- MW version: 1.33.0
- PHP version: 7.2.19
- SMW version (if applicable): none

### Issue

Hi, we are seeing this "/w/api.php   Error from line 200 of /srv/mediawiki/w/includes/api/ApiModuleManager.php: Class 'Maps\MediaWiki\Api\Geocode' not found"

**Comment by JeroenDeDauw** [comment]
Thanks for reporting and attempting to fix! Will fix later

**Comment by JeroenDeDauw** [comment]
@paladox what are you using the geocode API for?

**Comment by paladox** [comment]
@JeroenDeDauw  I’m not using it, I saw the extension cause the api to throw an exception (e.g on /w/api.php) and also saw it in the logs for the other wikis.

**Comment by JeroenDeDauw** [comment]
Alright. I will just remove it for now, as it was broken in at least one other way as well and I don't know anyone that uses it. Will re-add if users announce themselves on wikitech-l.
