### ISSUE TITLE
Hint against `IDatabase` instead of `DatabaseBase`

### ISSUE THREAD

**Issue by mwjames** [JeroenDeDauw/Maps#557]
Various efforts  in MW [0] are underway to remove direct references to `DatabaseBase` which is replaced by `DBConnRef` and implements the `IDatabase` interface therefore it is suggested to change related types in Maps accordingly.

`IDatabse` should be MW 1.31 safe [1].

https://github.com/JeroenDeDauw/Maps/blob/30ebcd0e7442b9c1335cc001a07784fd7e85eeef/src/SemanticMW/ValueDescriptions/CoordinateDescription.php#L37-L39

[0] https://github.com/wikimedia/mediawiki/search?q=getConnectionRef&type=Commits
[1] https://github.com/wikimedia/mediawiki/blob/REL1_31/includes/libs/rdbms/database/IDatabase.php

**Comment by JeroenDeDauw** [comment]
Thanks - I created a PR with that change. Might be problems with the type not matching that in SMW since this method is implementing one from the base class...
