### ISSUE TITLE
$egMapsMapHeight seems to be ignored

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#567]
### Setup

- Maps version: 7.4.1
- MW version:1.31
- PHP version: 7
- SMW version (if applicable): 

### Issue

setting of 
`$egMapsMapHeight = 500;`
in Localsettings.php seems to have no effect.

Neither does 
$egMapsMapWidth = 300;

**Comment by JeroenDeDauw** [comment]
Are you using PHP 7.0? Or 7.somethingHigher?

**Comment by JeroenDeDauw** [comment]
You are probably #DoingItWrong :)

```php
wfLoadExtensions( [ 'ParserFunctions', 'Maps', 'SemanticMediaWiki' ] );

require_once __DIR__ . '/extensions/Maps/Maps_Settings.php';
$egMapsMapHeight = 600;
```

That order, and the require_once line is ... required.

https://www.semantic-mediawiki.org/wiki/Maps/Configuration

**Comment by krabina** [comment]
oops. Indeed, I had
`require_once __DIR__ . '/extensions/Maps/DefaultSettings.php';
instead of Maps_Settings.php
Thank you. 
I also changed the order, becaus I usually load SMW first and then everything else. Did not know that Maps should be loaded before SMW...

**Comment by JeroenDeDauw** [comment]
> I also changed the order, becaus I usually load SMW first and then everything else. Did not know that Maps should be loaded before SMW...

That does not matter. Should have removed non-maps extensions from my example. My bad
