### ISSUE TITLE
add clicktarget parameter

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#578]
### Feature request

Similar to the eventcalendar format, it would be great to have a [clicktarget](https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/200) parameter to be able to specify a form to input a new page that should be added given the coordinates where the user clicked.

A simple use case: People are entering data via page forms and a map display is presented showing every entry. If users now had the possililty to look around on the map, zoom in and then select a point where they would like to make another entry, the clicktarget parameter could be used to send the coordinates to a designated page form for editing a new entry with these coordinates.

**Comment by JeroenDeDauw** [comment]
Is this about existing markers on the map or about placing new markers via the visual editor?

**Comment by krabina** [comment]
About placing new markers without visual editor.  Just as you can click on an eventcalendar display on another day and create a new event, you could click somehwere on the map and be directed to a page form.

**Comment by JeroenDeDauw** [comment]
At the moment you can have a popup for the markers that contains a link. You want that the marker directly links to some page right?

And I suppose you want to get the link target from some semantic property?

**Comment by krabina** [comment]
I want on a map that displays results from an ask query to be able to click (or double-click) on a place where there is no marker and via clicktarget direct this click to a page forms where I can create a new page with coordinates passed on from the map click. Thereford the users can add a new entry based on an exact map position...

**Comment by JeroenDeDauw** [comment]
Aha. So this is not about clicking on markers at all.

The only thing dynamic about the target is the coordinates?

**Comment by JeroenDeDauw** [comment]
I thought initially you where talking about something like https://github.com/JeroenDeDauw/Maps/issues/579, which apparently was never implement for Leaflet o_O

**Comment by krabina** [comment]
Well the page name to be created as well, but this feature is also not availalbel in the clicktarget for the eventcalendar format...

**Comment by JeroenDeDauw** [comment]
Where would the name of the page come from?

**Comment by krabina** [comment]
Well this seems to be a problem.  Currently, in eventline it creates a page with an ID, because users are not asked for a pagename. You can see it here:
https://sandbox.semantic-mediawiki.org/wiki/Issue/SRF/200

Instead of just asking for "OK", it would be better to ask for a page name it should create.
But anyhow, in a first version you could create a page with the coordinates as name...

**Comment by JeroenDeDauw** [comment]
Oh... this is actually surprising to me: you need to specify the name before you get to the form? I was expecting a "create new XYZ" form where you enter the name of the thing to create. Is that not possible with Page Forms?

**Comment by krabina** [comment]
both is possible in Page Forms:
https://www.mediawiki.org/wiki/Extension:Page_Forms/Linking_to_forms
you can have the #forminput parser function that displays a field to enter the name the user whishes to create and you have the #formlink parser function that has pagename as value.

**Comment by krabina** [comment]
as the clicktarget parameter is independent of page forms, it uses the special page:
`|clicktarget=Special:FormEdit/Event/Event {{#time: U | now }}?event[hasDate]=%clickyear%-%clickmonth%-%clickday%&returnto={{FULLPAGENAME}}`

**Comment by JeroenDeDauw** [comment]
Special:FormEdit is added by PageForms no?

> you can have the #forminput parser function that displays a field to enter the name the user whishes to create and you have the #formlink parser function that has pagename as value.

Both of these are about steps before getting to the main form right? For the clicktarget parameter we need a special page that itself has the name field. Something like `Special:CreatePage/Event?coordinates=1234`

**Comment by krabina** [comment]
> Special:FormEdit is added by PageForms
yes

well this would be a nice feature of Special:FormEdit to be able to pass a parameter for the pagename.

**Comment by JeroenDeDauw** [comment]
With some help from @yaronkoren I learned that you do not need to pass the page name to FormEdit. So Page Forms already supports the ideal flow here. No extra stuff needed in eventcalendar or in Maps (besides being able to specify a link with dynamic coordinate replacement).

Example Page Forms link: http://www.discoursedb.org/wiki/Special:FormEdit/Author?Author[first%20name]=foo

**Comment by JeroenDeDauw** [comment]
Now I'm wondering how the interaction with the map should look like. Presumably there should be some visual indication that the user can click to make something happen. An icon moving under the cursor seems like a good approach. But what happens when the user clicks? Do they immediately go to the form or is some confirmation needed? Clicking a link would be immediate... So assuming there is a decent indication of the click-ability, maybe a confirmation is not needed.

**Comment by krabina** [comment]
Well this link does call the form "Author", but it does not specify a page name, which is our problem. So what would be the name of the page created with the above link?
I guess the link should be like
http://www.discoursedb.org/wiki/Special:FormEdit/Author/xyz?Author[first%20name]=foo
this would create a page "xyz" with the template "author" where the first name is "foo"

**Comment by krabina** [comment]
The interaction is a good question. currently, clicking on the map is used to move it around, double-clicking, zooms in a littel bit. So yes, I guess it would need some edit icon or so (maybe borrowed from the GeoJSON-editor?)
Right-Click is not a good idea probably, becaus of mobile devices.

**Comment by JeroenDeDauw** [comment]
Why would we need to specify the page name already before the user gets to the form? Much better if the form takes care of it no?

**Comment by JeroenDeDauw** [comment]
Adding a linktarget parameter and sending the user to that location with some coordinates replaced in the value when they click somewhere is not that much work. Adding a dedicated UI for that on the map is a bunch of work though, and not something I can do without funding.

**Comment by krabina** [comment]
> Why would we need to specify the page name already before the user gets to the form? Much better if the form takes care of it no?
yes, but the form does not, not via Special:FormEdit. 

Adding a clicktarget parameter is a very nice and already usable first step!

**Comment by JeroenDeDauw** [comment]
Special:FormEdit does take care of the page name. See the example I linked:

http://www.discoursedb.org/wiki/Special:FormEdit/Author?Author%5Bfirst%20name%5D=foo

This particular form concatenates the values from the first and last name field to get to a page name.

**Comment by krabina** [comment]
yes, but if I click on the eventcalendar and I am only bein asked "ok", the resulting event will be called "Event Eventdate" - there is nowhere where I could specify a page name if I am not asked for it.
