### ISSUE TITLE
runJobs: PHP-Warning: Use of undefined constant MW_VERSION

### ISSUE THREAD

**Issue by m-art-in** [JeroenDeDauw/Maps#585]
### Setup

- Maps version: 7.90.
- MW version:1.31.5
- PHP version: 7.2.5
- SMW version (if applicable): 3.0.2

### Issue
If I start runJobs.php I get this PHP-Warning

`PHP Warning:  Use of undefined constant MW_VERSION - assumed 'MW_VERSION' (this will throw an Error in a future version of PHP) in /PATH/extensions/Maps/src/MapsSetup.php on line 215
`

In the sandbox, I can't reproduce this warning, because it's evoked by command line. I know, it's only a warning, no error, but runJobs.php is a chronjob on my server and sends automatic emails about warnings.... So it's a bit annoying.

**Comment by JeroenDeDauw** [comment]
Issue confirmed

Note to self: fix is https://github.com/JeroenDeDauw/Maps/blob/master/MapsRegistration.php#L39

**Comment by JeroenDeDauw** [comment]
This is more fallout of the absolute shitfest that is https://lists.wikimedia.org/pipermail/wikitech-l/2019-September/092577.html

**Comment by JeroenDeDauw** [comment]
This should be fixed in the just released 7.10.0. Let me know if not.
