### ISSUE TITLE
Maps do not load after edit with visual editor

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#587]
Can be seen on https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Jeroen_De_Dauw/LinesParse by editing and then saving. Map will not load without manually reloading the page.

Cause: editor does not reload the page after save, instead updates the HTML shown via background request.

**Comment by JeroenDeDauw** [comment]
Presumably fixed by https://github.com/JeroenDeDauw/Maps/commit/c7142a5e61e4db47d6413dcf793133e20aaa42f8

**Comment by ivanhercaz** [comment]
This bug seems fixed. I edited the test page with the visual editor and it wasn't necessary to reload it.
