### ISSUE TITLE
Special:MapEditor disappeared

### ISSUE THREAD

**Issue by acnetj** [JeroenDeDauw/Maps#595]
### Setup

MediaWiki | 1.34.0
PHP | 7.4.1 (fpm-fcgi)
MySQL | 5.7.25-0ubuntu0.16.04.2
ICU | 64.2

### Issue

Special:MapEditor is not available with Maps 7.15.2 with MW 1.34. It used to be available with MW 1.31 (it was also with older version of Maps), but the Semantic Media Wiki's site also has the edit page available with latest version of Maps, but MW 1.31. The Sandbox Mediawiki also has the edit page with MW 1.34.

https://www.transit.wiki/Special:Version

https://www.semantic-mediawiki.org/wiki/Special:Version

https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:MapEditor

Don't know if there's any hidden dependency somewhere.

**Comment by JeroenDeDauw** [comment]
That's weird. No idea why this would happen. Can't think of any relevant changes in Maps that could cause this.

**Comment by kghbln** [comment]
I see this special page on sandbox. If I am not mistaken it is a GoogleMaps only feature though.

**Comment by JeroenDeDauw** [comment]
Ah... that might be it. The special page is not registered if google maps is not enabled.

@acnetj did you change the `$egMapsAvailableServices` setting? `googlemaps3` needs to be in the array for the page to show.

**Comment by acnetj** [comment]
I never change that and I still use Google prominently on the site.

**Comment by JeroenDeDauw** [comment]
@acnetj well no idea...

This is the code that registers the page. Maybe it is not being executed somehow? https://github.com/JeroenDeDauw/Maps/blob/master/src/MapsSetup.php#L55-L58

**Comment by JeroenDeDauw** [comment]
Works fine https://maps.extension.wiki/wiki/Special:MapEditor
