### ISSUE TITLE
geocode missing i18n message

### ISSUE THREAD

**Issue by Nikerabbit** [JeroenDeDauw/Maps#60]
Core test fails me locally because of missing i18n message:
1) UserTest::testAllRightsWithMessage
Each user rights (core/extensions) has a corresponding right- message.
Failed asserting that two arrays are equal.

**Comment by JeroenDeDauw** [comment]
What message would this be?

**Comment by JeroenDeDauw** [comment]
@kghbln any idea?

**Comment by Nikerabbit** [comment]
That would be right-geocode and possibly also action-geocode. But I see them exist. Perhaps missing "global $wgAvailableRights" in Maps.php?

**Comment by JeroenDeDauw** [comment]
Should be fixed in 2c89e0a9a1b2ee81b2ba29bdd0b78e9d1064c35b

**Comment by kghbln** [comment]
Great that this worked out. Still the "action-geocode" message is missing for this user-right. Will do a pull-request for this.
