### ISSUE TITLE
Allow for padding of maps

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#606]
### Issue

Sometime the points displayed on a map are located at it's very border resulting in the respective marker being hidden from display. Providing a parameter that allows for padding to also include the display of the respective marker on the map will be a nice enhancement.

Alternatively an automatic padding could be applied to every map. Not sure what the best approach is here though I probably prefer an optional solution.

Zooming out does not appear to be a solution because the zoom levels are not sufficiently fine grained.

### Example
See [this example](https://www.chamapedia.ch/wiki/Wegkreuze) where the three most northern makers are cut off from the map display.

![image](https://user-images.githubusercontent.com/1104078/75625875-743a9200-5bc2-11ea-838a-2aca7f576320.png)

**Comment by JeroenDeDauw** [comment]
https://stackoverflow.com/questions/19407985/leaflet-js-fitbounds-with-padding

**Comment by kghbln** [comment]
@JeroenDeDauw Cool!
