### ISSUE TITLE
Classes non-compliant with psr-4 autoloading standard

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#610]
### Setup

- MediaWiki | 1.31.6 (1ec03b3)19:38, 18 March 2020
- PHP | 7.2.24-0ubuntu0.18.04.3 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Maps | 7.15.6 (4c3b0f1) 16:21, 9 February 2020 

### Issue
Composer grumps and I grump too because grump is my reserved right:

```
Deprecation Notice: Class Maps\Tests\Semantic\ValueDescriptions\AreaDescriptionTest located in ./extensions/Maps/tests/Integration/Semantic/ValueDescriptions/AreaDescriptionTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Maps\Tests\Integration\parsers\RectangleParserTest located in ./extensions/Maps/tests/Integration/parsers/RectlangleParserTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Maps\MediaWiki\Specials\MapEditorHtml located in ./extensions/Maps/src/MediaWiki/Specials/MapEditorHTML.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Comment by JeroenDeDauw** [comment]
What Composer version are you using?

**Comment by kghbln** [comment]
> What Composer version are you using?

1.10.1 but the grump came with [1.10.0](https://github.com/composer/composer/releases/tag/1.10.0)

**Comment by JeroenDeDauw** [comment]
If I get a clone of this repo and run `composer install` I do not get any such notices. This is with 1.10.1 as well. Where are you seeing these notices?

**Comment by JeroenDeDauw** [comment]
Ah found it: `-o`

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/JeroenDeDauw/Maps/commit/f1f0f56bd1282277b006fdc5f2fb4ea3abbeaa39 and https://github.com/JeroenDeDauw/Maps/commit/8fd32c6db95355784c295cb297110a27c3124d13

The namespace and class name needs to match the directories and file name. This is how you fix it in SMW and elsewhere.

In Maps we had one typo in a file name, one mismatch in capitalization between file and class name, and one class in the wrong namespace.

**Comment by kghbln** [comment]
> The namespace and class name needs to match the directories and file name. This is how you fix it in SMW and elsewhere.

Thanks for the tip. I was able to fix this for SMW. Cool.
