### ISSUE TITLE
Exclude NS by default in SMW result formats

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#618]
![image](https://user-images.githubusercontent.com/146040/81484891-99462380-9249-11ea-9a8e-1816dfa3653d.png)

**Comment by krabina** [comment]
I agree, Maps should treat this the same way as SMW. (Of coure, it is always great to have a config variable to set this otherwise).

**Comment by JeroenDeDauw** [comment]
Example of table result format not including NS by default: https://www.semantic-mediawiki.org/w/index.php?title=Special:Ask&#search

**Comment by JeroenDeDauw** [comment]
@krabina @kghbln Is there some standard option in SMW that impacts display of the namespace part in query results?

**Comment by krabina** [comment]
just leared this: https://www.semantic-mediawiki.org/wiki/Help:Namespace_prefix

**Comment by kghbln** [comment]
See also https://www.semantic-mediawiki.org/wiki/Help:Search_namespace_restrictions, however I am not aware of a syntax that allows you to specifically exclude a namespace.

**Comment by JeroenDeDauw** [comment]
Ok, so then there is no setting of parameter that changes if the namespace bit is shown or not, right?

**Comment by kghbln** [comment]
Affirmative.
