### ISSUE TITLE
Is there a list of all possible layers?

### ISSUE THREAD

**Issue by rbirmann** [JeroenDeDauw/Maps#632]
Haven't been able to find a list of all possible options to the `{{#display_map}}` parameters. Specially the `layer` parameter.

**Comment by JeroenDeDauw** [comment]
https://github.com/JeroenDeDauw/Maps/blob/master/DefaultSettings.php#L163-L226 (Assuming you use Leaflet)

**Comment by kghbln** [comment]
Documented on [maps.extension.wiki](https://maps.extension.wiki/w/index.php?title=Leaflet_Maps_examples&type=revision&diff=506&oldid=281)
