### ISSUE TITLE
Pins missing on map

### ISSUE THREAD

**Issue by infecticide** [JeroenDeDauw/Maps#637]
Versions:
Mediawiki 1.34.2
PHP 7.4.3 fpm-fcgi
MariaDB 10.3.22
ICU 66.1

Semantic Bundle 3.2.0
Maps 7.20.1

I have a number of category pages where I want to list a set of related pages with a map up top showing pin drops where these places are located.

I have the source code of each category page set like this:

{{#ask:
[[Category:Cemetery]]
|?Has coordinates
|format=map
}}

The leaflet map renders and it shows a few, but not all, of the locations.   The pages referenced in the category all use the same templates and they all have coordinates attached to them.

The site can be viewed here:
https://forgottenlives.ca/wiki/index.php?title=Category:School

Example of a site where the pin drop works:  https://forgottenlives.ca/wiki/index.php?title=Arbana_SD_683

Where it doesn't:  https://forgottenlives.ca/wiki/index.php?title=Regina_View_SD_4607

What have a I missed setting up correctly?

**Comment by JeroenDeDauw** [comment]
Can you put an ask query with a map that does not work side by side with the same query but then using the table format? Then I easily can see what data is not shown.

**Comment by infecticide** [comment]
I have added the format=table to this page as you requested:  https://forgottenlives.ca/wiki/index.php?title=Category:Cemetery

**Comment by JeroenDeDauw** [comment]
I'm not sure what is not working for you. The table contains 10 coordinates and there are 10 pins on the map.

In the table you can see your query is too general: you get ALL pages in the category, even those that do not have coordinates. You can limit this to only pages that have coordinates with:

```
{{#ask:
[[Category:Cemetery]] [[Has coordinates::+]]
|?Has coordinates
|format=table
}}
```

**Comment by infecticide** [comment]
The [[Has coordinates::+]] was the missing sauce!   It appears to be working as I expect now.

Thank you!
