### ISSUE TITLE
Error On MW 1.35 Upgrade

### ISSUE THREAD

**Issue by Foreclosurepedia** [JeroenDeDauw/Maps#638]
Doesn't matter what I try to do, update, upgrade, even pushing with Composer:

Fatal error: Uncaught UnexpectedValueException: callback 'MapsRegistration::onRegistration' is not callable in /home/iafstghq/digitalmatrixgroup.com/includes/registration/ExtensionRegistry.php:539
Stack trace:
#0 /home/iafstghq/digitalmatrixgroup.com/includes/registration/ExtensionRegistry.php(232): ExtensionRegistry->exportExtractedData(Array)
#1 /home/iafstghq/digitalmatrixgroup.com/includes/Setup.php(161): ExtensionRegistry->loadFromQueue()
#2 /home/iafstghq/digitalmatrixgroup.com/maintenance/doMaintenance.php(91): require_once('/home/iafstghq/...')
#3 /home/iafstghq/digitalmatrixgroup.com/maintenance/update.php(253): require_once('/home/iafstghq/...')
#4 {main}
  thrown in /home/iafstghq/digitalmatrixgroup.com/includes/registration/ExtensionRegistry.php on line 539

**Comment by kaffeeringe** [comment]
@Foreclosurepedia: Can you tell, what the problem was? I got the same error.
