### ISSUE TITLE
Failed to parse or geocode on Google Geocode

### ISSUE THREAD

**Issue by StatusQuo** [JeroenDeDauw/Maps#64]
Failed to parse or geocode is shown when using {{#geocode:New York|service=google}} and i cant figure out why!

Maps 3.2.2
MW 1.24.1

**Comment by JeroenDeDauw** [comment]
Does it also fail without `|service=google`?

**Comment by StatusQuo** [comment]
Found out that the API limit is reached with my hoster strato. Is there any way to avoid using hosters IP for geocode request?

**Comment by JeroenDeDauw** [comment]
Not at present. Such a feature overlaps with #63
