### ISSUE TITLE
Add a way to choose the cache backend for geocoding

### ISSUE THREAD

**Issue by prudloff-insite** [JeroenDeDauw/Maps#644]
We have a wiki with a lot of geocoded addresses so we set `$egMapsGeoCacheTtl` to a long TTL, in order to avoid using too many Google Maps API queries.

However, our wiki uses an APCU cache as the main cache:
```php
$wgMainCacheType = CACHE_ACCEL;
$wgSessionCacheType = CACHE_DB;
$wgParserCacheType = CACHE_DB;
```

Since, `MapsFactory` uses `CACHE_ANYTHING` as the cache type, this means it will use `CACHE_ACCEL` on our wiki.
This cache is typically short lived and tends to expire before the long TTL set in `$egMapsGeoCacheTtl`.

This is why it would be useful to have a way to set another cache type in the config.
(In the mean time, we patched `MapsFactory` to explicitly use `CACHE_DB` but it is a bit dirty.)

**Comment by JeroenDeDauw** [comment]
Seems like you already figured out almost everything needed to make a pull request ;)
