### ISSUE TITLE
Version 8.0.0 of Maps prevents the CodeMirror extension from working

### ISSUE THREAD

**Issue by Megajoul** [JeroenDeDauw/Maps#646]
### Setup

- Maps version:  8.0.0
- MW version:  1.35.1
- PHP version: 7.3.22
- SMW version (if applicable): 3.2.2

### Issue
Version 8.0.0 of Maps prevents [the CodeMirror extension](https://www.mediawiki.org/wiki/Extension:CodeMirror) from working : the wikicode is no longer highlighted and the  button with the Codemirror-icon.png icon isn't displayed in the editing toolbar that allows for switching syntax highlighting on and off.

**Comment by JeroenDeDauw** [comment]
Did this **not** happen with older versions of Maps?

Is there a public example of the bug? (If so, please post URL)

If there is no public example, can you see if there is an error in your browsers concole?

**Comment by Megajoul** [comment]
Sorry - no public example. 
Downgrading to Maps 7.20.1 solves the problem.
My Firefox console says : `Skipped unresolvable module ext.CodeMirror`
Is it helpful?

**Comment by JeroenDeDauw** [comment]
Are you using the latest version of CodeMirror? Maps used to have some compat code to make Maps work with new versions of MediaWiki. That code got removed in 8.0. Perhaps it was also fixing CodeMirror as side effect.

**Comment by Megajoul** [comment]
I just tried the Git master version of CodeMirror. It solves the problem! Thank you for your time.
