### ISSUE TITLE
openlayers / layer "osmarender" discontinued in 2012

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#65]
I appears that this is [not going to come back](http://wiki.openstreetmap.org/wiki/Osmarender). In current versions this layer renders with pink tiles. Probably worth removing this from code.

**Comment by JeroenDeDauw** [comment]
Was this done by c64c087281447769b9819d0ca5c2ff98bbdf2e12?

**Comment by kghbln** [comment]
I believe not all of it. I guess it is just a matter of also removing [L63-94](https://github.com/JeroenDeDauw/Maps/blob/3400c960f70b40429d3ece4533fc23541fdc77cf/includes/services/OpenLayers/OSM/OpenStreetMap.js#L63)?

**Comment by JeroenDeDauw** [comment]
You can actually link to that: https://github.com/JeroenDeDauw/Maps/blob/3400c960f70b40429d3ece4533fc23541fdc77cf/includes/services/OpenLayers/OSM/OpenStreetMap.js#L63-L94

**Comment by JeroenDeDauw** [comment]
Here you go https://github.com/JeroenDeDauw/Maps/pull/127

**Comment by JeroenDeDauw** [comment]
Btw, you should now have merge rights on MW extensions on my GH
