### ISSUE TITLE
No map shown, when using #ask

### ISSUE THREAD

**Issue by Tywyn** [JeroenDeDauw/Maps#650]
Hi,

I am trying to do my first steps with Maps and Semantic Media Wiki and I cannot get the code examples I found on https://maps.extensions.wiki to work.
I created a Template:City and added two pages "Fürth" and "Blarney" to my wiki (1.35.1, Maps 8.0.0, Maps is displayed in Versions-Page).
Then I setup a test-page with 3 parts (see code below). Parts 1 and 2 are displayed properly, but code part 3) does not display anything. 

What did I do wrong?
Are there any log files I can check?

Thanks in advance for your help. 
If this is not the right place to ask such questions, please give me a hint, where to do so?

Rainer

```
<!-- 1) Map is being displayed -->`
{{#display_map:
  Fürth;
  Blarney
}}

<!-- 2) Table with 2 cities and coordinates are being displayed -->
{{#ask: [[Category:Cities]]
 | format=table
 | ?Coordinates
}}

<!-- 3) Nothing is displayed -->
{{#ask: [[Category:Cities]]
 | format=googlemaps
 | ?Coordinates
}}
```

**Comment by JeroenDeDauw** [comment]
Did you define `Coordinates` as geographic property? https://www.semantic-mediawiki.org/wiki/Help:Type_Geographic_coordinates

**Comment by Tywyn** [comment]
Thank you for your answer Jeroen. Indeed I missed that. I now put in `/index.php/Attribut:Coordinates` the `[[Has type::Geographic coordinates]]` but still I get no map displayed. 
It is not, that there is a map without markers. There is just no map shown at all for the code in 3)

**Comment by Tywyn** [comment]
After having revisited the Testpage after a few minutes, now the maps are being displayed. Strange, but I guess the original problem is solved.

I there a forum for mediawiki?

**Comment by JeroenDeDauw** [comment]
> After having revisited the Testpage after a few minutes, now the maps are being displayed. Strange, but I guess the original problem is solved.

Yes, the values in SMW take some time to update if you change the property type.

> I there a forum for mediawiki?

Don't think so
