### ISSUE TITLE
Equals sign in {{#display_map: syntax stops map being displayed

### ISSUE THREAD

**Issue by jrbray1** [JeroenDeDauw/Maps#653]
### Setup

- Maps version: 	7.20.1
- MW version: 1.35.0
- PHP version: 7.4.3
- SMW version (if applicable): 

The adding of the '=' to the end of Netherlands causes the map to not display in
`{{#display_map:
  Berlin~The city Berlin~Berlin is a really nice city and there is plenty of Club Mate;
  Amsterdam~The city Amsterdam~Amsterdam is the capital of The Netherlands=;
}}`

What I want to do is display an external image when clicking on the map
`{{#display_map:
  Amsterdam~The city Amsterdam~Amsterdam is the capital of The Netherlands <IMG src="http://fileserver.com/Canal.jpg" width =200>;
}}`

And its the '=' that is stopping me. I could do just http://fileserver.com/Canal.jpg, but then the image is too big, I need the IMG tag to scale it

The <display_map> syntax does accept the '=' sign, but is not compatible with the ExternalData extension I'm using.

The problem seems to be a parsing issue that an equals sign anywhere switches the line from data to control argument

**Comment by JeroenDeDauw** [comment]
You can't put HTML in there. Wikitext is supported.

**Comment by jrbray1** [comment]
My solution was to use {{#tag

<pre>
{{#tag:display_map|
Berlin~city~<IMG SRC="">
| height="600" | width="600" | scrollwheelzoom="on" | cluster="yes" | service="leaflet"}}
</pre>

Ticket can be closed as workaround acceptable.
