### ISSUE TITLE
Merge "missing" system messages

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#67]
The following system messages are used by both [googlemaps](https://semantic-mediawiki.org/wiki/Help:Google_Maps_format), [openlayers](https://semantic-mediawiki.org/wiki/Help:OpenLayers_format) and [leaflet](https://www.semantic-mediawiki.org/wiki/Help:Leaflet_format) should be "aliased":

**maps-par-zoom**
* [x] maps-googlemaps3-par-zoom -> maps-par-zoom
* [x] maps-openlayers-par-zoom -> maps-par-zoom
* [x] maps-leaflet-par-zoom -> maps-par-zoom

**maps-par-searchmarkers**
* [x] maps-googlemaps3-par-searchmarkers -> maps-par-searchmarkers
* [x] maps-openlayers-par-searchmarkers -> maps-par-searchmarkers

**maps-par-resizable**
* [x] maps-googlemaps3-par-resizable -> maps-par-resizable
* [x] maps-leaflet-par-resizable -> maps-par-resizable
* [x] maps-openlayers-par-resizable -> _already_ maps-par-resizable

**Comment by JeroenDeDauw** [comment]
Should we keep this open?

**Comment by kghbln** [comment]
Yes. I think it is just a matter of replacing the dupes?

**Comment by kghbln** [comment]
@JeroenDeDauw Finally did this. To much pressure right now by @PeterTheOne to make the next release even more fluffier. :)
