### ISSUE TITLE
Add missing message documentation

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#69]
See [translatewiki.net](https://translatewiki.net/w/i.php?title=Special:Translate&group=ext-maps&language=qqq&filter=!translated&action=translate) for the missing 76 help texts for translators

**Comment by kghbln** [comment]
That's actually a bug

**Comment by JeroenDeDauw** [comment]
Should we keep this open?

**Comment by kghbln** [comment]
Yes, down to 75 in the meantime. I should do it soon.

**Comment by JeroenDeDauw** [comment]
Or better yet, recruit someone else to do it :)

**Comment by kghbln** [comment]
Dream a little dream <s>of</s> with me. Actually a very good song.

**Comment by kghbln** [comment]
Down to 69, will do one after the other now to get rid of his one.

**Comment by kghbln** [comment]
Finally down to 0! \o/ Just took me a year. Additionally I made all of them consistent in appearance and checked them.

@JeroenDeDauw Doing this I learned of multiple parser functions I was not aware of at all. This extension was like a box of chocolates.

**Comment by JeroenDeDauw** [comment]
![chocolate-bunnies](https://cloud.githubusercontent.com/assets/146040/16131399/43efc33e-340e-11e6-8a36-f2b6a7dbaf29.jpg)

**Comment by kghbln** [comment]
Cool: https://github.com/JeroenDeDauw/Maps/commit/58d03bebc194484902a40f35099e57489ff6eaf7
