### ISSUE TITLE
image added via imageoverlay parameter does not render

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#70]
The specified image does not render on the [map on a regular wiki page](https://semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_ground_overlays). There is only an invisible though clickable field at the specified spot on the map. Currently only the preview on ["Special:MapEditor"](https://semantic-mediawiki.org/wiki/Special:MapEditor) works

**Comment by kghbln** [comment]
That's probably related to issue https://github.com/JeroenDeDauw/Maps/issues/51

**Comment by JeroenDeDauw** [comment]
Looking at the linked page it seems this has been fixed. Can you confirm?

**Comment by kghbln** [comment]
> Looking at the linked page it seems this has been fixed. Can you confirm?

@JeroenDeDauw Affirmative, the image renders now but the link specified does no longer work. Should I create a new issue for this?

**Comment by JeroenDeDauw** [comment]
I suppose that is an improvement. New issue yes
