### ISSUE TITLE
Per overlay meta data do not work for Openlayers

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#74]
I am not absolutely sure but I think this is a feature request since I do not know if this is supposed to work. I tried to add lables and other stuff as metadata to an overlay generated by OpenLayers. This does not work: [see version history](https://semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_map_with_one_marker_having_an_inline_label)

**Comment by JeroenDeDauw** [comment]
Yeah, only markers can have meta data when using OpenLayers

**Comment by kghbln** [comment]
Thanks!
