### ISSUE TITLE
Semantic map displays "loading" and fails to load

### ISSUE THREAD

**Issue by davidepiga** [JeroenDeDauw/Maps#77]
Hi,

I am trying to fix a map that doesn't work here: http://wiki.km4dev.org/Members_-_Map

I checked the syntax: correct, checked js errors: none, checked for incompatible extensions: none, checked for known bugs in MW version that could impact extension: none, checked php config files syntax for errors or missing parameters: none.

Unfortunately I don't have access to server logs, but nothing where I checked seems to be wrong. In fact I noticed that at times the map shows up correctly, only to disappear again if I refresh the page. See attached screenshot. 

Would you be able to help?

![screenshot 2015-05-08 14 12 56](https://cloud.githubusercontent.com/assets/12400030/7574116/c4bcd12e-f822-11e4-8fac-c1de73933933.png)

**Comment by kghbln** [comment]
I have just checked with the web console of my browser: JavaScript returns "ReferenceError: hasClass is not defined" when not loading. This may be the issue but I dunno where it comes from.

**Comment by davidepiga** [comment]
Update: I just randomly opened the page again and now it works. Having looked at @kghbln 's comment (thanks!) I checked with the web console of my browser and the JavaScript error is still there, so I assume the error is not related to the problem with the map not loading. Hope this helps.

![screenshot 2015-05-14 11 52 01](https://cloud.githubusercontent.com/assets/12400030/7630685/7f0cdd80-fa30-11e4-87c7-5647a4a1da9d.png)

**Comment by JeroenDeDauw** [comment]
Please reopen if still an issue with Maps 3.5 and SM 3.3
