### ISSUE TITLE
[3.2.3] Fatal error: Failed to parse or geocode

### ISSUE THREAD

**Issue by gesinn-it** [JeroenDeDauw/Maps#78]
* MW 1.25.1
* Maps 3.2.3

installed via Composer

{{#geocode:Brandenburg Gate, Berlin, Germany}}

results in "Fatal error: Failed to parse or geocode" after some time

**Comment by JeroenDeDauw** [comment]
#ItWorksForMe

Are you using the default geocoding settings?

**Comment by gesinn-it** [comment]
should be default. Geonames account created and activated for API use

// Mapping services configuration
        $GLOBALS['egMapsAvailableServices'] = array(
                'googlemaps3',
                'openlayers',
                'leaflet',
        );
        $GLOBALS['egMapsDefaultService'] = 'googlemaps3';
        $GLOBALS['egMapsDefaultServices'] = array(
                'display_map' => $GLOBALS['egMapsDefaultService'],
        );

// Geocoding
         $GLOBALS['egMapsAvailableGeoServices'] = array(
                'geonames',
                'google',
                'geocoderus',
        );
        $GLOBALS['egMapsDefaultGeoService'] = 'geonames';
        $GLOBALS['egMapsUserGeoOverrides'] = true;
        $GLOBALS['egMapsAllowCoordsGeocoding'] = true;
        $GLOBALS['egMapsEnableGeoCache'] = true;
        $GLOBALS['egMapsGeoNamesUser'] = 'MyActivatedGeonamesAccount';

**Comment by JeroenDeDauw** [comment]
Do you get this failure for all requests (ie also for other locations)? Perhaps you exhausted your request quota? Maps is not handling the requests in a very optimized fashion, see #14
