### ISSUE TITLE
[3.2.3] NetworkError: 404 Not Found - http://localhost:8080/wiki01/index.php/Theme/default/style.css

### ISSUE THREAD

**Issue by gesinn-it** [JeroenDeDauw/Maps#79]
* MW 1.25.1
* Maps 3.2.3

installed via Composer.

{{#display_map: Berlin, Germany
 |service=openlayers 
}}

raises

"NetworkError: 404 Not Found - http://localhost:8080/wiki01/index.php/Theme/default/style.css"

in Firebug. Any ideas?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this

**Comment by JeroenDeDauw** [comment]
Can you apply this change and tell me if that fixes the issue? https://github.com/JeroenDeDauw/Maps/pull/80/files

**Comment by gesinn-it** [comment]
Hi Jeroen, no,

NetworkError: 404 Not Found - http://localhost:8080/wiki01/theme/default/style.css

oooeehm, by-the-way, the folder theme/default does not exist in MW folder. Sorry for not checking this before...

MW 1.25?

**Comment by JeroenDeDauw** [comment]
I also have that error on my Wiki, though figured it was not coming from the Maps extension...

**Comment by JeroenDeDauw** [comment]
I created a `3.2.4` release now. Perhaps that fixes it for you.

**Comment by gesinn-it** [comment]
... updating to 3.2.4 did not solve the issue, still the same error in Firebug.

Shouldn't the correct path be:
http://localhost:8080/wiki01/extensions/Maps/includes/services/OpenLayers/OpenLayers/theme/default/style.css

By-the-way: "theme" is now again with an uppercase "T", I think it should be lowercase "t"

Found this old issue:
http://sourceforge.net/p/semediawiki/mailman/message/29639756/

**Comment by JeroenDeDauw** [comment]
I just realized that I forgot to apply my change on one location: https://github.com/JeroenDeDauw/Maps/commit/c1f57e507168711c15d9ca99fc29e78205c6ffba

I suspect this is not what is causing your error though.

I'm guessing it is coming from https://github.com/JeroenDeDauw/Maps/blob/master/includes/services/OpenLayers/OpenLayers.php#L37. Not sure in which manner though. You can confirm it is related to that by changing the file reference there from `style.css` to `foobar.css` and see if your error changes accordingly.

**Comment by gesinn-it** [comment]
updated to c1f57e5

changing style.css to foobar.css changes the behavior as follows:

instead of raising the error in Firebug, the map area stays gray saying "Loading map...". No error in Firebug, no timeout.

**Comment by gesinn-it** [comment]
In the meanwhile I checked
* with MW 1.23.9, SMW 1.9.2, SM 3.0.4 => same error
* changed VM settings from NAT to Bridged networking => same error

**Comment by gesinn-it** [comment]
the error is caused by:

includes/services/OpenLayers/OpenLayers/OpenLayers.js

this.theme=OpenLayers._getScriptLocation()+"theme/default/style.css";

**Comment by JeroenDeDauw** [comment]
Ah! Good find. I only ran my search against the PHP code >_>

**Comment by JeroenDeDauw** [comment]
I'm actually not sure what to do about this...

**Comment by gesinn-it** [comment]
found this:

https://www.drupal.org/node/1188996

**Comment by JeroenDeDauw** [comment]
Based on that I am thinking the issue would probably go away if #88 is done

**Comment by Fannon** [comment]
This problem is caused by the Resource Loader (appending ?debug=true to the URL should fix this problem).

This is because the Ressource Loader aggregates all JS and serves it as a single file. That file has of course the wrong relative path.

To fix this, overwrite the OpenLayers._getScriptLocation() function to use a static, correct path:

https://gist.github.com/Fannon/1ed55d6caf532a99fe02

(Add lines 4-6)

Best,
Simon

**Comment by JeroenDeDauw** [comment]
@Fannon can you submit that as a pull request?

**Comment by JeroenDeDauw** [comment]
@gesinn-it can you try the fix? If it works then I'll merge #89

**Comment by gesinn-it** [comment]
yes, issue fixed. Thanks @Fannon @JeroenDeDauw for having a look into this!

**Comment by JeroenDeDauw** [comment]
I just created a 3.3.0 release which includes this fix
