### ISSUE TITLE
openlayers / selector for markers duplicated in overlays section

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#87]
The layerswitcher menue selectable via the (+) offers an overlays section for selecting or deselecting the markers. The checkbox for this is duplicated. See [this docu page](https://semantic-mediawiki.org/wiki/Maps_examples/OpenLayers_with_layer_maps) for an example.

MW 1.24.1, SMW 2.2, Maps 3.2.3 on PHP 5.3.3

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue!

**Comment by PeterTheOne** [comment]
This was fixed in #143.

**Comment by kghbln** [comment]
Cool. Thanks for fluff!
