### ISSUE TITLE
Update OpenLayers to a recent version

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/Maps#88]
Maps contains OpenLayers 2.11 which was released in 2011. As of November 2018 the latest version of OpenLayers is 5.3.

---

For 500 EUR I can justify spending the time on this upgrade. Write me at jeroendedauw at gmail.com if you are interested.

**Comment by kghbln** [comment]
@JeroenDeDauw Does this include removing the afaik obsolete "Layer" namespace or is this an extra issue to be created?

**Comment by JeroenDeDauw** [comment]
This is not about the Layer NS. Which is not obsolete, though quite possible rather broken. The last set of big changes to it was kinda half-assed.

**Comment by kghbln** [comment]
Ah, ok, understood!

**Comment by JeroenDeDauw** [comment]
It's 6 years old now, and we have skipped OpenLayers 3.x altogether and are now at 4.1 :D
