### ISSUE TITLE
Add OSM support to the map editor

### ISSUE THREAD

**Issue by a01020304uk** [JeroenDeDauw/Maps#93]
Is it possible to use OSM instead of Google when using MapEditor as when using Google the lines of roads are completely different than that of OSM

It would be good to use OSM as a choice when drawing lines if using OSM maps and Google when using Google Maps. on Special:MapEditor

As you can see here the red line is what google maps draws, but in reality the osm is no where the same as line is completely different when shown on osm map  (osm of the road is correct whereas google is totally wrong and not easily changed as mapmaker keeps rejecting the edit)

http://i.imgur.com/GMDLIWr.jpg

**Comment by JeroenDeDauw** [comment]
This si not currently possible, though thanks for the feature request!

**Comment by samwilson** [comment]
This would be great. Especially if one could choose other OSM renderings (such as railways).

**Comment by JeroenDeDauw** [comment]
Superseded by https://github.com/JeroenDeDauw/Maps/issues/482
