### ISSUE TITLE
Pull Map Coordinates from Article Code

### ISSUE THREAD

**Issue by a01020304uk** [JeroenDeDauw/Maps#94]
I like the simplicity of the map code but instead of having long bits of code+coordinates could the simple code pull the coordinates from code in the arcticle.

| lat  = 55.5555
| lon = -44.4444

The map code seems to suggest it can do this but no documentstation/instructions to say how.  If this was possible then the map code could be places in a template then pulled into the article and the coordinates read and then map displayed.

**Comment by JeroenDeDauw** [comment]
You want to have a look at Semantic Maps: https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/README.md

**Comment by a01020304uk** [comment]
I did have a look at that but could not find the specific solution, it seems to go on about geolocation than the specific thing I was after. do you have a specific link to an example

**Comment by JeroenDeDauw** [comment]
You can look at the https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki documentation - what you are asking about can also be done with data other than coordinates. You just need Semantic Maps if you want to do it with coordinates as well.

**Comment by a01020304uk** [comment]
sorry to sound like an idiot but added that extention and spent nearly 2 hours looking at the docs but it talks about geocordinates and other stuff but just cannot see any example or page that explains how to take the |lat |lon from an article and display the image like:
{{#display_map: {lat},{lon}|mappingservice=leaflet|zoom=15}}

**Comment by JeroenDeDauw** [comment]
I recommend you ask about this on the SMW user mailing list: https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_mailing_lists
