### ISSUE TITLE
Semantic Maps not rendering map when #ask (ing) and using format map

### ISSUE THREAD

**Issue by Tao108** [JeroenDeDauw/Maps#96]
I use mediawiki 1.25.2 Semantic MediaWiki 2.2.2 Semantic Maps 3.2 http://chinabuddhistencyclopedia.com/en/index.php/Special:Version

When using

{{
#ask:
[[Has coordinates::+]]
| ?Has coordinates
| format=map
}}

i get absolutely nothing. But when i render #displaymap then no problems. And if i use format=table then it renders with #ask also but with format=map nothing.

(I tested it one night didnt work at all, then next morning i opened and it worked. Then i added more coordinates to database and it stopped showing again.)

http://chinabuddhistencyclopedia.com/en/index.php/Category:Buddhist_Geography page where #ask in entered

and page http://chinabuddhistencyclopedia.com/en/index.php/Buddhist_Sites_in_Afghanistan_and_Central_Asia where i inserted [[Has coordinates::31° 57' 12.65" S, 115° 51' 25.37" E]]

and another page is  http://chinabuddhistencyclopedia.com/en/index.php?title=Buddhist_Cosmology_By_Ken_Holmes&action=edit      [[Has coordinates::33° 57' 12.35" S, 113° 51' 25.37" E]]

Is there something im missing here i have looked around and not find any fix to this.

Or is this some bug in the maps??

Can somebody please help me because it seems i cant get my way around it

Thank you very much!!!

**Comment by Tao108** [comment]
There is some explained here https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1201

**Comment by JeroenDeDauw** [comment]
Why do you think this is related to SemanticMediaWiki/SemanticMediaWiki#1201?

**Comment by kghbln** [comment]
They were two issues here, the [first one](https://semantic-mediawiki.org/wiki/Thread:Talk:Semantic_Maps/Semantic_Maps_not_rendering_map_when_ask_(ing)_and_using_format_map/reply) was the missing datatype declaration and the second issue was a compat thing with MW 1.25+ which was fixed with SMW 2.2.3

**Comment by JeroenDeDauw** [comment]
Thanks @kghbln!
